### ISSUE TITLE
Fix viewlet documentation

### ISSUE THREAD

**Issue by kakshay21** [plone/documentation#1005]
* **I'm submitting a ...**
  - [ ] bug report
 
* **Do you want to request a *feature* or report a *bug*?**
Bug in the documentation of viewlet

* **What is the current behavior?**
Currently, the viewlet manager shows configure.zcml configuraton instead of viewlet manager class.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
https://docs.plone.org/develop/plone/views/viewlets.html#id1
<img width="895" alt="screen shot 2018-07-11 at 2 30 41 pm" src="https://user-images.githubusercontent.com/13598994/42561548-0a88113a-8517-11e8-8e98-c7319fb5b727.png">

I asked this in community 👉 https://community.plone.org/t/problem-in-ordering-viewlets/6798

**Comment by stevepiercy** [comment]
Closing as won't fix. Plone 5.
