### ISSUE TITLE
Update tools part of how to contribute

### ISSUE THREAD

**Issue by svx** [plone/documentation#1006]
# Description

Currently our docs about tools about contributing/writing docs like editors, etc are kind of outdated.

There are more editors and manuals these days on how to setup you stuff for reST. including testing etc, etc, etc

**Comment by Rupeshiya** [comment]
@svx  I would like to work on this ,can you give the file location where to make changes ??

**Comment by tkimnguyen** [comment]
@Rupeshiya you can search this repository. Likely @svx meant this folder https://github.com/plone/documentation/tree/5.1/about/contributing

**Comment by Rupeshiya** [comment]
thanks @tkimnguyen ,should I add some editors ,usages ,their plugins for reST.

**Comment by tkimnguyen** [comment]
Maybe before you make any pull requests you could explain here what you propose to add

**Comment by Rupeshiya** [comment]
I would like to add some Helper Tools For Writing Documentation  like  UliPad(https://code.google.com/archive/p/ulipad/) , Editra(http://editra.org/preview) , TextMate(https://macromates.com/manual/en/),  Pycharm(http://www.jetbrains.com/pycharm/).
If I am correct ?? Have a look at it.  @tkimnguyen

**Comment by tkimnguyen** [comment]
It would help for the tools to be specifically useful to writing Plone documentation, e.g. RST editors, previewers, syntax checkers, etc., and then for each one you’d have to explain briefly how to set it up, how to use it.

**Comment by stevepiercy** [comment]
FWIW, PyCharm finally got reStructuredText preview in v2018.2, and has had a Sphinx builder and reStructuredText syntax checker for years. There's a professional paid edition and a community free edition. And they support open source software by giving the project's core developers free professional editions via [open source licenses](https://www.jetbrains.com/buy/opensource/), if the organization asks. Pylons Project has such an agreement with JetBrains.

I would not want a comprehensive list. It's yet one more thing to maintain, so a few big commercial players and a few free or open source options would be helpful. I still see newbies slogging away on the default Windows text editor at meetups, and I feel bad for them.

**Comment by Rupeshiya** [comment]
@stevepiercy  Ulipad and Editra are open source (free of cost) ,we should add them in the list ?

**Comment by svx** [comment]
For me IMHO, this part of the docs should be less about specific editors, and more about general things with links to examples.
Adding more and more different editors is IMHO not the best way, cause it adds lots of extra work for us to keeping the docs up to date and it also could be confusing for people.

**Comment by stevepiercy** [comment]
@Rupeshiya I have never heard of either editor until now. Do they satisfy the requirements for making it easier to write documentation?

If I understand @svx's comment, he would prefer an entry that gives developers sufficient information up front with explicit references and examples, perhaps something like this? What do you think @svx?

PyCharm has [support for reStructuredText](https://www.jetbrains.com/help/pycharm/restructured-text.html) preview, syntax checker, syntax highlighting, [docstring generation](https://www.jetbrains.com/help/pycharm/using-docstrings-to-specify-types.html#example), and Sphinx builders. There's a paid professional edition and a free community edition. [View feature comparison](https://www.jetbrains.com/pycharm/features/editions_comparison_matrix.html). [Download](https://www.jetbrains.com/pycharm/download/).

That makes it easier to choose a tool that satisfies requirements for writing docs without hunting down details at various websites or web pages.

**Comment by svx** [comment]
@stevepiercy yeah ! exactly !

And this maybe for the "most common ones" we know people use, for example:

- PyCharm
- Sublime
- VsCode

? 

I rather prefer editors people use already and if we really want we can always link to a custom dd search with rst editors or something for example, or we could add an extra document for "documentation nerds" :)

**Comment by stevepiercy** [comment]
PyCharm and the PSF does an annual developer survey, and the [top 10 editor tools are listed](https://www.jetbrains.com/research/python-developers-survey-2017/#tools-and-features). I assume there is significant bias for PyCharm in the results. I filtered by Web Developers, because that's what we are:

% | Editor
--|-------
30% | PyCharm Professional Edition
14% | Sublime Text
12% | PyCharm Community Edition
11% | Vim
10% | VS Code
9% | Atom
3% | Emacs
2% | Eclipse + Pydev
2% | IDLE
2% | Notepad++

Based on that data and my knowledge of their features, I agree that PyCharm, Sublime, and VS Code should be listed. I have no idea about the others' qualifications as good editors for writing documentation.

**Comment by svx** [comment]
I also used Atom a lot for writing rst and md based docs, it is working well, too.

Vim, NeoVim, Emacs, etc also working well and they have plugins, too.

IMHO we can care less about these, of you use VIm, etc, you also now how to do the setup and where to find plugins I would say :)

**Comment by stevepiercy** [comment]
I've heard good things about Atom.

There's also [butterflies](https://www.xkcd.com/378/).

One of these days I'll learn how to quit vim aside from closing the terminal window.

I think the 4 we've cited is good enough for now.

**Comment by spereverde** [comment]
new list of editors on https://www.jetbrains.com/lp/python-developers-survey-2020/
unsure if you should continue this if for Plone 6 we're moving to a markdown based setup?

**Comment by stevepiercy** [comment]
PyCharm has good support for Markdown, reStructuredText, and MyST.

**Comment by stevepiercy** [comment]
Authors gonna use the tools at their fingertips. This issue would add a maintenance burden. Closing as won't fix.
