### ISSUE TITLE
Problem with "Install Plone Using A Minimal Buildout on Ubuntu 18.04"

### ISSUE THREAD

**Issue by jensens** [plone/documentation#1010]
My intern followed the instructions and she found the following problems with 
https://docs.plone.org/manage/installing/installation_minimal_buildout.html on Ubuntu 18.04:

1. On Ubuntu 18.04 Pip for Python 2.7 is installed as ``pip2``.
2. Virtualenv is then installed as ``virtualenv``.

IMO this document may need more context.

**Comment by svx** [comment]
Well the whole docs are not updated and adjusted for 18.04.

Currently the docs are stating 16.04.

So, yes we need to update the complete docs to make them work with 16.04 and 18.04

**Comment by jensens** [comment]
and while at it, a note: A hint to install the dependend system-libraries before would help too.
