### ISSUE TITLE
Can't find chapter in repo

### ISSUE THREAD

**Issue by ida** [plone/documentation#1017]
Hi, wanted to add some notes to https://docs.plone.org/develop/coredev/docs/intro.html but somehow cannot find the corresponding page in the repo, could someone please give a hint where it's located?

It' about how start a Jenkins-job and what to do when the build breaks. Not so sure about the latter part though. This is the sketch to append to the doc:

```
To start Jenkins, first copy the URL of the browser's address-bar, then click
the link "Details" in the pull-request where it says "Please run the job".

You should then land on jenkins.plone.org and can paste the URL into the
provided text-field, finally click "Build now".
Wait until tests finished that should take about half an hour.

If the build broke, go to "https://jenkins.plone.org/job/pull-request-5.1"
(or is it "https://jenkins.plone.org/job/plone-5.1-python-2.7" ?)
and click "Build now", that will start a Jenkins-job on the current code base
and make tests pass again.

You can leave the PR as is, no need to close or anything, and take your time
to fix the errors, then start a PR again.

When the PR got merged or you decide to withdraw it, please be nice and delete
the branch, so not too much unneeded space is occupied.
```

**Comment by polyester** [comment]
Hi @ida , 
that has to be done in the buildout.coredev repo, specifically https://github.com/plone/buildout.coredev/tree/5.1/docs (or 5.2 for the 5.2 branch).
It's best to make a separate .rst file, and then link it in the index.rst

the whole docs folder of buildout.coredev is 'pulled in' to the docs.

**Comment by ida** [comment]
@polyester: Ah ok. Wanted to use the web-editor and searched this repo, but now see in "[how to update the docs](https://docs.plone.org/develop/core`dev/docs/updateme.html)" it's documented to checkout `buildout.coredev`, as you write. Thank you!

**Comment by ida** [comment]
@polyester Closed this assuming the issue should be added to `buildout.coredev`, was that correct?
And I'd refrain from making an additional RST-file, if you don't mind, because the doc is really helpful to have a step-by-step checklist for making a complete contribution within one page.
