### ISSUE TITLE
Please follow our styleguides

### ISSUE THREAD

**Issue by svx** [plone/documentation#1024]
Hi,

First of all it is awesome and really great that people start writing docs about how to migrate to Python 3 !

**Thanks you!!**

But, please can you make sure that you follow our style-guide and best practices about `rst`  practices from the beginning ?

Going later on though all these files and fix them, will be a huge effort and we are trying really hard (since the PloneConf in Brazil) to fix and improve the quality of our docs in general.

Again, it is really nice that you take time to write docs, but please also make sure to follow our best practices and style-guides.

For example: https://raw.githubusercontent.com/plone/documentation/5.2py3/manage/upgrading/version_specific_migration/upgrade_to_python3.rst

really needs some attention, that document is currently mixing various styles and has lots of room for `rst` improvements.

We want to archive docs which are understandable and readable !

So, please, please follow our guides they are there for a reason, the same as you/we have tests for code.

Thanks !

**Comment by stevepiercy** [comment]
To help developers toward the path of good documentation, what are the canonical links to the Style Guide and best practices? Let's be explicit, please.

**Comment by svx** [comment]
As said and written already many many times :)

A  good starting point is:

https://docs.plone.org/about/contributing/index.html

Which links to our style-guides:

https://docs.plone.org/about/contributing/rst-styleguide.html

https://docs.plone.org/about/contributing/documentation_styleguide.html

:)

And yes, people may have different opinions or may use different ones, but we use these :)

**Comment by spereverde** [comment]
@svx can we close this issue or is it needed as a gentle reminder 😄

**Comment by stevepiercy** [comment]
Superseded in Plone 6 docs, at temporary URL: https://6.dev-docs.plone.org/contributing/index.html
