### ISSUE TITLE
Line Length clarification

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1027]
There are some conflicts within the [Line Length section](https://docs.plone.org/about/contributing/documentation_styleguide.html#line-length).

> - Use semantic linefeeds when you are editing.
> - (snip)
> - One sentence per line.

These conflict with one another. For the non-professional documentation writer, one sentence per line is a lot easier rule to understand than semantic line feeds. I would much prefer one sentence per line.

Personally I can't _stand_ semantic line feeds because it makes it much harder to read when editing. It's like reading bad adolescent shoe-gazer emo poetry.

> Please do not follow PEP8 maximum line length standard.

Appears twice in this section. I'd suggest deleting the second instance.

> Limiting lines to a maximum of 130 characters.

This conflicts with "one sentence per line". Suggest its removal.

**Comment by svx** [comment]
About the line length, what is if we say aim to keep your lines to around 130 chars, I use something like that in other guides, because it gives you an idea, but it is no "hard" setting, 140 chars is 150% fine, if it fit the sentence :)

**Comment by stevepiercy** [comment]
I don't see any benefit by limiting line lengths. Most editors soft-wrap lines, so contributors don't need it. It doesn't show up to readers, so they don't need it. Keeping it adds one more rule to remember and to enforce.

**Comment by svx** [comment]
Done for Plone 6 documentation linter.
We use a soft setting of 140 if you use more the test is still passing but suggesting that you may want less.

**Comment by stevepiercy** [comment]
The narrative text was not changed. I'll submit a separate PR to fix the text.

**Comment by svx** [comment]
There is no need :) We do that from Plone 6 on.
The whole part of how to contribute and style guide is currently in the process of a rewrite and it is already covered there :)

**Comment by stevepiercy** [comment]
I disagree. Let's not establish bad habits for 5.2 that will be changed in 6. It's too confusing to maintain different style guide standards across multiple versions.

**Comment by stevepiercy** [comment]
More importantly, the guide is inconsistent now. That's a bug and should be fixed.

**Comment by svx** [comment]
Yeah, that is, of course, true, it is just that 6 will a complete rewrite anyway.
There is not much what we will "just" copy over.
But yeah, it can not hurt :)

**Comment by stevepiercy** [comment]
Plone 6 has no line length restriction, other than "one sentence per line". See https://6.dev-docs.plone.org/contributing/writing-docs-guide.html#abridged-plone-documentation-styleguide
