### ISSUE TITLE
Buildout and Plone API Docs

### ISSUE THREAD

**Issue by svx** [plone/documentation#1028]
We have to understand and hopefully fix how we can get rid of buildout for the API docs.

Everything works now fine without buildout, the only remaining headache in the new setup is Plone API.

If there is really no other fix, I will put API in a container and build it with cron every night or something so that we get the HTML.

I do not want to wait every time till buildout is finished and then build the HTML, given that buildout is working at all.

The new setup takes so far around 15 - 20 minutes less time, I would like to optimize that even more and buildout is not really helping :)

**Comment by MrTango** [comment]
What's the problem here, you please describe what shoudl be optimized.
I can help then ;)

**Comment by stevepiercy** [comment]
Closing as we use a git submodule to import plone.api and build its docs.
