### ISSUE TITLE
Certificate Expired: Monday, October 29, 2018 at 4:01:08 PM Pacific Daylight Time

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1031]
The LE cert expired for https://docs.plone.org/ on Monday, October 29, 2018 at 4:01:08 PM Pacific Daylight Time.

**Comment by svx** [comment]
Fixed !

**Comment by stevepiercy** [comment]
That was quick! Thank you!

I noticed in community.plone.org that this happened about 6 months ago, too. Is the auto-renew script not firing as it should?
