### ISSUE TITLE
Add missing statement to local.cfg in upgrade_to_python3.rst

### ISSUE THREAD

**Issue by 1letter** [plone/documentation#1049]
```
custom-eggs +=
    Products.PDBDebugMode [zodb]
    plone.reload

# add auto-checkout directive
auto-checkout +=
    Products.PDBDebugMode

[sources]
Products.PDBDebugMode = git ${remotes:collective}/Products.PDBDebugMode.git pushurl=${remotes:collective_push}/Products.PDBDebugMode.git branch=python3
```

**Comment by stevepiercy** [comment]
@1letter Please submit a pull request against the 5.2 branch for review. Thank you!

**Comment by 1letter** [comment]
I can't do this, because i'm not signing the plone contributor agreement, until now. perhaps, i will try it today at the sprint in munich.

**Comment by 1letter** [comment]
I see there is [pull request](https://github.com/plone/documentation/pull/1050)

**Comment by staeff** [comment]
@1letter - as far as I can see, the PR solved this issue. Do you agree and can this issue be closed?

**Comment by stevepiercy** [comment]
Closing as complete. Reopen if not.
