### ISSUE TITLE
Content/Writing guide and accessibility

### ISSUE THREAD

**Issue by svx** [plone/documentation#1061]
I noticed that the Microsoft Style Guide now recommends using "select" for all UI and keyboard interactions.
They no longer recommend "click" or "press."
From what I hear, this has to do with accessibility concerns with screen readers.

https://docs.microsoft.com/en-us/style-guide/procedures-instructions/describing-interactions-with-ui

@polyester do you have an opinion on that?

**Comment by stevepiercy** [comment]
More verbs to consider replacing include "hover", "point", "tap", and other device-specific actions.

**Comment by polyester** [comment]
Seems reasonable. Both regarding a11y and more diverse ways of operating UI's (speech control, ...) "Select" describes what you should do, not a way in which you should do it, which might vary for any number of reasons. So +1

**Comment by svx** [comment]
Okay, I will add it to the guide and the checks!
Thanks!

**Comment by stevepiercy** [comment]
Styles are are now advisory when using `make vale`. Closing.
