### ISSUE TITLE
Improper naming on https://docs.plone.org/external/plone.app.dexterity/docs/grok/reference/form-schema-hints.html

### ISSUE THREAD

**Issue by zopyx** [plone/documentation#1066]
`IBasic.description` must be `IDublinCore.description` in Plone 5(.2)

https://docs.plone.org/external/plone.app.dexterity/docs/grok/reference/form-schema-hints.html

**Comment by spereverde** [comment]
this was fixed in https://github.com/plone/plone.app.dexterity/commit/86f9062c5907418c442b76ca80bc99f103dfd782
