### ISSUE TITLE
Missing import in https://docs.plone.org/external/plone.app.dexterity/docs/advanced/permissions.html#protecting-form-fields

### ISSUE THREAD

**Issue by zopyx** [plone/documentation#1067]
The given example uses `write_permission()` without actually importing it.

**Comment by ritwikagarwal** [comment]
Can you point out on which line/instance it is?
Thanks

**Comment by spereverde** [comment]
fixed in https://github.com/plone/plone.app.dexterity/commit/43edc3abd76dcaaf7313d49dadec7a24642bee4e in https://github.com/plone/plone.app.dexterity
