### ISSUE TITLE
Search seems to be broken

### ISSUE THREAD

**Issue by jugmac00** [plone/documentation#1075]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**
When I enter a search term, a broken popup appears, see attached screenshot.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
- visit https://docs.plone.org/
- enter any search term in the upper right input field
- see broken pop up appear
(Fedora 28, Chrome 73)

* **What is the expected behavior?**
- working popup / preview

* **What is the motivation / use case for changing the behavior?**
fix whats broken

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
- Fedora 28
- Chrome 73 (also for Firefox 66.02)

![Screenshot from 2019-04-27 09-40-56](https://user-images.githubusercontent.com/9895620/56846610-9217d600-68d1-11e9-9dc2-4ddd0b9a3294.png)

**Comment by acsr** [comment]
FYI: We pickup the topic now during the #PloneConf2019 Sprint in Ferrara!

**Comment by polyester** [comment]
... and it's live
