### ISSUE TITLE
docs.plone.org certificate expires June 10, 2019

### ISSUE THREAD

**Issue by kuetrzi** [plone/documentation#1082]
Possibly automated renewal is not working.

**Comment by svx** [comment]
We are still in May :)

**Comment by kuetrzi** [comment]
Indeed we are. I thought it was worth being proactive with less than 2 weeks to go. It has expired a few times in the past. If you let me know the number of days before expiry you want to be be notified, I'll update our monitoring.

**Comment by kuetrzi** [comment]
Looks like it has now renewed
