### ISSUE TITLE
How do I add a viewer count to my page?

### ISSUE THREAD

**Issue by zhouwuji** [plone/documentation#1088]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by stevepiercy** [comment]
Please open a proper issue report. Closing.

**Comment by stevepiercy** [comment]
For support, please visit https://community.plone.org/
