### ISSUE TITLE
Integrate garbas z3c.form docs?

### ISSUE THREAD

**Issue by gforcada** [plone/documentation#109]
Today a colleague pointed me to: http://garbas.github.io/plone-z3c.form-tutorial/

Which maybe is not comprehensive but gives quite a few useful tips on every page, so I would say worth adding (fixing typos and updating here and there).

**Comment by svx** [comment]
is this still valid ? do we want to do that ?

**Comment by polyester** [comment]
no we don't. Stick to the training.plone.org way, and if necessary integrate some of garbas tips into that.

**Comment by svx** [comment]
ok closing this
