### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by dbitouze** [plone/documentation#1095]
If I'm right, there's a typo line 172 of https://github.com/plone/documentation/blob/5.2/manage/upgrading/version_specific_migration/upgrade_zodb_to_python3.rst. It should be:

`parts +=`

instead of:

`parts =+`

**Comment by ale-rt** [comment]
True! You can fix this directly on github:
https://github.com/plone/documentation/edit/5.2/manage/upgrading/version_specific_migration/upgrade_zodb_to_python3.rst
but remember to write a meaningful changelog and to select the radio button "Create a new branch for this commit and start a pull request"

**Comment by dbitouze** [comment]
I preferred to just open an issue since I didn't sign the Plone Contributor Agreement that lets me merge pull requests.

**Comment by ale-rt** [comment]
Documentation does not require it, right @plone/documentation-team

**Comment by tkimnguyen** [comment]
I’m sure somewhere in docs.plone.org it says  (Contributing?) that you can stare in your PR that you grant us all rights if you haven’t already signed the contributor agreement.

**Comment by tkimnguyen** [comment]
s/stare/state/

**Comment by dbitouze** [comment]
Done (hope the changelog is meaningful enough).

**Comment by polyester** [comment]
Just to weigh in: a simple typo does *not* need a contributor agreement, as it does not constitute a "work" in copyright law. Of course, @dbitouze you are very welcome to sign one anyway and enjoy the warm fuzzy feeling of being a fully-fledged Plone contributor ;-)

There's not a super-clear division line between what is a "work" and what is not, but a few-characters typo definitely doesn't need a Contributor Agreement.

**Comment by spereverde** [comment]
thanks for fixing this @dbitouze 🙂
