### ISSUE TITLE
Apache as front-endfor Plone: NameVirtualHost will be removed in the next (Apache) release

### ISSUE THREAD

**Issue by dbitouze** [plone/documentation#1097]
The (Plone 5) documentation about [Apache as front-end Web Server for Plone](https://docs.plone.org/manage/deploying/front-end/apache.html#installing-apache-front-end-for-plone) tells you to add a virtual host configuration file `/etc/apache2/sites-enabled/yoursite.conf` containing (among other things):

`NameVirtualHost *`

But, when Apache is restarted, the following warning appears:

>AH00548: NameVirtualHost has no effect and will be removed in the next release /etc/httpd/conf/...

Probably the documentation should be revised here but I've no idea of what should written instead (I'm quite ignorant about Apache).

**Comment by stevepiercy** [comment]
[Third hit in DDG](https://serverfault.com/questions/576939/namevirtualhost-has-no-effect).

The docs should also use the latest version of Apache 2.4.x. 2.2.x is no longer maintained and has issues. However I don't know anyone who uses Apache for a front end web server for Plone these days who would take on the maintenance of this page of the docs.

**Comment by dbitouze** [comment]
>However I don't know anyone who uses Apache for a front end web server for Plone these days who would take on the maintenance of this page of the docs.

Does it mean Nginx may be a better choice?

**Comment by stevepiercy** [comment]
No. It means use whatever works for you and your situation. That said, nginx is more popular and has lots more documentation in the Plone community, including in [automated deployments](https://docs.plone.org/external/ansible-playbook/docs/webserver.html).

**Comment by stevepiercy** [comment]
Also I would suggest you take this to the [community forum](https://community.plone.org) to get a broader perspective, because fewer people monitor the docs repo than exist in the community.

**Comment by ataoleo** [comment]
apach&nbsp;



---Original---

**Comment by dbitouze** [comment]
@stevepiercy 
>Also I would suggest you take this to the community forum to get a broader perspective, because fewer people monitor the docs repo than exist in the community.

Of course, thanks anyway for the hints.

**Comment by dbitouze** [comment]
@ataoleo Your message seems to be incomplete.

**Comment by tkimnguyen** [comment]
@dbitouze nginx is definitely more popular nowadays for Plone installs. I have not seen a production deployment that uses Apache in quite some time. If you look in the https://github.com/plone/ansible-playbook the current best practice is to use nginx. However if someone is able to update the Apache section in our docs that would be great!

**Comment by dbitouze** [comment]
@tkimnguyen Unfortunately, my OS (Linux Mageia 7) seems to not be supported:

>We generally support relatively current CentOS and Debian/Ubuntu environments. Versions currently supported are Ubuntu 18.04 (Bionic) LTS, 16.0.4 (Xenial) LTS, Ubuntu 15, Debian jessie, Debian stretch, and CentOS 7.

**Comment by dbitouze** [comment]
@tkimnguyen Moreover, I'm using Plone 5.2 with Python3 and I don't know if it is compatible with the fact:

>Ansible requires that the target server have a recent Python 2.x on the server.

**Comment by tkimnguyen** [comment]
We just redeployed a lot of Foundation servers with the playbook so maybe that part of the docs is just out of date. 

If your OS or distro isn’t on the list you can still follow something like the https://github.com/plone/simple-plone-buildout maybe

**Comment by dbitouze** [comment]
@tkimnguyen
>We just redeployed a lot of Foundation servers with the playbook so maybe that part of the docs is just out of date.

I reloaded the corresponding page but I didn't see any update.

>If your OS or distro isn’t on the list you can still follow something like the https://github.com/plone/simple-plone-buildout maybe

This seems to not be adapted to my Linux Mageia server:

>For UNIX based operating systems the Plone unified installer is the preferred method.

**Comment by stevepiercy** [comment]
Closing as won't fix. Please create a pull request if you want to write the docs for this.
