### ISSUE TITLE
start mentioning easyform alongside PloneFormGen

### ISSUE THREAD

**Issue by tkimnguyen** [plone/documentation#1104]
This is related to #711 but since easyform is not as fully featured as PFG it can't really (yet) be considered a replacement.

However, Plone 5.2 on Python 3 will not run PFG, which is Archetypes-based, making easyform the only viable TTW form tool.

With that in mind, we need to start mentioning easyform in the docs where PFG is mentioned or documented, e.g. https://docs.plone.org/working-with-content/managing-content/ploneformgen/index.html

**Comment by stevepiercy** [comment]
I'd accept a PR that either points to easyform's docs directory or import those docs into Plone 6 Documentation. To do the latter:

- Convert to MyST: https://6.docs.plone.org/contributing/documentation/admins.html#importing-external-docs-and-converting-to-myst
- Import as a submodule: https://6.docs.plone.org/contributing/documentation/admins.html#importing-external-docs-with-submodules

I don't use this add-on, so I'm not motivated to do the work myself, but I would be happy to assist and review a pull request.

**Comment by stevepiercy** [comment]
Per https://github.com/collective/collective.easyform/issues/105#issuecomment-2389036490, pulling in the docs is off the table. There are also plenty of docs for forms in Plone 6 core already.

Closing as won't fix, but if you have something actionable, you can create a new issue.
