### ISSUE TITLE
Document PLIP 1775: CMFQuickInstallerTool removal Plone 6

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/documentation#1123]
PLIP 1775 was merged. Some documentation would be needed. The [comment](https://github.com/plone/Products.CMFPlone/issues/1775#issuecomment-620915913) can be the basis for that.
Where would that need to be added? In the 5.2 branch? I see a 6 branch but not much has happened there.

Let me copy the comment, and amend a bit.

# portal_quickinstaller removed

See [PLIP 1775](https://github.com/plone/Products.CMFPlone/issues/1775).

The `portal_quickinstaller` tool is longer added to new sites. In existing sites, it will be removed during upgrade to Plone 6.0. For installation code in an add-on you should no longer create an `Extensions/install.py` file, but create a `GenericSetup` profile, as has been the norm for years.

Since Plone 5.1 deprecation warnings were shown for no longer supported methods. These methods have now been removed.

The best source of information for dealing with this change, is the upgrade guide for add-ons from Plone 5.0 to 5.1: https://docs.plone.org/develop/addons/upgrade_to_51.html#installation-code

**Comment by spereverde** [comment]
Everything Plone 6 backend related should go into https://github.com/plone/documentation/tree/backend-6

Maybe we could add this inside a (new) migrating plone 5 to plone 6 section under https://docs.plone.org/manage/upgrading/version_specific_migration/index.html?

I searched and can't find any documentation on portal_quickinstaller, only notes about not using it anymore inside the developing add-ons and migration docs you already mentioned

**Comment by mauritsvanrees** [comment]
Meanwhile done.
