### ISSUE TITLE
Broken links for collective under Contributing to Plone Core

### ISSUE THREAD

**Issue by XinyiXiang** [plone/documentation#1128]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**
Reporting a bug

* **What is the current behavior?**
Page error 404

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Go to https://docs.plone.org/develop/coredev/docs/agreement.html#contributing-to-plone-core, click on collective external link

* **What is the expected behavior?**
Direct to collective.github.io

* **What is the motivation / use case for changing the behavior?**
Potentially due to false suffix of URL, should have been `collective.github.io` instead of `.com`

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
Searched through the repo and have not found the subfolders for this page of documentation so I suppose I should submit this issue to the core

**Comment by polyester** [comment]
acknowledged. I will release fix this weekend. Thanks for reporting!
