### ISSUE TITLE
broken ploneformgen links

### ISSUE THREAD

**Issue by ThibautBorn** [plone/documentation#1129]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**
There are still Links to the 'ploneformgen' products page, but these do not longer seem to exist. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
see links to ploneformgen products page : 
e.g.
    * https://docs.plone.org/develop/plone/forms/index.html
    * https://docs.plone.org/working-with-content/managing-content/ploneformgen/index.html

* **What is the expected behavior?**
to be redirected correctly: either link to another page like pypi (https://pypi.org/project/Products.PloneFormGen/), or remove the links?

* **What is the motivation / use case for changing the behavior?**
Documentation shouldn't have broken links:..

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by stevepiercy** [comment]
@ThibautBorn would you please submit a pull request that replaces the URL https://plone.org/products/ploneformgen with https://pypi.org/project/Products.PloneFormGen/ throughout the entire set of documentation?

I don't think a redirect is necessary.

**Comment by polyester** [comment]
I'll fix this on Saturday. Thanks @ThibautBorn for reporting.

**Comment by polyester** [comment]
fixed via https://github.com/plone/documentation/pull/1132 ; will deploy tomorrow

**Comment by spereverde** [comment]
Thanks!
