### ISSUE TITLE
Plone 6: [dev] Backend / Classic UI 

### ISSUE THREAD

**Issue by MrTango** [plone/documentation#1137]
#### structure

Keep it as flat as possible, very long stories should be handled in trainings. Short examples (tutorial style) should stay in the docs close to the context.
Backend is relevant for Headless and Classic UI, if in doubt keep it in backend for the moment.

##### Backend

- content types
- behaviors
- annotations
- vocabularies
- fields
  - schema
    - autoform (directives) ordering/filtering/permissions
  - supermodel (xml) 
    - autoform (directives) ordering/filtering/permissions
- widgets
    - autoform (directives): widget/fieldset
- plone_view/utils (global functions CMFPlone/plone.app.layout)
- portal actions
- users and groups
- security
  - permissions
  - roles
    - global roles
    - local roles 
  - sharing
- workflows
- search
  - catalog
  - querystring 
- ZODB
- plone.api (probably stay external)
- plone.restapi (probably stay external)
- sending email

##### Classic UI

- static resources
- theming
- templates
- views
- viewlets
- forms
- portlets
- Cross-Site Request Forgery (CSRF): only ui?
- TTW
  - Templates
  - RestrictedPython
  - conten types

#### Tasks:

- [x] #1142
- [x] #1138  [Zope Page Templates](https://zope.readthedocs.io/en/latest/zopebook/ZPT.html)
- [ ] #1143
- [x] #1144

**Comment by stevepiercy** [comment]
@MrTango regarding the four task checkboxes, I am not clear about what you mean. Perhaps these should be separate issues?

Also an update: I have completed the structure for `backend`, and I have started on `classic-ui` in my draft PR #1141

**Comment by stevepiercy** [comment]
I addressed the structure in PR #1141.

I created new issues for the tasks where they can be tracked.

Closing.
