### ISSUE TITLE
Document resource registry in `classic-ui/static-resources`

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1142]
Document resource registry in `classic-ui/static-resources`.

old docs: 
- https://5.docs.plone.org/adapt-and-extend/theming/resourceregistry.html

**Comment by MrTango** [comment]
This looks like a good not to big task for @jensens right?

**Comment by MrTango** [comment]
done already: https://6.docs.plone.org/classic-ui/static-resources.html

**Comment by gforcada** [comment]
Isn't there a way to programatically enable/disable bundles to be rendered? i.e. I have a specific view that needs some specific JS and/or CSS, so I create a bundle with that JS/CSS, and on that view I call a method that will inject the bundle resources into the final HTML.

That would be nice to have documented. I guess, we should create a new issue, right? or is that documented somewhere else?

**Comment by stevepiercy** [comment]
@gforcada unless some content expert responds, I would suggest that you create a new issue. It might exist in Plone 5 docs, and needs to be updated for Plone 6, but I lack familiarity to be certain.
