### ISSUE TITLE
Automate deployment to 6.dev-docs.plone.org

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1146]
We need to deploy documentation under development to ~~`6-dev.docs.plone.org`~~ `6-dev-docs.plone.org`.

- [x] Create space for automatic deployments under our own hosting.
- [x] Get DNS entry to point `6-dev-docs.plone.org` to our own hosting.
- [x] Configure our server to resolve requests to the space.
- [x] Create secrets and add them to [Settings > Secrets](https://github.com/plone/documentation/settings/secrets/actions)
- [x] Update GitHub Actions configuration [`.github/workflows/build_deploy.yml`](https://github.com/plone/documentation/blob/6-dev/.github/workflows/build_deploy.yml)

**Comment by stevepiercy** [comment]
@ericof or any other DNS manager, can you work your magic to create the necessary DNS entry?

> `6-dev.docs.plone.org` to `6-dev-docs-plone-org.netlify.app`

**Comment by polyester** [comment]
@stevepiercy @ericof  it appears that Cloudflare (at least on our opensource level) does not provide multiple level subdomains SSL - for that you need an (expensive) extra. So, I've set up 6-dev-docs.plone.org to point to 6-dev-docs-plone-org.netlify.app but that probably needs to be set up in Netlify as well.

**Comment by stevepiercy** [comment]
Thank you! That should work, as soon as the pull request gets merged to `6-dev`. Right now, that branch lacks sufficient build configuration.

We could use another pair of eyes to review https://github.com/plone/documentation/pull/1141. I ported the contributing stuff from Trainings, but it definitely needs review by someone with your talent and experience, @polyester.

A temporary URL to view the build on Netlify is https://61e8de5e50d8f50008c486f8--6-dev-docs-plone-org.netlify.app/

**Comment by stevepiercy** [comment]
I deployed a preview of the PR to `6-dev-docs-plone-org.netlify.app` but it appears the CNAME entry for `6-dev-docs.plone.org` does not resolve to it. @polyester @ericof @tkimnguyen would you please check the DNS for this?

```shell
$ host -t cname 6-dev-docs.plone.org
6-dev-docs.plone.org has no CNAME record
```

See instructions: https://docs.netlify.com/domains-https/custom-domains/configure-external-dns/#configure-a-subdomain

**Comment by polyester** [comment]
I had set it with the (default) setting "proxy". After some googling, that appears wrong as Netifly doesn't like to be proxied. Now set it as "DNS only". That makes the connection, host -t cname 6-dev-docs.plone.org is correct, but obviously gives an SSL error. So presumably a LetsEncrypt one needs to be set in Netifly, according to https://docs.netlify.com/domains-https/https-ssl/

**Comment by stevepiercy** [comment]
I need to provide a custom certificate per https://docs.netlify.com/domains-https/https-ssl/#custom-certificates

This is not a great option because the cert does not auto-renew and would require manual intervention. 🤮 

We might be better off with hosting the site ourselves, like we do with Trainings. @ericof set up keys with GitHub Actions to do an automatic deployment.

Another option would be to use ReadTheDocs.org, now that we are using just Sphinx and MyST. But I'm going to wait on that because there could be a step with importing docs for Volto.

**Comment by polyester** [comment]
hmm, doesn't https://docs.netlify.com/domains-https/https-ssl/#netlify-managed-certificates imply that they auto-renew even for a custom domain? OTOH, we should be able to host on own site.

**Comment by stevepiercy** [comment]
Yes, but only if they manage the DNS, and I assume we do not want to do that.

See https://docs.netlify.com/domains-https/custom-domains/#assign-a-domain-to-a-site under "If the domain is registered (already has an owner),":

Second and third bullet points:

- If the domain was registered elsewhere, you can choose to use Netlify DNS for automatic configuration, branch subdomains, and automatic HTTPS on all subdomains with wildcard certificates. To get started, visit the doc about adding a domain to Netlify DNS.
- Alternatively, if the domain was registered elsewhere, and you want to continue using your current DNS provider, you will need to add DNS records on your provider to point your domain or subdomain to your site on Netlify. Visit the external DNS instructions to complete your configuration.

**Comment by stevepiercy** [comment]
I think we are left with two options for deploying docs.

1. Host our own, like we do with Training. @ericof helped with that. I think the advantage of that is control, but the disadvantage is supporting the infrastructure.
2. ReadTheDocs. This has a unique advantage of generating ad revenue with Ethical Ads, if we so choose. We do this with the Pylons Project, and donate the $20/month we get from it to the Python Foundation. It's [trivially easy to set up a secure certificate for a custom domain with RTD](https://docs.readthedocs.io/en/stable/custom_domains.html#custom-domain-support).

I would really appreciate opinions from @ericof @polyester @tkimnguyen and any other AI member to advise.

**Comment by stevepiercy** [comment]
That was rude @mister-roboto! Reopening.

**Comment by tkimnguyen** [comment]
It might be a good thing to reduce the load on our admin team

**Comment by tkimnguyen** [comment]
If we could use exactly the same infrastructure as for the training docs then there is no extra burden on the admin team and it has the advantage of being in the exact same place with the same processes and workflow

**Comment by tkimnguyen** [comment]
Using Netlify or some other infrastructure would be more burden in the sense that it would be one more stack to manage and one more place to remember

**Comment by polyester** [comment]
I'm in favor of using our own infra:

- there is no real extra burden, as we need a VM for static HTML for other things as well (docs for 3,4,5, archive.plone.org, training, etc)
- it's fairly trivial to host static html anyway
- it gives control to add some extras, like a landing page, or rewrites for instance if it turns out that incoming links on sites beyond our control are wrong.

**Comment by spereverde** [comment]
Also in favor of using same infrastructure as training

**Comment by stevepiercy** [comment]
The consensus is to use our own infrastructure to host the docs. I have updated the checklist at the top of this issue. It is assigned to @ericof, but if anyone else has the knowledge and permission to make the necessary changes as we did for Trainings, feel free to pick up the issue and tag @ericof that you're working on it.

**Comment by ericof** [comment]
@stevepiercy Deploying to [6.dev-docs.plone.org](https://6.dev-docs.plone.org)

**Comment by stevepiercy** [comment]
Fantastic! Thank you! Closing.

**Comment by ksuess** [comment]
Shouldn't there already be a frontend chapter?

**Comment by stevepiercy** [comment]
There will be as soon as I merge #1160. Please stand by.
