### ISSUE TITLE
Use redirects to avoid link rot with sphinx-reredirects

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1149]
Configuring the web server for redirects requires an admin.

This Sphinx extension allows the author to add a redirect to the file itself.

See https://github.com/documatt/sphinx-reredirects/issues/3 and open PR https://github.com/documatt/sphinx-reredirects/pull/6.

At this moment we do not have any specific redirects, but we might in the future.

**Comment by liborjelinek** [comment]
Hi there, just FYI that in today released sphinx-reredirects 0.1.5, the above mentioned PR to check validity of redirect URLs has been merged.

**Comment by stevepiercy** [comment]
@liborjelinek thanks for the heads up!

**Comment by stevepiercy** [comment]
Closed by #1601
