### ISSUE TITLE
Customize the theme to align with Plone branding

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1150]
The primary navbar needs some love. I'm not sure why the title and logo are not stacked.

![Screen Shot 2022-01-19 at 4 25 49 PM](https://user-images.githubusercontent.com/102112/150240026-ad119472-4080-4c5b-a44a-2d1243b632ff.png)

**Comment by nileshgulia1** [comment]
@stevepiercy I can take this.

**Comment by nileshgulia1** [comment]
hm... looks good in https://6-dev-docs.plone.org

**Comment by stevepiercy** [comment]
This turned out to be a configuration issue in `conf.py` from not copying over the required CSS:

```python
html_static_path = [
    "_static",
]
```
