### ISSUE TITLE
Investigate Netlify as possible deployment infrastructure

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1154]
Investigate Netlify as possible deployment infrastructure without piling onto an existing server. It's just static content.

**Comment by stevepiercy** [comment]
This was pretty tricky, but I got it to work. Here's a temporary URL to preview the docs:

https://61e8de5e50d8f50008c486f8--6-dev-docs-plone-org.netlify.app/

Netlify creates a unique preview URL with a hash for every build, which is triggered on every push to a PR against `6-dev`.

See also #1146.

**Comment by stevepiercy** [comment]
Is there anyone else who would like to join the Plone 6 Docs team on Netlify?

**Comment by ksuess** [comment]
yes, I am curious.

**Comment by stevepiercy** [comment]
When I was about to add @ksuess and @tkimnguyen, Netlify warned me:

> Inviting 1 new member will add 1 extra seat at $15.00/month to your monthly bill.

I applied Plone Documentation as an Open Source Project, and I am awaiting a response.

**Comment by stevepiercy** [comment]
Also add @flipmcf and @spereverde

**Comment by tkimnguyen** [comment]
Another way to deploy for free is to GitHub pages with Jekyll, e.g. https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll and you can set a custom domain

**Comment by stevepiercy** [comment]
> Another way to deploy for free is to GitHub pages with Jekyll, e.g. https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll and you can set a custom domain

How would that work with our chosen infrastructure of Sphinx and MyST?

**Comment by stevepiercy** [comment]
It's been a couple of business days since I requested an Open Source License. Given the slow response, and the inability to automatically renew a secure certificate for a custom domain on Netlify without using them for domain management, I'm going to close this issue as "will not fix".

If anyone finds information contrary to my findings, I would really appreciate it.

Otherwise, we can discuss which service might fit the bill in https://github.com/plone/documentation/issues/1146

**Comment by stevepiercy** [comment]
As a side note, I just got approval from Netlify as a team. Nonetheless we decided to go with our own infrastructure for hosting the Documentation as discussed in #1146.

**Comment by stevepiercy** [comment]
I've also transferred this site to the [Netlify team Plone](https://app.netlify.com/teams/plone/overview), and invited @flipmcf, @tkimnguyen, and @ksuess to join, but I need @spereverde's email to invite her.
