### ISSUE TITLE
Search results should show breadcrumbs

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1156]
Currently the search results only show the page title.

They should display the full path as breadcrumbs, as well as the page title, similar to DuckDuckGo.

![Screen Shot 2022-01-19 at 4 19 41 PM](https://user-images.githubusercontent.com/102112/150239454-8bbfccc7-12a4-4290-b99e-239cb00f3815.png)

**Comment by ksuess** [comment]
Closing with follow-up https://github.com/plone/documentation/issues/1177
