### ISSUE TITLE
Replace outdated gulp with alternative for live update of local set up

### ISSUE THREAD

**Issue by ksuess** [plone/documentation#1157]

**Comment by stevepiercy** [comment]
I use sphinx-autobuild. I pushed 2d3a68723f6ed3bec2b62585e5418b8acc8845ad to https://github.com/plone/documentation/pull/1141 to try it out.

**Comment by ksuess** [comment]
sphinx-autobuild works like a charm. gulp can be removed. docs about gulp also.

**Comment by stevepiercy** [comment]
Done in 835f01aadbb46259fbb147b8032c81d42a536d62.

**Comment by ksuess** [comment]
really nice solution.
