### ISSUE TITLE
Markdownnlint colors my editor - enforce Markdownlint?

### ISSUE THREAD

**Issue by jensens** [plone/documentation#1163]
Usually I write markdown with help of [Markdownlint](https://github.com/DavidAnson/markdownlint) - there's is a neat [VSCode plugin](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint)  - and so I keep my style more consistent.

Unfortunately the docs are in wide parts colored with lots of warnings.

We should fix that!

**Comment by stevepiercy** [comment]
This looks interesting. Sphinx does error checking, so I am surprised it does not catch the errors with `make livehtml`.

At the very least, we can suggest it as a development tool, but I don't know yet whether to make it a requirement.

Can you give an example of something that shows errors, including screenshots?

I would prefer to avoid adding node stuff back, as we just purged it from the project. Is there a Python equivalent? It would be nice to use just one platform, especially when running CI/CD.

**Comment by jensens** [comment]
Like this, mostly the same warnings, VSCode "format document" eliminates most automatically.

![Screenshot from 2022-01-25 13-46-13](https://user-images.githubusercontent.com/157140/150979513-a973e2a8-c705-411a-94c6-9060ae96c547.png)

The there are more valid complaints like

![Screenshot from 2022-01-25 13-48-29](https://user-images.githubusercontent.com/157140/150979982-de2df031-514e-4567-8d92-effbe1a2ebaa.png)

As I am everything but a markdown expert I like these tools.

**Comment by stevepiercy** [comment]
- The label is valid MyST syntax. We are going to keep that.
- Multiple blank lines help provide visual separation between sections, especially when we need a blank line for labels.
- Bare URLs are also OK. We have a configuration value in `conf.py` to convert them to clickable URLs. Yay MyST!

I assume that you can configure the plugin to ignore these warnings, similar to how you would with flake8. I would suggest you do so. These examples are perfectly OK in MyST, as it is a superset of CommonMark.

**Comment by stevepiercy** [comment]
I would accept a configuration dot-file or similar, and we can add the plugin as suggested editing tool. However @ksuess just opened https://github.com/plone/documentation/issues/1164 which might be a better plugin for our purposes. Please try that one out, and let us know what you think.

**Comment by jensens** [comment]
Ok, I was not aware MyST is that special here. I close this one and look at #1164.
