### ISSUE TITLE
Add hint to contributors guidelines: VSCode extension "MyST-Markdown"

### ISSUE THREAD

**Issue by ksuess** [plone/documentation#1164]
VSCode Extension "MyST-Markdown" https://marketplace.visualstudio.com/items?itemName=ExecutableBookProject.myst-highlight

![image](https://user-images.githubusercontent.com/1144737/150935033-81a9c4a9-d39d-4ce8-a859-228d0da4e9f0.png)

![image](https://user-images.githubusercontent.com/1144737/150935717-3e6441f9-fa16-40f4-9fd1-da82d587f936.png)

**Comment by stevepiercy** [comment]
Nice. PyCharm does not have autocomplete for admonitions. It only has CommonMark support, without the MyST superset. I poked them on Twitter for it, and with @pauleveritt who is a Sphinx/MyST advocate, maybe it will happen.

**Comment by pauleveritt** [comment]
Alas, our Markdown support has some refactorings it is focused on. It's unlikely that PyCharm itself will take on MyST support until it reaches usage parity with RST.

**Comment by stevepiercy** [comment]
@pauleveritt checking in to see whether JetBrains recognizes MyST as having parity with reStructuredText?

**Comment by pauleveritt** [comment]
It's not a subsystem we've been current with this year, so no.

**Comment by stevepiercy** [comment]
For anyone who wants to upvote the issue I created for PyCharm:

https://youtrack.jetbrains.com/issue/PY-61291/Support-MyST-syntax
