### ISSUE TITLE
Consider adding some styles to the `plone.api` documentation

### ISSUE THREAD

**Issue by me-kell** [plone/documentation#1169]
Consider adding some styles to the `plone.api` documentation.

https://docs.plone.org/develop/plone.api/docs/api/portal.html
https://docs.plone.org/develop/plone.api/docs/api/content.html
https://docs.plone.org/develop/plone.api/docs/api/user.html
https://docs.plone.org/develop/plone.api/docs/api/group.html
https://docs.plone.org/develop/plone.api/docs/api/env.html
https://docs.plone.org/develop/plone.api/docs/api/exc.html

The `plone.api` is scarcerly styled and is difficult to read. Specially for visually impaired developers.

The headings of Signature, Parameters, Exceptions, Returns, Example etc. look all the same and is difficult to discern them.

It would be very helpful if at least the lines with the signatures could be highlighted.

As far as I can see all the involved html-elements are already marked with the necessary classes.

It would suffice to modify one or two of the styles;

```css
dt.sig {
  /* set e.g. background-color and/or a border-top */
}
dt > span.sig-name {
  /* set e.g. another background-color and/or a style that differenciates this from the rest of the line */
}
```
**Costs:** probably less than 15 Min.
**Benefits:** Better readability. Make documentation accessible.
**Collateral issues:** probably none

**Comment by stevepiercy** [comment]
This issue should be moved to the 5.2 branch on `plone/documentation`.

For Plone 6 Documentation, it is open for discussion whether to import these docs or to have them separate. We are currently running through a [PR with importing Volto docs](https://github.com/plone/documentation/pull/1160) with favorable results. The Docs Team have not begun this conversation with `plone.api` folks, but we might as well start now.

**Comment by stevepiercy** [comment]
@me-kell [plone.api is now imported into Plone 6 docs](https://6.dev-docs.plone.org/plone.api/index.html). Does the issue persist?

**Comment by stevepiercy** [comment]
Closing as complete. Please reopen if the issue persists @me-kell. We won't backport to Plone 5 docs.
