### ISSUE TITLE
To check: Additional Control Script `debug`, `console` and `run` Commands

### ISSUE THREAD

**Issue by svx** [plone/documentation#117]
cheap copy and paste from:
https://github.com/plone/plone.recipe.zope2instance/pull/14/files#diff-88b99bb28683bd5b7e3a204826ead112R508

thanks @do3cc for his tweet about it :)

we should check if we already have that in the docs !

---

+Additional Control Script `debug`, `console` and `run` Commands
+---------------------------------------------------------------

 The extended Zope 2 control script installed by this recipe, usually
 `bin\instance` by convention, offers a `debug` command and another
 @@ -505,6 +505,15 @@ with following options::
 Note that these options must come before the script name,
 e.g. `bin/instance -RLOPlone/front-page debug`

+The `console` command is similar to the fg command, but it does not
+create a subprocess to start up Zope 2. This is useful for two
+use cases. First, the supervisor program, to supervise long running
+processes like a Zope, require the process not to fork away, so that
+supervisor can control it.
+Second, IDEs like WingIDE and PyCharm support debugging running
+processes from within. For this to work, the process should also
+not fork away.
+
 Additional control script commands

---

**Comment by stevepiercy** [comment]
We're up to Zope 5. Closing as won't fix.
