### ISSUE TITLE
Fix dropdown menu (repository, "open issue", "suggest edit")

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1173]
TODO

- [ ] Fix link target of "open issue" for submodules plone.restapi, plone.api, volto
- [x] Target "suggest edit" to contributing chapter: https://6.dev-docs.plone.org/contributing/index.html
- [ ] Fix link target of "repository" for submodules plone.restapi, plone.api, volto

---
See https://github.com/executablebooks/sphinx-book-theme/issues/470

ideally this would open a new issue WITH the new template:
![image](https://user-images.githubusercontent.com/1144737/152471246-d2272ecd-bcd3-42a6-989c-f92b0089aad5.png)

_Originally posted by @ksuess in https://github.com/plone/documentation/issues/1172#issuecomment-1029621250_

**Comment by ksuess** [comment]
Unfortunatly there is no affordable way to change the links "repository" and  "open issue" for the integrated submodules (Volto, plone.api, plone.restapi). So we decided to leave them as they are and add a note on the landing page of the plone/documentation repo: https://github.com/plone/documentation/pull/1292/files
