### ISSUE TITLE
Integrate plone.api documentation in Plone 6 documentation

### ISSUE THREAD

**Issue by ksuess** [plone/documentation#1178]
plone.api 
- has cross references between /docs and docstring / typehint in code. The cross references are more than helpful in docs.plone.org. The cross reference is between narration and signature.
Example: https://docs.plone.org/develop/plone.api/docs/portal.html
- /docs are written in rest not myst.

- [ ] plone.api: Remove GitHub-only message
- [ ] Theming: Highlight header of methods! http://localhost:8000/plone.api/api/relation.html?highlight=delete#plone.api.relation.delete
- [ ] Theming in general

**Comment by mauritsvanrees** [comment]
Thanks for all your work!

Small issue, but may be hard to fix:

- Go to https://6.dev-docs.plone.org/plone.api/index.html
- Click the GitHub icon.
- In the dropdown click on 'Suggest edit'
- You end up on a page that does not exist, giving a 404: https://github.com/plone/documentation/edit/main/docs/plone.api/index.rst
- It should be this: https://github.com/plone/plone.api/edit/master/docs/index.rst

**Comment by stevepiercy** [comment]
@mauritsvanrees there is a known issue https://github.com/plone/documentation/issues/1211

**Comment by stevepiercy** [comment]
@ksuess has this been completed? If yes, are there any issues here that need to be captured in new issues?

**Comment by ksuess** [comment]
Yes, it has been completed. Thanks for taking care, @stevepiercy.
