### ISSUE TITLE
Set default branch to `6-dev` instead of `5.2`?

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1179]
I would prefer to set the default branch of this repo to `6-dev` so that it uses the new issue template and chooser.

I would like to discuss that with the team before changing the setting for the default branch. @polyester @tkimnguyen @svx @spereverde @ksuess what do you all think?

_Originally posted by @stevepiercy in https://github.com/plone/documentation/issues/1175#issuecomment-1034720876_

**Comment by polyester** [comment]
I'm fine with that, with a little preparation:

- announce when the change will happen at community.plone.org
- change https://github.com/plone/documentation/blob/6-dev/README.md so that it links to the right URL for browsing the 6-dev docs, and has a section on the Plone 5.2 docs and points to those as well.

**Comment by stevepiercy** [comment]
I opened a PR to start us off. There may be other things that need to be addressed before switching. Please let me know if you think of anything else.

@polyester what's a reasonable and usual amount of lead time to make the announcement? I will include it in my next Docs update post in the next few days.

**Comment by polyester** [comment]
@stevepiercy maybe two days? Or make it next Monday? And it's probably good to make it a **separate** announcement, so that I (or others with that ability) can pin it to the top of community for a week or so.

**Comment by stevepiercy** [comment]
@polyester posted! Please pin:

https://community.plone.org/t/plone-documentation-repository-to-set-default-branch-as-6-dev/14836

Let's leave this issue open until we set the default branch on Mon, Feb 21.

**Comment by polyester** [comment]
Pinned globally (until March 3), which is the "middle shouty" option; there is one shoutier option which is "Banner pin" but that is a bit in-your-face...

**Comment by stevepiercy** [comment]
Done!
