### ISSUE TITLE
write plone.app.contenttypes best practices 

### ISSUE THREAD

**Issue by svx** [plone/documentation#12]
extend currrent docs about plone.app.contenttypes
with best practices with reference link to dexterity

**Comment by svx** [comment]
@pbauer looks great, but we should structure that a bit more, atm we have a lot what is great ! But we should improve it, it is one long README :)

**Comment by polyester** [comment]
@pbauer, I think everything is there. It just needs splitting up. From the styleguide: the README should be a **short** description of the add-on, not the entire documentation! (Or in this case, the entire unabridged edition of "War and Peace" ;-) 
When my cold is getting better, I'll fix.

**Comment by stevepiercy** [comment]
Superseded by https://github.com/plone/documentation/pull/1455
