### ISSUE TITLE
Check layout after breaking changes in sphinx-book-theme release v0.3.0

### ISSUE THREAD

**Issue by ksuess** [plone/documentation#1209]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

Release sphinx-book-theme v0.3.0 https://github.com/executablebooks/sphinx-book-theme/releases/tag/v0.3.0
See changelog for even newer releases.

**Comment by stevepiercy** [comment]
Going forward, I think we should pin the theme to <0.4.0 in all our repos' requirements files. We're still in development, so I'm not overly concerned about breaking things.

**Comment by ksuess** [comment]
+1 for pinning <0.4.0
And yes it's harmless.
