### ISSUE TITLE
GitHub link for "suggest edit" returns 404 for plone.restapi and volto

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1211]
Visit https://6.dev-docs.plone.org/volto/index.html, click the GitHub Octocat icon, and click "suggest edit". You get a 404 at https://github.com/plone/documentation/edit/main/docs/volto/index.md

The same thing happens with plone.restapi.

The quick fix is to remove the link, but that's not really a good fix.

I don't know if there is a way to override the theme template depending on the path of the file being written.

**Comment by ksuess** [comment]
GitHub link for "suggest edit" overridden for this repo: Impede drive-by edits by linking chapter on how to contribute. Fixed in https://github.com/plone/documentation/pull/1292
