### ISSUE TITLE
Check Netlify build times (make storybook)

### ISSUE THREAD

**Issue by ksuess** [plone/documentation#1216]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

'make storybook' seems to need a rather high amount of build time: yarn, yarn build-storybook.
It's triggered on every netlify build. This is not necessary.

**Comment by stevepiercy** [comment]
I Agree. Let's pull `make storybook` from `make netlify`.

Sphinx takes 32 seconds.

Storybook takes 5 minutes, 9 seconds.

We can't afford to lose that many build minutes.

https://app.netlify.com/teams/plone/builds/insights

**Comment by stevepiercy** [comment]
Closed by https://github.com/plone/documentation/pull/1219
