### ISSUE TITLE
Create "Releasing" section under somewhere TBD

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1258]
We could use a page like this, but then in the general Plone docs in a section about contributing, not specific to `plone.api`.

_Originally posted by @mauritsvanrees in https://github.com/plone/plone.api/issues/476#issuecomment-1136828066_

**Comment by stevepiercy** [comment]
We actually do not yet have a Contributing section for Plone core. I am not sure where it would go.

Is `zest.releaser` used universally to release all of these packages listed in the sections in the navigation?

- [Frontend](https://6.dev-docs.plone.org/volto/index.html)
- [REST API](https://6.dev-docs.plone.org/plone.restapi/docs/source/index.html)
- [Backend](https://6.dev-docs.plone.org/backend/index.html)
  - [A Plone API](https://6.dev-docs.plone.org/plone.api/index.html)
- [Classic UI](https://6.dev-docs.plone.org/classic-ui/index.html)

**Comment by mauritsvanrees** [comment]
Not sure about Volto, but for all others: yes.

**Comment by stevepiercy** [comment]
Here is the current Releasing proposal:

-------

# Releasing

We use `zest.releaser` for releasing the packages used in [REST API](https://6.dev-docs.plone.org/plone.restapi/docs/source/index.html), [Backend](https://6.dev-docs.plone.org/backend/index.html), [A Plone API](https://6.dev-docs.plone.org/plone.api/index.html), and [Classic UI](https://6.dev-docs.plone.org/classic-ui/index.html). The end.

-------

Clearly that could use some work. 🤪
