### ISSUE TITLE
Upgrading Guide

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1269]
### Plone Documentation versions affected

- [X] 5.x
- [X] 6.x

### Description

Per the last [Plone 6 Coordination meeting](https://community.plone.org/t/plone-6-coordination-meeting-2022-07-07/15433/1) we identified an urgent need to work on the Plone 6 Upgrade Guide.

We have a placeholder [Plone 6 upgrade guide](https://6.dev-docs.plone.org/deployment/upgrade.html) under [Deployment of Plone](https://6.dev-docs.plone.org/deployment/index.html) in the main navigation.

I propose the following:

1. Promote "Plone 6 upgrade guide" to the primary navigation level. It does not feel Deployment-ish to me. This page will be a landing page with links to all other upgrading bits and documentation to be created.
2. Add the following links as content to this page:
    - Volto/frontend: [Upgrade Guide](https://6.dev-docs.plone.org/volto/upgrade-guide/index.html)
    - plone.restapi: [Upgrade Guide](https://6.dev-docs.plone.org/plone.restapi/docs/source/upgrade-guide.html)
    - backend (placeholder only): [Upgrading the Backend](https://6.dev-docs.plone.org/backend/upgrading/index.html)
    - [Upgrading to Plone 6.0](https://6.dev-docs.plone.org/backend/upgrading/v60.html) (under [Upgrading the Backend](https://6.dev-docs.plone.org/backend/upgrading/index.html))
3. Solicit developers of add-ons to contribute documentation for upgrading their add-ons.

@esteele @mauritsvanrees @ksuess @pbauer @jensens did I miss anything? Feedback appreciated!

**Comment by ksuess** [comment]
+1 from me. Especially +1 for:
> Promote "Plone 6 upgrade guide" to the primary navigation level.
