### ISSUE TITLE
Edit Contributing docs

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1278]
## Description

We frequently get newbie requests to contribute. Plone 6 docs lack one way to do things, but we have numerous packages and documentation that each have their own way to contribute.

- [Contributing to Documentation](https://6.docs.plone.org/contributing/index.html) - Consider the following:
  - Create a new primary navigation item "Contributing".
  - Move this content deeper under "Contributing" and rename it to "Documentation".
  - Create a new section under "Contributing" called "Contributing to Plone".
- [Developing for Plone Core](https://5.docs.plone.org/develop/coredev/docs/index.html) with its source at https://github.com/plone/buildout.coredev/tree/6.0/docs. See https://github.com/plone/buildout.coredev/issues/840
- [Contributing to plone.api](https://6.docs.plone.org/plone.api/contribute/index.html)
- [Contributing to plone.restapi](https://6.docs.plone.org/plone.restapi/docs/source/contributing.html)
- [Volto](https://github.com/plone/volto/issues/3574)

There should be a generalized authoritative contributing document in `plone/documentation`, one that includes the items that every repo should follow. I would suggest the following:

- Include signing the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement) as the first step.
- General steps to propose a change (file an issue or post to the Community Forum, clone, branch, edit, run tests, commit, push, submit PR, request review from core contributors)
- Mention CI/CD requirements (GitHub Workflows, Jenkins)
- Mention that each project has its own details for contributing, and should be reviewed next, with a list of links to the core packages' contributing docs.

## To Dos
- [x] https://github.com/plone/documentation/pull/1478
- [x] https://github.com/plone/volto/pull/4634
- [x] Revise [Contributing to `plone.api`](https://6.docs.plone.org/plone.api/contribute/index.html). See https://github.com/plone/plone.api/pull/539.
- [x] Revise [Contributing to `plone.restapi`](https://6.docs.plone.org/plone.restapi/docs/source/contributing.html)
- [x] Migrate and revise [content from coredev](https://github.com/plone/buildout.coredev/tree/6.0/docs). Refs: https://github.com/plone/buildout.coredev/issues/840
- [x] Review branch https://github.com/plone/documentation/tree/contributing to determine what should and should not get migrated. There is a lot of irrelevant and outdated stuff

**Comment by JatinPandey26** [comment]
Can i work on it ?

**Comment by stevepiercy** [comment]
This is an advanced issue for people who have experience with contributing to Plone.

**Comment by stevepiercy** [comment]
I just got this from the Read The Docs newsletter. Here is a brilliant and well-organized guide, [Contributing to Wagtail](https://docs.wagtail.org/en/stable/contributing/index.html#), a Django-based CMS. Very relevant to what we want to do.

**Comment by fredvd** [comment]
Here's another very good Idea I got from a talk held 2 weeks ago at FOSS-backstage 2023.   A jenkins maintainer gave a talk with a lot of do's/works/didnt'work from a creating and maintaining a public road map. I really like this overview:

https://www.jenkins.io/participate/

(presentation here:  https://www.youtube.com/watch?v=yVO2-uZbeQU)

**Comment by stevepiercy** [comment]
Closing as completed. There's a couple of open PRs that will close this anyway.
