### ISSUE TITLE
UI not properly aligned for tablet size.

### ISSUE THREAD

**Issue by JatinPandey26** [plone/documentation#1279]
### Plone Documentation versions affected

- [ ] 5.x
- [ ] 6.x

### Description

I was looking into documentation of plone , then i realised UI  is not properly handled for multiple screen sizes (majorly tablets).
![Capture](https://user-images.githubusercontent.com/62138518/185980256-da117bab-5e20-4737-afa7-f949dbff073e.PNG)

**Comment by JatinPandey26** [comment]
If no one is working on it currently , then i would love to work on it  . @sneridagh

**Comment by stevepiercy** [comment]
@JatinPandey26 wrong repo. Please ask in the Community Form for guidance.

https://community.plone.org/
