### ISSUE TITLE
Document minimum browser support

### ISSUE THREAD

**Issue by esteele** [plone/documentation#1280]
We need a listing of which browsers Plone 5 will support.

See also plone/Products.CMFPlone#1032

**Comment by vangheem** [comment]
See my comment: https://github.com/plone/Products.CMFPlone/issues/1032#issuecomment-141694074

I think we need to support IE9+

**Comment by polyester** [comment]
+1

Individual sites can of course up the ante in their own themes, but OOTB it should be IE9+

**Comment by sneridagh** [comment]
+1 Yeah, I think we agree IE9+ some while ago. At least @albertcasado and I worked with that premise.

**Comment by davisagli** [comment]
The discussion here is way out of date, but I searched for Plone browser support and couldn't find a valid current reference. @mauritsvanrees Do we have any effective current guideline for what browsers are supported?

**Comment by mauritsvanrees** [comment]
No idea.
@agitator @santonelli Do you know which browsers are supported in Plone 6.0?

**Comment by santonelli** [comment]
Since we rely on Bootstrap for Classic UI I'd refer to [Bootstrap's Documentation](https://getbootstrap.com/docs/5.2/getting-started/browsers-devices/#supported-browsers)

**Comment by stevepiercy** [comment]
Next question, where should it go in the docs? Possible locations:

- https://6.dev-docs.plone.org/install/source.html#system-requirements
- https://6.dev-docs.plone.org/classic-ui/theming/barceloneta.html

I also assume that this applies only to Classic UI, and not Volto, and if so, then we must make that distinction when documenting it.

**Comment by davisagli** [comment]
@stevepiercy System requirements could work. It might also make sense to have a new page about compatibility which could also talk about Python versions? I wouldn't put it with theming because it also has to do with frontend javascript.

Volto is mainly tested on Chrome, but uses build tools that aim to provide compatibility with the last 4 versions of the major browsers: https://github.com/plone/volto/blob/1aff8d0451f5cb375ca9f5afe9b2b72a0555afd8/packages/volto/package.json#L170-L176

**Comment by stevepiercy** [comment]
Here are the two configs from those links from @santonelli and @davisagli:

## Bootstrap

```
>= 0.5%
last 2 major versions
not dead
Chrome >= 60
Firefox >= 60
Firefox ESR
iOS >= 12
Safari >= 12
not Explorer <= 11
```

## Volto

```
  "browserslist": [
    ">1%",
    "last 4 versions",
    "Firefox ESR",
    "not ie 11",
    "not dead"
  ],
```

Syntax, usage, and guidance for reference: https://github.com/browserslist/browserslist#readme

I am not sure about the difference between `versions` and  `major versions`, and the reference does not make a distinction. I assume `versions` includes any major (vX), minor (vX.Y), or patch (vX.Y.Z) release, whereas `major versions` is only major release. Assuming that is correct, then I am not sure which is more restrictive.

To help inform us as to where the documentation of the browser support should be placed in the docs, should we have a single `browserslist` configuration for all of Plone, or two separate configurations, one for Volto and another for Classic UI?
