### ISSUE TITLE
Reorganize Backend navigation items

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1299]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

We need to reorganize the items in https://6.dev-docs.plone.org/backend/index.html sorted alphabetically when rendered, not by filenames.

**Comment by ArslanYM** [comment]
@stevepiercy Can I work on this issue?

**Comment by stevepiercy** [comment]
@ArslanYM you do not need to ask to work on any project under the Plone organization. Just start working. That is the nature of open source software.

To avoid potentially duplicating work, check to see if anyone has been assigned to the issue, or has done work on it under Pull Requests.

Finally see how to contribute:
https://6.docs.plone.org/contributing/index.html
