### ISSUE TITLE
Reorganize Classic UI navigation items

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1300]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

We need to reorganize the items in https://6.docs.plone.org/classic-ui/index.html sorted alphabetically when rendered, not by filenames.

**Comment by sitanshu05** [comment]
Can I work on this issue? Where can i access the code?

**Comment by stevepiercy** [comment]
@sitanshu05 yes! Please assign yourself to this issue. Then read https://6.dev-docs.plone.org/contributing/index.html for instructions for how to contribute to Documentation. Thank you!

**Comment by Prath-11** [comment]
Hi is this issue still open? Can you assign it to me.

**Comment by stevepiercy** [comment]
@Prath-11 Yes. No.

Please see Volto and general contributing guidelines.

- https://6.docs.plone.org/volto/developer-guidelines/contributing.html
- https://6.docs.plone.org/contributing/index.html#making-contributions-on-github

**Comment by stevepiercy** [comment]
Closing as completed.
