### ISSUE TITLE
Backend > Widgets needs content

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1307]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

Backend > Widgets needs content.

Source material:

- https://github.com/plone/training/blob/main/docs/mastering-plone/dexterity_reference.md
- https://github.com/plone/plone.app.dexterity/blob/master/docs/reference/widgets.rst

**Comment by rber474** [comment]
@stevepiercy
I looking forward to collaborate with documentation, but I have several doubts:

Regarding the source material links, I have no experience at all with Volto but in the first link there are many references and examples for frontend widgets. Should widgets section include them?
I also have doubts about the scope of the section, what about all docs in http://plone-documentation.s3-website-us-east-1.amazonaws.com/latest/en/develop/plone/forms/z3c.form.html#id25 ?
Shouldn't this section include these examples and chapters (Widgets) or is it intended to place it into forms section?

**Comment by stevepiercy** [comment]
@rber474 http://plone-documentation.s3-website-us-east-1.amazonaws.com/latest/en/develop/plone/forms/z3c.form.html#id25 is not official documentation. May I ask how you found it? Do you know who hosts it? The official Plone 5 documentation for that page is here: https://5.docs.plone.org/develop/plone/forms/z3c.form.html

That aside, there are two frontends in Plone 6: Classic UI and Volto. This issue is about documenting Classic UI Widgets.

Classic UI has a placeholder at [Forms](https://6.docs.plone.org/classic-ui/forms.html#), which in turn will reference [Fields](https://6.docs.plone.org/backend/fields.html), [Widgets](https://6.docs.plone.org/backend/widgets.html), and [Vocabularies](https://6.docs.plone.org/backend/vocabularies.html).

Volto has a user manual under development at [User Manual](https://6.docs.plone.org/volto/user-manual/index.html), but other people are working on that.

I hope that explains better what we are trying to do.

**Comment by rber474** [comment]
@stevepiercy just a quick google search "Plone widgets", I was trying to get all the sources I could before start to typing.

Edited: No, I don't know who hosts it.

**Comment by stevepiercy** [comment]
@rber474 OK, thanks. I put the AI team on it, in case the Plone Foundation is paying for something that they don't know exists.

**Comment by davisagli** [comment]
I took a look, the plone-documentation S3 bucket is owned by the Plone AI team. I switched its permissions to block public access since it is out of date.
