### ISSUE TITLE
`html_static_path` does not support globbing syntax

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1312]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

While running `make clean livehtml` or `make clean html`, I noticed that `html_static_path` does not support globbing (`*`) syntax. One must use `clean` to notice.

We have this:

https://github.com/plone/documentation/blob/ad20b4bf89836c6353258a11291b8b491c36db71/docs/conf.py#L130-L134

Which generates warnings:

```console
WARNING: html_static_path entry 'volto/_static/*png' does not exist
WARNING: html_static_path entry 'volto/_static/*jpg' does not exist
```

I think the best option is to place images that we want to copy over into a subdirectory in `volto/docs/source/_static/volto/img/` (there are only two at the moment), then change `html_static_path`:

```python
html_static_path = [
    "_static",
    "volto/_static/volto/img",
]
```

This naming convention with the repo name could be replicated as needed to other submodule repos.

We would also need to update the image paths in the Volto docs.

**Comment by ksuess** [comment]
Good plan.

**Comment by stevepiercy** [comment]
I forgot to mention, we earlier discovered that this:

```python
html_static_path = [ 
     "_static", 
     "volto/_static", 
 ] 
```

...caused everything to be copied over from `volto/_static`, including overwriting the `custom.css` in `plone/documentation`. We don't want that again.

**Comment by stevepiercy** [comment]
Closing as obsolete.
