### ISSUE TITLE
Installation from packages: All-In-One-Installer

### ISSUE THREAD

**Issue by ksuess** [plone/documentation#1317]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

I wrote down the instructions on how to install Plone 6 backend with pip instead of buildout. The guide on how to enfold the skeleton for the backend, a skeleton that allows to pin Plone package versions, checking out Plone packages, etc. https://6.dev-docs.plone.org/install/source-step-by-step.html uses **mxdev**.

It would be great to have **one recommended “installer” for both backend and frontend** which allows these customizations.

I expect that this cookiecutter https://github.com/collective/cookiecutter-plone-starter will be the recommended installation tool/method for an installation from package.
Is it planned to integrate mxdev for pinning versions of Plone packages, checking out Plone packages, etc.?
If not, how to pin Plone package versions, checking out Plone packages, etc.?

So, how to move forward? It would be awesome to have a recommended way on how to install Plone 6 from packages described in https://6.dev-docs.plone.org/install/source.html where I already wrote down common tasks like 
- Add an add-on
- Pin the version of an add-on
- Checkout an add-on
- Pin the version of a Plone package / constraints
- Checkout a Plone package
- Build and start your instance

**Comment by ksuess** [comment]
@plone/installers  What is planned? Is there already something to update in documentation? 
TODO: https://6.dev-docs.plone.org/install/source.html#installation-jump-in-and-enfold-the-beauty
Can I help with mxdev?

**Comment by ksuess** [comment]
[This](https://github.com/collective/cookiecutter-plone-starter/issues/4) would amend the all-in-one candidate for installation (backend and frontend) _cookiecutter-plone-starter_ with the ability to override Plone core versions and add Plone core development packages. And of course add-ons.

/cc @jensens @ericof @stevepiercy

**Comment by stevepiercy** [comment]
I think we can close this issue. Is there anything left unresolved, other than https://github.com/plone/documentation/issues/1326?

**Comment by stevepiercy** [comment]
@ksuess closing in favor of #1326. Feel free to reopen and update, or create a new issue.
