### ISSUE TITLE
Add content for Overview part

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1352]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

We have a [skeleton framework for Overview](https://6.dev-docs.plone.org/overview/index.html), but no content.

See also https://github.com/plone/documentation/issues/1281

**Comment by Manan17** [comment]
Can I work on this?

**Comment by stevepiercy** [comment]
This issue requires the contributor to have deep familiarity with Plone architecture.

**Comment by stevepiercy** [comment]
Closing as completed at some point. https://6.docs.plone.org/overview/index.html
