### ISSUE TITLE
Need documentation age of files?

### ISSUE THREAD

**Issue by gforcada** [plone/documentation#1362]
### Plone Documentation versions affected

- [X] 5.x
- [X] 6.x

### Description

Long time ago, the documentation team wanted to have way to see the age of files on this repository (i.e. the last time a file had been updated).

For that [this jenkins job](https://jenkins.plone.org/view/QA/job/qa-docs-age/) was created and still is running nowadays on branch 5.2.

You can see [the output](https://jenkins.plone.org/view/QA/job/qa-docs-age/lastSuccessfulBuild/artifact/report.txt/*view*/).

The question is two fold?

- is that still needed?
- and if _yes_, would that be also needed for the `6.0` branch? 😄 

If _no_, then I would be removing it. There is no point on keeping a job running that is not being used 👍🏾 🍏

**Comment by stevepiercy** [comment]
Thanks for reporting. I never knew about this job, and I cannot imagine why it is useful. This job is redundant to using `git log`, your editor's git UI, or the GitHub UI, with a lot less information. I would say purge it, unless @polyester, @ksuess, or @spereverde can come up with an historic reason to keep it around.

**Comment by spereverde** [comment]
I agree,  by now I think most developers use git for this.
+1 for not keeping that job

I guess the code for the jenkins job is versioned so we can reuse it if it
should be needed again

**Comment by gforcada** [comment]
I think the idea at that time , was to know which files we're more outdated and fet a warning about them. I will remove it 👍🏾
