### ISSUE TITLE
Put new documentation live

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/documentation#1363]
### Plone Documentation versions affected

- [x] 5.x
- [X] 6.x

### Description

Apologies if this is already captured in other issues, but I did not find the right one. Feel free to close this, or hack it up into other issues, whatever you see fit.

Current expected release date for Plone 6 final, according to the plan formulated in the Plone 6 coordination meeting today, is Monday December 12, 2022. On the Release Plone 6 docs [project board](https://github.com/orgs/plone/projects/12/views/4) an awesome 239 tasks are marked as done. Great work! There are 10 items in progress and 72 todo. We won't finish all these before December 12. And if we wait till all are finished (or rather: work hard on finishing them) we will be far into 2023, which is not an option.

So on this Thanksgiving Day let's give thanks to all contributors, especially @stevepiercy and @ksuess for all the hard work done. Let's use the remaining time to finish up what we have. It's show time!

I can see the following technical tasks needed for putting it live:

- [ ] When we release Plone 6 final, https://docs.plone.org should show the Plone 6 documentation. The switch should be done either on the same day, or in the week before.
- [ ] The Plone 5 docs should remain available under a different link.
- [ ] There should be an easy way to switch from the Plone 6 docs to the Plone 5 docs. The homepage of https://6.dev-docs.plone.org already has such a link, so that seems fine. It just needs to be a different url once we have made the switch.
- [ ] There should be an easy way to switch from the Plone 5 docs to the Plone 6 docs. Maybe do the same: simply add a link on the homepage. Or is there a different plan?

Is anything else along these lines needed?

How about content? Anything that you feel must really be tackled before the release, maybe consider it a blocker?

**Comment by stevepiercy** [comment]
I updated items in https://github.com/plone/documentation/issues/1140. I'm closing this issue in favor of the other.

The most critical issues are the ones where there is no content.

- https://github.com/orgs/plone/projects/12/views/4?filterQuery=content
- https://github.com/orgs/plone/projects/12/views/4?filterQuery=migrate
