### ISSUE TITLE
Links to Plone demos need to be updated

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1376]
Update links to demo sites. One place, probably a few others:

https://6.docs.plone.org/install/index.html

Note that the Plone 5 demo is temporarily non-existent.

**Comment by stevepiercy** [comment]
From Discord:

- https://52.demo.plone.org/ is up. It is the lastest stable 5.2 release (5.2.10)
- https://6.demo.plone.org/ is Volto
- https://classic.demo.plone.org/ is Plone 6 Classic UI

**Comment by davisagli** [comment]
I searched the built docs and only found links to the demo site here and in the plone.restapi readme. Submitted PRs.

**Comment by stevepiercy** [comment]
Submodules updated, and we have docs with shiny new demo links.
