### ISSUE TITLE
Redirect api.plone.org to Plone 6 Documentation

### ISSUE THREAD

**Issue by erral** [plone/documentation#1383]
### Plone Documentation versions affected

- [x] 5.x
- [x] 6.x

### Description

https://api.plone.org redirects now to https://docs.plone.org/develop/plone.api/docs/index.html

I think it should redirect to the current version at https://6.docs.plone.org/plone.api/

**Comment by polyester** [comment]
I had already put that in place, but there was some weird redirect going on in Cloudflare DNS. Will probably take a bit to flush out the cache, but should be fixed soon. Keeping this open until it resolves proper.

**Comment by stevepiercy** [comment]
7 hours later, and it still hasn't cleared cache, else something else is going on. Which response header is the one that reports on cache, assuming that is what it does?

```
cache-control: max-age=3600
cf-ray: 77aad4b16ee3efb0-PDX
date: Fri, 16 Dec 2022 22:24:43 GMT
expires: Fri, 16 Dec 2022 23:24:43 GMT
location: https://docs.plone.org/develop/plone.api/docs/index.html
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=BFZj3RB9dXzhgOgPKnygVHJn8RJpl5kgkKwrJyP4XbfiG7%2BlCczfxFnVnz8D0fwEimnNFvlktg5YXuGlmVCNetWbNDSa8SavABA0m%2B8XzMbuuccf1qu7B8Fjm8vAQgU%3D"}],"group":"cf-nel","max_age":604800}
server: cloudflare
vary: Accept-Encoding
```

**Comment by polyester** [comment]
so, there are several creative places where the utterly useless cloudflare webinterface can hide things. Found it.
