### ISSUE TITLE
Deprecation notices from lack of `pyproject.toml` and `wheel`

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1395]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

We have a couple of deprecation notices that appear on CI.

> DEPRECATION: livereload is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
> 
> DEPRECATION: sphinx-sitemap is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

We could add pins for `setuptools` and `wheel` to our `requirements.txt`, and add a `pyproject.toml` file. I don't know what we would put in it, though.

Anyone have any opinions? @plone/documentation-team

**Comment by mauritsvanrees** [comment]
That sounds like these two projects have no `pyproject.toml`, which is something we cannot do anything about, except perhaps file an issue.

The `wheel` package is not installed. I usually install it. Plone has it in its [`requirements.txt`](https://dist.plone.org/release/6.0.0/requirements.txt).

But even if we install `wheel`, it will find no wheels for these two packages: their latest version only has a source distribution. So in the end it would call `python setup.py install` anyway.

 I guess the problem then is that pip would very much like to avoid calling `setup.py install`. I would need to reread the linked issue and related documentation a few more times to understand the big picture, and also see where the `pep517` and `build` packages come into this.

Summary seems to be: only the authors of those two packages can do anything about this, mostly be uploading wheels to PyPI.

**Comment by stevepiercy** [comment]
Refs:
- https://github.com/lepture/python-livereload/issues/240
- https://github.com/jdillard/sphinx-sitemap/pull/39

**Comment by stevepiercy** [comment]
A maintainer of livereload uploaded a wheel. I'm going to add `wheel` to our requirements.

That leaves sphinx-sitemap as the remaining todo.

**Comment by stevepiercy** [comment]
And the maintainer of sphinx-sitemap released a wheel to PyPI.

**Comment by stevepiercy** [comment]
I'm closing this issue, as it was an upstream matter. Because we don't release documentation as a package to PyPI, we don't really need a `pyproject.toml`, although we might want to add one in the future.
