### ISSUE TITLE
Custom 404 not found page with navigation, search, etc for new 6.docs.plone.org

### ISSUE THREAD

**Issue by ksuess** [plone/documentation#1399]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

- Minimum solution: page with navigation, search, etc
- Luxus version: link to requested url replaced by domain (docs.plone.org -> 5.docs.plone.org) with a "maybe you are looking for a Plone 5 documentaion page you bookmarked"
  Example: 
https://docs.plone.org/develop/testing/unit_testing.html
->
https://5.docs.plone.org/develop/testing/unit_testing.html
- [obsolete with version switcher] Optional: Mention Plone 5 documentation with root url 5.docs.plone.org

**Comment by ksuess** [comment]
Minimum solution:
![grafik](https://user-images.githubusercontent.com/1144737/209063330-e2534843-a34c-48b9-a2be-110cf47e7a71.png)

**Comment by ksuess** [comment]
Current solution:
![grafik](https://user-images.githubusercontent.com/1144737/209063538-a215adb8-6dff-4454-978a-98704fa6bf1d.png)

**Comment by stevepiercy** [comment]
The minimal is good for now. I would like to revisit the luxury model in a future PR.

**Comment by Vic-Orlands** [comment]
@stevepiercy @ksuess  I would like to work on this issue. A more detailed Error page with illustrations will be better suited for this.

**Comment by stevepiercy** [comment]
@Vic-Orlands what do you propose? What illustrations?

The minimal version currently exists, and was added in https://github.com/plone/documentation/pull/1400

Example: https://6.docs.plone.org/notfound

However since then, plone.org has a new design that we must follow.

https://plone.org/notfound

**Comment by Smit1324** [comment]
@ksuess I would love to work in this issue as I can solve it acc to my expertise. So, kindly assign me this issue to fix

**Comment by ksuess** [comment]
@Smit1324 The minimal version currently exists, and was added in https://github.com/plone/documentation/pull/1400
The web server configuration needs a fix to point the user to the existing https://6.docs.plone.org/404.html That's a job for someone with permission to configure the web server.

**Comment by ksuess** [comment]
@stevepiercy or @polyester, would you please be so kind and add a 404 rule to the web server configuration. We have a custom 404 page: 
https://6.docs.plone.org/404.html
Thanks!

**Comment by stevepiercy** [comment]
I lack that super power. It needs to be done by @polyester, @fredvd, @ericof, or someone else with sufficient access in the @plone/ai-team.

**Comment by Smit1324** [comment]
> @Smit1324 The minimal version currently exists, and was added in #1400 The web server configuration needs a fix to point the user to the existing https://6.docs.plone.org/404.html That's a job for someone with permission to configure the web server.

So can I do it ??

**Comment by Smit1324** [comment]
> I lack that super power. It needs to be done by @polyester, @fredvd, @ericof, or someone else with sufficient access in the @plone/ai-team.

May I ??

**Comment by polyester** [comment]
fixed. Sorry, @Smit1324 , this is a sysadmin issue, that requires actual SSH access to our servers, so not up for grabs to people not in the sysadmin team.
