### ISSUE TITLE
coordinate PLIP process with documenting the PLIP's

### ISSUE THREAD

**Issue by svx** [plone/documentation#14]
- describe plip and add docs to this

**Comment by tkimnguyen** [comment]
Hi @svx is this issue about updating http://docs.plone.org/develop/plone-coredev/plips.html etc.?

**Comment by svx** [comment]
@tkimnguyen partly yes, but in the first case it is more about making sure that a plip has proper documentation **before** the plip gets merged.

This of course can be differ a lot, depending on the plip.

The idea is/was to 'assign a docs buddy' to the developer, we sadly still forgetting quite often to document.

**Comment by tkimnguyen** [comment]
The big issue I noticed is that the docs still refer to the old dev.plone.org for PLIPping; I was looking it up to see how to create a PLIP.

**Comment by svx** [comment]
Well this has to be fixed in the docs of buildout.coredev [https://github.com/plone/buildout.coredev], once it is fixed there we will pull it into the docs.

**Comment by stevepiercy** [comment]
Superseded by https://github.com/plone/buildout.coredev/issues/840 and https://github.com/plone/documentation/issues/1278
