### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by gforcada** [plone/documentation#1412]
### Plone Documentation versions affected

- [X] 5.x
- [X] 6.x

### Description

Hi @stevepiercy (and all @plone/documentation-team 😄 ) 👋🏾 

I noticed these repositories in the collective organization:

- https://github.com/collective/collective.chinesedocumentation
- https://github.com/collective/collective.spanishdocumentation

And though my idea is on the cleaning side (deleting forks on collective org that do not make sense), for this one I would like your input.

I guess that documentation is totally outdated (last commit being on 2012), but brings up the question of how to handle translations in the _current_ one (so, here in this repo).

Some food for thought for this new year 🥳 😃

**Comment by stevepiercy** [comment]
Based on the progress made in 2022 on Plone 6 Documentation, I do not foresee its completion for at least another two years. Until more resources are dedicated to Plone 6 Documentation, that estimate will not change.

Third party translation services, such as [Deepl](https://www.deepl.com/translator) and [Google Translate](https://translate.google.com/), are good enough.

As such, it would be impractical for the Plone organization to put effort into translating the docs. Of course, anyone is welcome to translate them under the collective organization as an unsupported version. If that happens, then we can revisit whether to make a translation official.

Closing as "won't fix".
