### ISSUE TITLE
Glossary needs cleanup

### ISSUE THREAD

**Issue by jensens** [plone/documentation#1415]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

In the glossary there are some terms like.

```
Hydration (SSR)
    After loading an HTML page generated with SSR in the browser, React can "populate" the existing DOM elements, recreate and attach their coresponding components.

```

Someone looking by alphabet for SSR won't not find it.
It would be better to define it as two terms:

```
SSR
Hydration
    After loading an HTML page generated with SSR in the browser, React can "populate" the existing DOM elements, recreate and attach their coresponding components.
```

**Comment by stevepiercy** [comment]
SSR != Hydration. They should be two separate Glossary entries, and wherever:

```
{term}`Hydration (SSR)`
```

appears, it should be changed to:

```
{term}`Hydration`
```

Also this term:

```
Server-Side Rendering (SSR)
```

Should be:

```
SSR
Server-Side Rendering
```

You can "stack" terms and define them.

**Comment by stevepiercy** [comment]
Similarly:

```
Single Page Application (SPA)
```

Should be:

```
SPA
Single Page Application
```

and

```
Hot Module Replacement (HMR)
```

should be:

```
HMR
Hot Module Replacement
```


and

```
middleware (Redux)
```

s/b

```
middleware
```


and

```
hooks (React)
```

s/b

```
hooks
```


and

```
hoisting (Yarn)
```

s/b

```
hoisting
```

We also need to check whether any `term` includes the parenthetical elsewhere in the docs, specifically in Volto.

**Comment by stevepiercy** [comment]
PRs are ready:

- https://github.com/plone/documentation/pull/1416
- https://github.com/plone/volto/pull/4211

**Comment by stevepiercy** [comment]
Completed and updated submodule.
