### ISSUE TITLE
Issue on page /volto/getting-started/install.html

### ISSUE THREAD

**Issue by bsuttor** [plone/documentation#1422]
Hello,
I tried to install a fresh new volto project as explain in https://6.dev-docs.plone.org/volto/getting-started/install.html
but it seems I have to make a `yarn install` before a `yarn start` command
Otherwise, there is this error :

```
Internal Error: frontend-oality@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
```

**Comment by stevepiercy** [comment]
Did you heed the warning at the top of the page?

> This chapter of the documentation has been superseded by the official Plone 6 Documentation chapter [Install](https://6.docs.plone.org/install/index.html#install-index-label). This chapter contains some legacy information that may be useful to Plone 5.2 development.

Also the new URL for Plone 6 docs does not have `dev-` in the host name. Can you let me know where you found that URL so I can update it?

**Comment by bsuttor** [comment]
Indeed I miss the warning
I found docs link from https://github.com/plone/volto-documentation/blob/master/README.md
And I click on https://docs.voltocms.com/

**Comment by stevepiercy** [comment]
> Indeed I miss the warning I found docs link from https://github.com/plone/volto-documentation/blob/master/README.md And I click on https://docs.voltocms.com/

@plone/ai-team or maybe @polyester can someone delete the obsolete repo https://github.com/plone/volto-documentation, not just archive it? It still causes confusion. I do not have permission.

**Comment by polyester** [comment]
@stevepiercy ... aaaaaand it's gone

**Comment by stevepiercy** [comment]
@polyester thank you! Also @bsuttor thank you for the report.
