### ISSUE TITLE
Backend > Traversing needs content

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1425]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

https://6.docs.plone.org/backend/traversing.html chapter needs content. It will appear when https://github.com/plone/documentation/pull/1291 is merged.

### Source material

- https://5.docs.plone.org/develop/plone/serving/traversing.html
- https://5.docs.plone.org/develop/plone/views/layers.html
- https://github.com/plone/documentation/issues/355
- https://github.com/plone/bobtemplates.plone/issues/89#issuecomment-138474557

**Comment by jensens** [comment]
done in #1429
