### ISSUE TITLE
Failing test due to failing include of `CHANGELOG.md` in release notes of Volto

### ISSUE THREAD

**Issue by ksuess** [plone/documentation#1431]
This can be safely ignored. Volto docs pulls in `CHANGELOG.md` from its repo, and Docs pulls in Volto docs. Thus `CHANGELOG.md` has two different relative paths, depending on the context of whether you build docs in Documentation or Volto. See https://github.com/plone/volto/pull/3994/files#diff-8ea15a25d044c7930c6e3f0f521299f7b93d2d8196a08ac0e1c4898f73869d5fR12-R22

However, if this becomes annoying, I can make the `CHANGELOG.md` not get included in Volto's local build, and only included in Documentation's build. That might be a more sane approach. @ksuess you hit this, too. Thoughts?

_Originally posted by @stevepiercy in https://github.com/plone/documentation/issues/1405#issuecomment-1381693333_

**Comment by ksuess** [comment]
Sounds like a plan!

(Unfortunatly I have no alternative idea to 'ifconfig' to include a file conditionally.)

**Comment by stevepiercy** [comment]
I've got a fix for this in https://github.com/plone/volto/pull/4404

The downside is that now there will be many warnings when building the docs within the Volto repo. These can be safely ignored.

`/Users/stevepiercy/projects/Plone/documentation/submodules/volto/docs/source/index.md:38: WARNING: toctree contains reference to document 'release-notes/index' that doesn't have a title: no link will be generated`

**Comment by ksuess** [comment]
@stevepiercy  As it is obviously difficult to include files from submodules: How about letting a Volto release generate an additional CHANGELOG to its /docs? No more complicated inclusions and if/then.

Failing PRs:
https://github.com/plone/documentation/pull/1451
https://github.com/plone/documentation/pull/1449

**Comment by stevepiercy** [comment]
If I understand:

- `/CHANGELOG.md`
- `/docs/CHANGELOG.md`

Would have the same content, correct? If so, yes, that's a great idea!

A couple of things to add to it:

- `/CHANGELOG.md`: I would update the comments:

  https://raw.githubusercontent.com/plone/volto/master/CHANGELOG.md

```
<!-- DO NOT EDIT THIS FILE.
     It is generated automatically by towncrier.
     Instead create a file in the directory "news".
     For instructions, see:
     https://6.docs.plone.org/volto/developer-guidelines/contributing.html#create-a-pull-request
-->
```

- `/docs/CHANGELOG.md` should include an additional note.

```
<!-- DO NOT EDIT THIS FILE.
     It is generated automatically by towncrier.
     Instead create a file in the directory "news".
     For instructions, see:
     https://6.docs.plone.org/volto/developer-guidelines/contributing.html#create-a-pull-request
     Also this file is a duplicate of the one at the root of the repository.
     It is used only to build the documentation without Sphinx warnings.
-->
```

I am not sure exactly whether it is safe to edit those comments directly in the file, but I think it is OK. We should check with other people to make sure.

**Comment by ksuess** [comment]
Oh my. @stevepiercy please stop investing more time on this. The mentioned PRs are green with the update of the submodule tips.

Please, if you fix something, and this CHANGELOG drama fix was a good fix, then do the submodule tip dance.
 ;-)

**Comment by stevepiercy** [comment]
@ksuess what? I thought you were proposing a fix for this? I don't understand what you are talking about "submodule tip dance" has to do with your proposal.

**Comment by ksuess** [comment]
> @ksuess what? I thought you were proposing a fix for this? I don't understand what you are talking about "submodule tip dance" has to do with your proposal.

Since I updated the submodule tips yesterday, the fix https://github.com/plone/volto/pull/4404 you mentioned above fixes the problem.
```
 /home/runner/work/documentation/documentation/docs/volto/release-notes/index.md:16: CRITICAL: Directive "include": error reading file: /home/runner/work/documentation/documentation/CHANGELOG.md
[Errno 2] No such file or directory: '/home/runner/work/documentation/documentation/CHANGELOG.md'.
```
But this fix was not applied before, so I was thinking about a solution. As the fix is now applied, it is not necessary to invest time to find another solution. That's all.

**Comment by stevepiercy** [comment]
Actually that "fix" just moved warnings from Documentation to Volto. It fixed one bug, and introduced another. That's why I like your idea of a second CONTRIBUTING.md in `docs/` to fix it in Volto. Does that make sense?
