### ISSUE TITLE
Add and link glossary terms UID and intid

### ISSUE THREAD

**Issue by jensens** [plone/documentation#1460]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

The terms UID and intid are used at several places. In my opinion it would be good to add them as glossary terms and  link to the glossary everywhere used.

**Comment by stevepiercy** [comment]
In general, we need to refer to the definition of a term in the glossary only once per page, where it first appears, not everywhere.

**Comment by varun-p18** [comment]
hi, I want to work on this issue, can you please assign me this issue?

**Comment by stevepiercy** [comment]
@varun-p18 please see https://6.docs.plone.org/contributing/index.html#making-contributions-on-github, especially item 2. Thank you!

**Comment by anishbasnetAB** [comment]
hello, I want to work on this issue , can you please assign me ?

**Comment by stevepiercy** [comment]
@anishbasnetAB no. See my previous comment. It is always a good idea to read the issue comments and linked references before making a comment.
