### ISSUE TITLE
Specify supported and unsupported OSes and alternatives for Windows users

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1468]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

Now that we use `make` everywhere, effectively Windows is no longer supported for Plone 6. We should specify that in system requirements under Install:

- https://6.docs.plone.org/install/containers/index.html#install-containers-index-system-requirements-label
- https://6.docs.plone.org/install/install-from-packages.html#install-packages-system-requirements-label

This sentence is a lie:

> Almost any modern operating system, including Linux, macOS, and **Windows**, but a UNIX-based operating system is recommended.

@tiberiuichim @sneridagh @jensens @mauritsvanrees @davisagli I could use your feedback and historical knowledge before I start making any changes.

Refs:
- https://github.com/plone/volto/issues/4564
- https://github.com/plone/documentation/issues/1276

**Comment by jensens** [comment]
Well, you can run Plone on Windows using pip/npm only, we just do not cover it in our docs. Yes, this is more work and not as easy as with make, but it is not rocket science. Another option is to run Docker on Windows.

**Comment by stevepiercy** [comment]
The question is whether we *should* cover Windows installation in our docs. Keep in mind we have two sets of Install docs: one each for containers and from packages. The latter requires `make`.

The way the install docs are now, we say it is OK to use Windows for either install method, but in reality from packages requires `make`, so you're screwed and have to post to the Community Forum for help, and then we say "Just use WSL or Linux". That is not a good first impression.

I would rather say, "Although you may run Plone on Windows, no one has bothered to write the documentation for how to do so. We welcome contributions from Windows users. Otherwise just use WSL or Linux in a VM."

**Comment by stevepiercy** [comment]
I mean, just look at this, in the last 24 hours.

- https://community.plone.org/t/master-plone-6-training-on-windows/16835
- https://community.plone.org/t/gsoc23-intro-and-set-up-issues-with-plone-6-on-windows/16841
- https://community.plone.org/t/installing-volto-from-packages-node-version-question/16858

This is a terrible way to treat newbies.

**Comment by jensens** [comment]
Indeed, this is bad. So pointing to WSL or VM is probably all we can do for now.

**Comment by tiberiuichim** [comment]
@stevepiercy "Volto is supported only on systems that support running `make`, such as Linux, OSX or WSL under Windows".
