### ISSUE TITLE
Version banner warning should float

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1473]
### Plone Documentation versions affected

- [X] 5.x
- [ ] 6.x

### Description

When a user visits an anchor in a page, it often scrolls the warning banner out of view.

Example: https://docs.plone.org/develop/coredev/docs/agreement.html#dealing-with-pull-requests-on-github

This causes visitors to assume that this version 5 is current. To resolve this, I would propose to "sticky" a div at the top that does not scroll out of view.

Alternatively, here is what Pyramid does: https://docs.pylonsproject.org/projects/pyramid/en/1.2-branch/

I tested the following on the row div that contains the warning.

```html
<div class="row" style="
    position: sticky;
    top: 0;
    z-index: 1001;
    position: -webkit-sticky;
">
  <div class="col-sm-12 admonition warning version_warning" style="">
    <p class="first admonition-title">Warning</p>
    <p class="last">
      This is the documentation for Plone 5.x.<br>
      The latest version is
      <a href="https://6.docs.plone.org">Plone 6 documentation</a><br>
      For archive reasons, there are also versions for
      <a href="https://4.docs.plone.org">Plone 4</a> and
      <a href="https://3.docs.plone.org">Plone 3</a>
    </p>
  </div>
</div>
```

## No scroll

![Screen Shot 2023-03-23 at 3 24 36 PM](https://user-images.githubusercontent.com/102112/227378554-26772ee0-0272-489d-9f1c-35daf28b7ca1.png)

## Scroll

![Screen Shot 2023-03-23 at 3 24 43 PM](https://user-images.githubusercontent.com/102112/227378604-5be06e21-bf63-478c-a1a1-02bb5d76249c.png)

@polyester I can make the change, but wanted to check with you how best to approach this, as I am not familiar with the v5.2 theme structure. I would prefer to put the CSS in the correct `*.css` file, too, instead of inline in the HTML.

**Comment by polyester** [comment]
Won't be able to work on this before Monday; the theme is a rather rustic one at https://github.com/plone/sphinxtheme.plone, there's one css file for the 5 version:
https://github.com/plone/sphinxtheme.plone/blob/main/src/sphinxtheme/plone/plone_basic/static/css/ploneorg5.css

**Comment by stevepiercy** [comment]
@polyester created PRs:

- https://github.com/plone/sphinxtheme.plone/pull/79
- https://github.com/plone/documentation/pull/1474
