### ISSUE TITLE
'make html' outputs wrong build dir to find the generated documentation

### ISSUE THREAD

**Issue by fredvd** [plone/documentation#1477]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

At the end of running `make html` in the documentation repository root, the Makefile prints:

" Build finished. The HTML pages are in ../_build//html. "

But the builded docs are in in  "_build/html"

**Comment by stevepiercy** [comment]
This is an easy fix. Just change:

```
BUILDDIR        = ../_build/
```

to:

```
BUILDDIR        = ../_build
```
