### ISSUE TITLE
Create or reuse a Sphinx theme package for Plone 6 Documentation?

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1491]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

There are at least a dozen packages that use various themes for publishing their documentation. Plone 6 Documentation uses a lightly customized theme of Sphinx Book Theme, which in turn is based on PyData Sphinx Theme, and sharing these modifications across all packages is not maintainable.

To remedy this situation, we should create a new theme named `plone-sphinx-theme`. It would have tests that check functionality, display, and layout, using the similar test suites from the parent themes.

There exists a Sphinx theme repository in the Plone organization already, but it might not be the best fit going forward.

- https://github.com/plone/sphinxtheme.plone

Refs:
- https://github.com/executablebooks/sphinx-book-theme/tree/master/tests
- https://github.com/pydata/pydata-sphinx-theme/tree/main/tests

**Comment by polyester** [comment]
Create a new one. Sphinxtheme.plone has the ones for the 5, 4 and 3 versions of the docs, and is on palliative care by me to keep it running and cludgel in things like version drop-downs to the current version. Having a completely different theme in there in a branch is just a recipe for brain melt

**Comment by stevepiercy** [comment]
See https://github.com/plone/plone-sphinx-theme

**Comment by stevepiercy** [comment]
This is now done. Closing as completed.
