### ISSUE TITLE
PLIP template has a legacy 5 URL

### ISSUE THREAD

**Issue by sneridagh** [plone/documentation#1495]
### Plone Documentation versions affected

- [X] 5.x
- [X] 6.x

### Description

<img width="710" alt="image" src="https://github.com/plone/documentation/assets/486927/7eaac155-8249-4816-b9fe-c515913d895d">

**Comment by stevepiercy** [comment]
@sneridagh I think this issue needs to be move to whatever repo where you noticed this. `plone/documentation` does not have a PLIP issue chooser.

**Comment by davisagli** [comment]
@stevepiercy The template is https://github.com/plone/volto/blob/master/.github/ISSUE_TEMPLATE/PLIP.md, but I'm not sure there is an equivalent page in the Plone 6 docs to link to.

**Comment by stevepiercy** [comment]
There is no page yet, but there is a placeholder issue for it https://github.com/plone/documentation/issues/1486.

I need help from content experts to take docs from buildout.coredev and figure out where they should go in Plone 6 documentation.

For convenience, here's the link to the current document https://5.docs.plone.org/develop/coredev/docs/plips.html
