### ISSUE TITLE
New documentation isn't correctly indexed on google

### ISSUE THREAD

**Issue by cekk** [plone/documentation#1503]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

This happens everytime i search something on Google: i see only results for the 5.2 version and when i click on it, i am redirect to the homepage of the 6.x and i need to repeat the search inside the site.

https://github.com/plone/documentation/assets/1402078/fbe95a5b-f9fe-49e7-a527-f614f69ed9bd

**Comment by stevepiercy** [comment]
@cekk thank you for the report. We are aware of it and have a plan that needs an available server admin to perform the work. See https://github.com/plone/documentation/issues/1496. Closing as duplicate.
