### ISSUE TITLE
"Unversioned" URLs below https://docs.plone.org/ not properly redirected

### ISSUE THREAD

**Issue by tobiasherp** [plone/documentation#1507]
### Plone Documentation versions affected

- [X] 5.x
- [ ] 6.x

### Description

The URL [https://docs.plone.org/manage/deploying/processes.html#process-control-with-supervisor](https://docs.plone.org/manage/deploying/processes.html#process-control-with-supervisor) is not properly redirected;
the Plone 4 version of it, https://docs.plone.org/4/en/manage/deploying/processes.html#process-control-with-supervisor, _is._

I suggest to treat all URLs below https://docs.plone.org/ whose path component doesn't start with `/[345]/en/` the same as if they'd start with `/5/en/` (as this seems to be the most likely case).

**Comment by stevepiercy** [comment]
@tobiasherp thank you for the report. I have bad news and good news.

We will not set up a wholesale redirection of URLs under `docs.plone.org` to `5.docs.plone.org`. See discussions:
- https://github.com/plone/documentation/issues/1496
- https://community.plone.org/t/plone-6-documentation-update-2023-05-12-plone-6-documentation-released/17451
- https://github.com/plone/documentation/issues/1140

We will consider specific paths under `docs.plone.org` for redirection. It might make sense to do this:

`https://docs.plone.org/manage/deploying/foo` ➡️  `https://5.docs.plone.org/manage/deploying/foo`

At the same time, deployment should redirect to the most current deployment docs, so maybe that's not such a good idea. Then again, our Plone 6 deployment docs are in a neglected state, except for Caching: https://6.docs.plone.org/deployment/index.html.

Overall the best way to fix this is to update content in Plone 6 documentation by porting it from Plone 5, and set up a redirect to Plone 6 docs. We need someone to champion that effort. Here are the source files to update: https://github.com/plone/documentation/tree/5.2-myst/5.2-myst/manage

**Comment by Smit1324** [comment]
Hey @stevepiercy @tobiasherp I would love to work on this issue as I have my expertise in it. So, kindly assign me this issue.

**Comment by stevepiercy** [comment]
@Smit1324 please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially Item 1 in [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do).

However, as a newcomer to Plone, I doubt you have sufficient experience with Plone 5.2 and 6.0 required to migrate the deployment documentation. It requires thoughtful curation, not mindless copy-paste, otherwise it would have been done long ago.

**Comment by stevepiercy** [comment]
Closing as issues brought up have been addressed by policy (redirects will be considered on a case-by-case basis) or in other issues.

- https://github.com/plone/documentation/issues/1327
