### ISSUE TITLE
Code samples in dark mode on white

### ISSUE THREAD

**Issue by jensens** [plone/documentation#1514]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

This should be dark as well.
![screenshot_2023-06-29_10:38:23_selection](https://github.com/plone/documentation/assets/157140/101bff9c-3847-4027-96f5-b6e883ade5c1)

**Comment by stevepiercy** [comment]
FWIW, I'm working on a [Plone Sphinx theme package](https://github.com/plone/plone-sphinx-theme) (nothing there yet) that will take the customizations from Training where code samples display well in dark mode. Thus the fix for this issue is to wait for that package to be released.

**Comment by sofiyanpathan** [comment]
hi,can I work on it?

**Comment by stevepiercy** [comment]
@sofiyanpathan no, please see https://github.com/plone/documentation/issues/1514#issuecomment-1612656285

**Comment by Narottamchy** [comment]
> FWIW, I'm working on a [Plone Sphinx theme package](https://github.com/plone/plone-sphinx-theme) (nothing there yet) that will take the customizations from Training where code samples display well in dark mode. Thus the fix for this issue is to wait for that package to be released.

Okok understood

**Comment by stevepiercy** [comment]
Closing as Plone Sphinx Theme has been applied.
