### ISSUE TITLE
Netlify’s built-in asset optimization feature is deprecated and will be at end of service on October 17, 2023.

### ISSUE THREAD

**Issue by ksuess** [plone/documentation#1530]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

Affects both docu and training

https://answers.netlify.com/t/please-read-deprecation-of-post-processing-asset-optimization/96657?_gl=1*9ivoaa*_gcl_au*MTExOTA5MTI0NC4xNjkyMDE3MjAz

![grafik](https://github.com/plone/documentation/assets/1144737/dd01ccbd-8ca7-45f5-849e-77268ad2fb35)

**Comment by stevepiercy** [comment]
Why do we need this for previews?

It is not enabled for training, plone.restapi, and plone.api.

- https://app.netlify.com/sites/plone-training/configuration/deploys#asset-optimization
- https://app.netlify.com/sites/plone-restapi/configuration/deploys#post-processing
- https://app.netlify.com/sites/plone-api/configuration/deploys#asset-optimization

Documentation and Volto have it enabled.

- https://app.netlify.com/sites/volto/configuration/deploys#asset-optimization
- https://app.netlify.com/sites/6-docs-plone-org/configuration/deploys#asset-optimization

I think we should do nothing and let it just go away.

Alternatively we can implement our own asset optimization step in our CI.

**Comment by stevepiercy** [comment]
Closing due to no response. Please reopen if you think we should take action. Thank you for the report!
