### ISSUE TITLE
mention installing Cookiecutter on page /install/install-from-packages.html

### ISSUE THREAD

**Issue by tkimnguyen** [plone/documentation#1533]
The page mentions installing Cookiecutter but only the Python side. 

Missing: installing the executable too: `brew install cookiecutter` on macOS, as per https://cookiecutter.readthedocs.io/en/stable/installation.html#install-cookiecutter

**Comment by stevepiercy** [comment]
Adding methods to install third party software does not fix a problem, but introduces a new one, that of supporting multiple installation methods. The Python method is universal for all OSes. Closing as not planned.

**Comment by tkimnguyen** [comment]
Something like "...and you will have to install Cookiecutter too" is too much?

**Comment by stevepiercy** [comment]
Already covered: https://6.docs.plone.org/install/install-from-packages.html#cookiecutter

**Comment by tkimnguyen** [comment]
I'd missed warnings at the end of the `pip install` output, that several scripts had been installed to `~/Library/Python/3.11/bin`, which isn't on my PATH. The proper fix in my case is to do something like this: `export PATH="~/Library/Python/3.11/bin:$PATH"`
