### ISSUE TITLE
Expand the secondary navbar to two levels

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1543]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

The secondary navbar that shows the in-page table of contents should always display and should be expanded to always display at least two levels.

https://sphinx-book-theme.readthedocs.io/en/latest/sections/sidebar-secondary.html#show-more-levels-of-the-in-page-toc-by-default

```py
html_theme_options = {
  "show_toc_level": 2
}
```

[Demo of feature](https://sphinx-book-theme.readthedocs.io/en/latest/reference/kitchen-sink/really-long.html).

@tiberiuichim @sneridagh

**Comment by ArmanKukreti** [comment]
@stevepiercy I want to contribute to this issue , highlight in a screenshot that you are referring to which secondary navbar.

**Comment by stevepiercy** [comment]
@ArmanKukreti please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html).
