### ISSUE TITLE
Broken link for https://52.demo.plone.org in install/index.md

### ISSUE THREAD

**Issue by rber474** [plone/documentation#1553]
### Plone Documentation versions affected

- [ ] 5.x
- [X] 6.x

### Description

Tests failed because of a broken link to https://52.demo.plone.org in install/index.md

As documentation is for Plone 6, should this link be removed?

```
(   install/index: line   31) broken    https://52.demo.plone.org/en/ - 502 Server Error: Bad Gateway for url: https://52.demo.plone.org/en/
make: *** [Makefile:192: linkcheckbroken] Error 1
Error: Process completed with exit code 2.
```

**Comment by stevepiercy** [comment]
We're awaiting a decision. See also https://community.plone.org/t/5-2-demo-is-down/18059. We can ignore it until a decision is made.

**Comment by ksuess** [comment]
I suggest to remove the option [Plone 5.2.x (stable) with Barceloneta frontend](https://52.demo.plone.org/en/) in installation guide  https://6.docs.plone.org/install/index.html


![grafik](https://github.com/plone/documentation/assets/1144737/c731b609-c725-435e-83f9-03b36d7e3c18)

**Comment by stevepiercy** [comment]
LOL, you read my mind. https://community.plone.org/t/5-2-demo-is-down/18059/3?u=stevepiercy
