### ISSUE TITLE
Misleading information in docs

### ISSUE THREAD

**Issue by hipertracker** [plone/documentation#1576]
The statement "http://plone.localhost/ is the URL you will be using to access the website. " is untrue. This site is not a Plone site. It's only the landing page where Plone sites can be created. Nginx needs Virtual Host Monster path to display a classic Plone site.

**Comment by stevepiercy** [comment]
@hipertracker technically, you are correct. What do you suggest instead? I'd accept a PR.

I don't understand this statement:

>  Nginx needs Virtual Host Monster path to display a classic Plone site.

The note continues on all the container examples, such as [nginx configuration](https://6.docs.plone.org/install/containers/examples/nginx-volto-plone.html#nginx-configuration):

> You can either use `localhost`, or add it in your `/etc/hosts` file or DNS to point to the Docker host IP.

**Comment by hipertracker** [comment]
This has nothing to do with /etc/hosts. When you open http://plone.localhost/ you will not see a Plone site:

<img width="629" alt="plone1" src="https://github.com/plone/documentation/assets/649/6f70ef7a-0423-4c3d-89c7-ee1332897e26">



This is the Plone site which should be exposed for the domain:

<img width="718" alt="plone-site" src="https://github.com/plone/documentation/assets/649/8aa09e3c-c679-4931-aa54-a1c441ab7d30">

Nginx should rewrite  http://plone.localhost/ into  http://plone.localhost/VirtualHostBase/http/plone.localhost:80/Plone/VirtualHostRoot

**Comment by hipertracker** [comment]
> nginx configuration

This won't work with Plone clasic. It needs Volto frontend. Plone clasic does not need an additional frontend. It 
only needs proper URL virtual host rewriting

**Comment by hipertracker** [comment]
I refer to this documentation https://6.docs.plone.org/install/containers/examples/nginx-plone.html

**Comment by stevepiercy** [comment]
> This has nothing to do with /etc/hosts. When you open http://plone.localhost/ you will not see a Plone site:

Yes, [I already agreed that you are technically correct, and asked you to provide a PR to correct that](https://github.com/plone/documentation/issues/1576#issuecomment-1817861455).

> Nginx should rewrite http://plone.localhost/ into http://plone.localhost/VirtualHostBase/http/plone.localhost:80/Plone/VirtualHostRoot

I'm not sure whether a rewrite is needed. If one creates a Classic [UI] Plone site, they can still visit the Plone site at http://plone.localhost/Plone. @ericof can you respond as the maintainer of these docs?

As an aside, we need to change that button to "Create Classic UI Plone Site". We've been sloppy with the term, dropping "UI" in some instances.

**Comment by ericof** [comment]
@hipertracker You are correct. the documentation is wrong. Could you, please, send a PR and then assign it to me?

**Comment by hipertracker** [comment]
> @hipertracker You are correct. the documentation is wrong. Could you, please, send a PR and then assign it to me?

I don't know how to assign PR to you. The PR has been created at https://github.com/plone/documentation/pull/1580

**Comment by ericof** [comment]
Fixed in #1580
