### ISSUE TITLE
Contributing to projects has duplicate navigation

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1582]
### Links of affected pages in Plone Documentation, if any.

- [Contributing to plone.api](https://6.docs.plone.org/plone.api/contribute/index.html)
- [Contributing to plone.restapi](https://6.docs.plone.org/plone.restapi/docs/source/contributing/index.html#)
- [Contributing to Volto](https://6.docs.plone.org/volto/contributing/index.html)

### Description

Visit any of the projects contributing pages. Observe that the navigation is duplicated. Links are valid in both copies, but the navigation items should not be duplicated.

Because each project maintains its own contributing policies in its documentation, we need to replace their toctree entries in `contributing/index.md` with entries to new pages in the subdirectory:

- `contributing/plone.api.md`
- `contributing/plone.restapi.md`
- `contributing/volto.md`

Each of these pages will have minimal content of just a heading with a reference link to the project's contributing documentation.

**Comment by SujayVivek** [comment]
Hello maintainers ,
I thought I could give a shot at this issue, so I assigned myself to it. 
Will shortly open a pull request!

**Comment by Smit1324** [comment]
Hello maintainers,
I think I can fix this issue according to my expertise
So, kindly assign me this issue to look forward for my PR

**Comment by stevepiercy** [comment]
@Smit1324 please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html).

@SujayVivek unassigning you due to no pull request in 3 weeks, which is longer than "shortly".

**Comment by Debzoti** [comment]
@stevepiercy Is this issue open to work now?i want to work in the issue.

**Comment by stevepiercy** [comment]
@Debzoti please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially Items 1 and 4 in [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do).

**Comment by Cvr421** [comment]
hello @stevepiercy is this issue is pending. i would like to work on this if anyone is not working.

**Comment by stevepiercy** [comment]
@Cvr421 please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do).
