### ISSUE TITLE
Add documentation to Jenkins

### ISSUE THREAD

**Issue by svx** [plone/documentation#16]
Add the documentation setup to jenkins, so that we catch issues early

**Comment by svx** [comment]
First issue for that is opened on https://github.com/plone/jenkins.plone.org/issues/103

**Comment by svx** [comment]
This is an on going process, thanks to @gforcada we have now our first test on jenkins !!!

**Comment by gforcada** [comment]
@svx keep filling tickets and we will try to add them as soon as possible. For building documentation and so on, the list of dependencies and which steps need to be run will be really helpful :)

**Comment by svx** [comment]
@gforcada is it possible that some of the checks are not working properly ?

For example I checked:

http://jenkins.plone.org/view/All/job/docs-package-styleguide/lastSuccessfulBuild/artifact/report.txt

which is the test, checking for a readme, the test is telling me there is no readme in:

https://github.com/plone/plonetheme.barceloneta

and 

https://github.com/plone/plone.themepreview

but I do have a README.rst in both repos 

any idea what it could be ?

**Comment by gforcada** [comment]
Quite easy, look at the output of a job (I just run it for you): http://jenkins.plone.org/view/All/job/docs-package-styleguide/20/console

svn.zope.org seems to be down and the latest successful build is quite old (more than a month).

**Comment by stevepiercy** [comment]
Closing as obsolete as we now use GitHub Actions for docs.
