### ISSUE TITLE
Obsolete references to collective.autopermission

### ISSUE THREAD

**Issue by gforcada** [plone/documentation#160]
I was reading http://docs.plone.org/external/plone.app.dexterity/docs/advanced/permissions.html and saw that it talks about ``collective.autopermission`` but it already warns that is merged in Zope, so probably we can remove that for both Plone 4 and Plone 5 documentation and keep it (?) for Plone 3?

**Comment by svx** [comment]
This is fixed right? Does that mean we can close this one and https://github.com/plone/plone.app.dexterity/issues/140 ?
