### ISSUE TITLE
Add references about roles, groups, user and workflow policies

### ISSUE THREAD

**Issue by macagua** [plone/documentation#161]
Hi guys

I would be great to add references about roles, groups, user and workflow policies, for example:

Plone: workflow e sicurezza (Just in Italian created by @keul ).
http://plone-worfklow-e-sicurezza.readthedocs.org/en/latest/index.html

**Comment by svx** [comment]
Is someone willing to do this ?, looking at @macagua :) otherwise I will close this, because it fills upthe issue tracker and could be better moved to our trello 'wish board'

**Comment by svx** [comment]
I will close that for now, feel free to open again if you want to work on it
