### ISSUE TITLE
Netlify previews indexed by search engines. Should not, don't they?

### ISSUE THREAD

**Issue by ksuess** [plone/documentation#1619]
### Links of affected pages in Plone Documentation, if any.

-

### Description

sorry, screenshot, as search results are local. You see what I mean…

![grafik](https://github.com/plone/documentation/assets/1144737/e975d90b-9d6b-4db8-b2da-dd04c428a87c)

**Comment by davisagli** [comment]
Ouch. Can we add a robots.txt when building the docs on netlify but not when building them for production?

**Comment by stevepiercy** [comment]
For Volto docs only, yes, and that appears to be only what is being indexed. Update this file to block everything:

https://github.com/plone/volto/blob/main/docs/source/robots.txt

```txt
User-agent: *
Disallow: /
```

For main docs, it would be trickier. We would have to add a final step in https://github.com/plone/documentation/blob/6.0/Makefile#L227-L238 to copy a special `robots.txt` file used only on Netlify, something like `cp <srcpath>/netlify_robots.txt <targetpath>/robots.txt`. Here is our current https://github.com/plone/documentation/blob/6.0/docs/robots.txt.

**Comment by stevepiercy** [comment]
Netlify also supports [setting headers in a `netlify.toml` file](https://docs.netlify.com/routing/headers/#syntax-for-the-headers-file), which could be added to every page for Volto docs only.

```toml
[[headers]]
  for = "/*"
  [[headers.values]]
    X-Robots-Tag = "none"
```

- https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag#xrobotstag
- https://docs.netlify.com/routing/headers/#syntax-for-the-headers-file
