### ISSUE TITLE
Add redirect of `recipes` to `development`

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1669]
### Links of affected pages in Plone Documentation, if any.

As part of the reorganization of docs in Volto in https://github.com/plone/volto/pull/5809, I neglected to include a redirect of the folder to the new location.

Example:

https://6.docs.plone.org/volto/recipes/widget.html#restricting-potential-targets

Should be:

https://6.docs.plone.org/volto/development/widget.html#restricting-potential-targets

### Description

```nginx
location ~ ^/volto/recipes/(.*) {
    return 301 /volto/development/$1;
}
```

Ref: https://community.plone.org/t/volto-docs-are-getting-better/18907

**Comment by polyester** [comment]
Done
