### ISSUE TITLE
Issue on page /backend/upgrading/version-specific-migration/upgrade-to-60.html

### ISSUE THREAD

**Issue by croaklumpish** [plone/documentation#1692]
There are no upgrade instructions on this page. It's very misleading and frustrating. Where can we find upgrade instructions?

**Comment by stevepiercy** [comment]
There is a link in the main navigation [Upgrade guide](https://6.docs.plone.org/upgrade/index.html). This is the entry point to the comprehensive and detailed upgrade guide.

Closing, but if you need further guidance, please reopen and clarify what you need.

**Comment by croaklumpish** [comment]
After I run buildout on 5.2, what do I do? My site doesn't run. instance doesn't run. If I'm upgrading to 6, shouldn't I be running `make start-backend` ? Where is that command? Should it show up after I run buildout on 5.2?

**Comment by stevepiercy** [comment]
It depends on how you set up your Plone site. If the documentation does not provide sufficient guidance, then you will need to post to https://community.plone.org/ for support. GitHub Issues is the last place to ask for support, if at all. See https://plone.org/community/support/how-to-ask-for-help.

**Comment by croaklumpish** [comment]
https://community.plone.org/t/upgade-5-2-to-6/17382
