### ISSUE TITLE
Update cookie* references to current Volto 18.0.0-alpha.43 release

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1706]
### Description

With the release of Volto 18.0.0-alpha.43, we need to review and potentially update or supplement references to `cookiecutter-plone-starter`, `cookiecutter-zope-instance`, and `@plone/generator-volto` with Cookieplone.

- [ ] https://6.docs.plone.org/install/manage-add-ons-packages.html

See also:
- https://github.com/plone/volto/issues/6289
- https://github.com/plone/documentation/pull/1714

**Comment by stevepiercy** [comment]
We need to decide whether to update this page with Cookieplone, or retain it and create a second one for Cookieplone.

Most of the content applies to both cookiecutters, so I would prefer to do an update and use Sphinx Design's synched tabs to display specific content for each cookiecutter. Here's a demo: https://sphinx-design.readthedocs.io/en/latest/tabs.html#synchronised-tabs @sneridagh @davisagli @animus888 @ksuess

**Comment by davisagli** [comment]
@stevepiercy Ugh, this whole page is a mess:
1. None of it really belongs under Install
2. A lot of the information doesn't really belong under the heading "Manage add-ons and packages". "Common management tasks" is currently a subheading but would be a more fitting title for the chapter. (Or possibly there should be an entire "Operating Plone" section with multiple chapters?)
3. "Installation details with Cookiecutter" should be removed or maybe included as a note in the relevant "create a project" chapter
4. "Configuration with cookiecutter-zope-instance" should go under "Common management tasks" and be renamed to "Configure the Zope instance"
5. "Manage Plone backend packages with mxdev" has too much exposition and doesn't belong at this level of the outline. Instead we should have 2 subheadings under Common Management Tasks: "Override a core Plone package version" and "Install a package from source"
6. All of the information about add-ons only covers backend add-ons, but doesn't explicitly say that.
7. "Backend installation details" has details about how the Makefile created by the generator works. This isn't details about installation, and I'm not sure it really belongs here at all.
8. If we go with the synched tab idea, we could include a tab for how to accomplish the same tasks in buildout-based installations -- if someone other than me is willing to provide that info.

**Comment by stevepiercy** [comment]
@davisagli thanks for the feedback. I realize it tries to do too much, and its parts need to be moved elsewhere. Let's follow the Diataxis framework as a guide, which is consistent with your observations. Let's start a PR and collaborate on this.
