### ISSUE TITLE
Contributor email between GitHub and commits must match

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1716]
During the Salamina sprint, we discovered that if the emails between your GitHub user account and your commits do not match, then `mr.roboto` will complain.

To remedy this, we need to document that the contributor's emails between GitHub and commits must match. Here's the proposed snippet to use. @mauritsvanrees @fredvd @folix-01 would you please review?

```md
When pushing a commit to GitHub, the email address in your commit must match an email address in your GitHub account. If it does not match, then `mr.roboto` will notify you that there is a problem that prevents your pull request from being merged.

To change the email address in your commits, see [Setting your commit email address](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address].

To add an email address to your GitHub account, see [Adding an email address to your GitHub account](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/adding-an-email-address-to-your-github-account).
```

We also need to update the mr.roboto message with this clarity and for consistency ~~, and add it to the PCA page at https://plone.org/foundation/contributors-agreement~~. I'll submit an issue or PR as needed.

_Originally posted by @stevepiercy in https://github.com/plone/mr.roboto/issues/163#issuecomment-2378023299_

**Comment by folix-01** [comment]
> 
> ```
> When pushing a commit to GitHub, the email address in your commit must match an email address in your GitHub account. If it does not match, then `mr.roboto` will notify you that there is a problem that prevents your pull request from being merged.
> 
> To change the email address in your commits, see [Setting your commit email address](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address].
> 
> To add an email address to your GitHub account, see [Adding an email address to your GitHub account](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/adding-an-email-address-to-your-github-account).
> ```


In my opinion, this snippet is enaught informative.

**Comment by stevepiercy** [comment]
"enaught"? Do you mean "enough"?

**Comment by folix-01** [comment]
> "enaught"? Do you mean "enough"?

Yeah "enough". My bad sorry :D

**Comment by stevepiercy** [comment]
@folix-01 no worries. Thanks for the feedback. I'll make it happen.

**Comment by stevepiercy** [comment]
PRs made:

- https://github.com/plone/documentation/pull/1722
- https://github.com/plone/mr.roboto/pull/164
