### ISSUE TITLE
Rename "Frontend" and "Backend"?

### ISSUE THREAD

**Issue by davisagli** [plone/documentation#1740]
### Links of affected pages in Plone Documentation, if any.

- overall nav structure

### Description

Could we consider renaming "Frontend" and "Backend" in the navigation?

They are confusing misnomers. "Frontend" currently contains docs about Volto, but the Classic UI also has a frontend. 

I propose that we:
- [x] change the title "Frontend" to "Volto UI"
- [x] move "Classic UI" so it appears immediately after "Volto UI"

"Backend" contains information about developing on Plone-the-framework, which for the most part is relevant to developers working on the Python portion of both Volto sites and Classic UI sites. I propose that we aim to move this content into the new Developer Guide which is started in https://github.com/plone/documentation/pull/1731

@stevepiercy Let me know what you think. If this doesn't seem as obvious to you as it does to me, let's find a time to talk about it.

**Comment by stevepiercy** [comment]
In tonight's Volto Team meeting, we agreed with the two to-do checkbox items above. @sneridagh pointed out that it will also pave the way for the future "Bring your own UI" documentation.

I also agree with "Backend".

**Comment by stevepiercy** [comment]
To make it sensible, without appending ` UI` to every instance of `Volto`, I used wording that makes it clear.

We still have some work to do to guide end users and developers to the right UI for their use case. See https://github.com/plone/documentation/issues/1353 and https://community.plone.org/t/help-installers-choose-a-frontend-classic-ui-or-volto/20004
