### ISSUE TITLE
`pip install pipx` should not be used on page /install/create-project-cookieplone.html

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#1771]
I just realized we have an issue with the [new docs method to install `pipx`](https://6.docs.plone.org/install/create-project-cookieplone.html#pipx). This may affect other pages where we say `pip install pipx`.

@davisagli let's chat about pipx's official documentation to install [pipx](https://pipx.pypa.io/stable/#install-pipx). I think our current method of `pip install pipx` will trip up some users who might try to install it into their system Python with `sudo` or who might create a virtual environment and activate it 😱. I much prefer to link to official docs.

**Comment by davisagli** [comment]
@stevepiercy The official pipx docs don't look like something we can recommend.

For macOS it says to use homebrew to install pipx. I know from experience that that leads to sadness, because it'll use the homebrew-installed Python, and then at some random point in the future homebrew will upgrade Python and then existing software installed with pipx will stop working.

For linux it says to use the OS package manager. In a similar way that means you get the Python from the OS and don't have any control over which version of Python to use.

My preferred path would be to switch to using `uvx` instead of `pipx`, since it also handles installing a compatible version of Python in a cross-platform way.

**Comment by stevepiercy** [comment]
@davisagli what would be the process to install `uvx` instead of `pipx`? And which one?

- https://pypi.org/project/uvx/
- https://pypi.org/project/uvenv/
- https://docs.astral.sh/uv/getting-started/installation/#shell-autocompletion

There's still the matter of using `pip install` without knowing which pip to use. Weren't you the person who pointed me to https://snarky.ca/why-you-should-use-python-m-pip/ ?

**Comment by davisagli** [comment]
@stevepiercy The `uvx` command that comes with `uv`. The standalone installer is the best option for someone who doesn't know what they're doing. https://docs.astral.sh/uv/getting-started/installation/#standalone-installer

> There's still the matter of using pip install without knowing which pip to use. Weren't you the person who pointed me to https://snarky.ca/why-you-should-use-python-m-pip/ ?

I guess I was figuring that you generally want pipx installed globally in whatever Python is your default. Sure, it's probably better to be explicit. But we don't have this problem if we stop using pipx.

**Comment by stevepiercy** [comment]
OK.

Now the hard question: Should we be so bold as to use `uvx` in the docs now or use `python3 -m pip install pipx`?

I'm on the fence. For personal stuff and Plone Sphinx Theme, I'm using `uv` and its friends, but I have also stumbled on some things with it, such as [`uv` discovery of venvs](https://docs.astral.sh/uv/pip/environments/#discovery-of-python-environments). `pip` is most familiar, and `python3 -m pip install pipx` won't require a big change. I reckon we need to throw this out to the Community Forum for a broader discussion.

In docs, we can always add a `note` admonition with a brief explanation of why we use this one way, whichever one we choose.

**Comment by stevepiercy** [comment]
Executive decision: we'll use `pipx`. `uv` is not yet widely adopted in Plone.

Would this be the best method to install `pipx`?

```shell
python3 -m pip install pipx
pipx ensurepath
```

I tried it, and it installed it into my current active Python 3.12. I had an older version in my previously active Python 3.10.

```shell
$ pipx --version
1.2.1

 01:49:02  stevepiercy@Steves-MacBook-Pro  ...projects/Plone/documentation  🐍 3.12.2 3.11.5 3.10.13 system  ⬡ v20.10.0   6.0 ✘ ✹ 
$ python3 -m pip install pipx

Collecting pipx
  Using cached pipx-1.7.1-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: argcomplete>=1.9.4 in /Users/stevepiercy/.local/lib/python3.12/site-packages (from pipx) (3.4.0)
Requirement already satisfied: packaging>=20 in /Users/stevepiercy/.local/lib/python3.12/site-packages (from pipx) (24.1)
Requirement already satisfied: platformdirs>=2.1 in /Users/stevepiercy/.local/lib/python3.12/site-packages (from pipx) (4.2.2)
Requirement already satisfied: userpath!=1.9,>=1.6 in /Users/stevepiercy/.local/lib/python3.12/site-packages (from pipx) (1.9.2)
Requirement already satisfied: click in /Users/stevepiercy/.local/lib/python3.12/site-packages (from userpath!=1.9,>=1.6->pipx) (8.1.7)
Using cached pipx-1.7.1-py3-none-any.whl (78 kB)
Installing collected packages: pipx
Successfully installed pipx-1.7.1

[notice] A new release of pip is available: 24.1.2 -> 24.3.1
[notice] To update, run: /Users/stevepiercy/.pyenv/versions/3.12.2/bin/python3 -m pip install --upgrade pip

 01:50:34  stevepiercy@Steves-MacBook-Pro  ...projects/Plone/documentation  🐍 3.12.2 3.11.5 3.10.13 system  ⬡ v20.10.0   6.0 ✘ ✹ 

$ pipx --version             
1.7.1
```

**Comment by davisagli** [comment]
@stevepiercy I'll continue experimenting with `uvx` for my personal use, but I'm fine sticking with pipx for now. I think using uv can solve some problems that happen when Python gets upgraded or there's a new release of the tool that's being run with pipx/uvx. But it makes sense to have more experienced folks put it through it's paces first.

> I'm using uv and its friends, but I have also stumbled on some things with it, such as [uv discovery of venvs](https://docs.astral.sh/uv/pip/environments/#discovery-of-python-environments).

That sounds like a potential gotcha when using uv to install things into an existing virtualenv that wasn't created with uv. But it wouldn't be a problem when running a tool with `uvx` or `uv tool run`, which create their own temporary virtualenvs. (More info at https://docs.astral.sh/uv/guides/tools/#running-tools)

**Comment by stevepiercy** [comment]
> That sounds like a potential gotcha when using uv to install things into an existing virtualenv that wasn't created with uv.

Correct.

If we go with uv and friends, we will need to go all in. That means there would be quite a few documentation updates, 32 instances in 7 files. We can take PRs, and wait until after PloneConf Trainings to merge them. I don't want to pull the rug out from under them.
