### ISSUE TITLE
Node version is not supported: Got v22.11.0 

### ISSUE THREAD

**Issue by krissik** [plone/documentation#1781]
### Links of affected pages in Plone Documentation, if any.

https://6.docs.plone.org/install/create-project-cookieplone.html

### Description

I have installed nvm and node as described here: https://6.docs.plone.org/install/create-project-cookieplone.html#nvm
After running `pipx run cookieplone project` it says

```
Node: Node version is not supported: Got v22.11.0    
```

I expected that node version is ok because I installed as described in the docs.

I have changed node version to 20 and now `pipx run cookieplone project` works. So either the documentation needs some update or maybe the check for supported node versions?

**Comment by stevepiercy** [comment]
@krissik thanks for the report. See https://github.com/plone/cookieplone/issues/48, which was fixed in https://github.com/plone/cookieplone/pull/49, and was released in https://github.com/plone/cookieplone/commit/a917cd6b32625e6c0d666ed05e16aa27b5f2b65f. Please try installing the latest version of Cookieplone, and try again, then let us know if the issue persists.

**Comment by stevepiercy** [comment]
FYI @ericof @sneridagh @davisagli we should probably update docs with minimum versions of Cookieplone, similar to what we do in `conf.py`.

https://github.com/plone/documentation/blob/27c4998b2d39f1f0b6b7f368264d69feb3ddf53f/docs/conf.py#L439-L444

For example:

```python
    "{COOKIEPLONE_MINIMUM_VERSION}": "8.1",
```

Or would that be too much?

**Comment by krissik** [comment]
> @krissik thanks for the report. See [plone/cookieplone#48](https://github.com/plone/cookieplone/issues/48), which was fixed in [plone/cookieplone#49](https://github.com/plone/cookieplone/pull/49), and was released in [plone/cookieplone@a917cd6](https://github.com/plone/cookieplone/commit/a917cd6b32625e6c0d666ed05e16aa27b5f2b65f). Please try installing the latest version of Cookieplone, and try again, then let us know if the issue persists.

It is working with `pipx run --spec cookieplone==0.8.1 cookieplone project` - Thx!

**Comment by stevepiercy** [comment]
See related issue https://github.com/plone/cookieplone/issues/53

**Comment by stevepiercy** [comment]
Closing as fixed. Please reopen if the issue persists.
