### ISSUE TITLE
Incorrect Instructions in Documentation for install Pillow Dependencies

### ISSUE THREAD

**Issue by pigeonflight** [plone/documentation#1804]
**Summary:** Update incorrect package installation command for Pillow dependencies in the documentation  

**Description:**  
The documentation at the following URL contains an incorrect command for installing required packages on Linux (Debian/Ubuntu):  
[https://6.docs.plone.org/install/create-project-cookieplone.html#install-the-project](https://6.docs.plone.org/install/create-project-cookieplone.html#install-the-project)  

The current command is:  
```  
apt-get zlib libjpeg  
```  
This is not a valid `apt-get` command and results in an error.  

**Steps to Reproduce:**  
1. Navigate to the URL: [https://6.docs.plone.org/install/create-project-cookieplone.html#install-the-project](https://6.docs.plone.org/install/create-project-cookieplone.html#install-the-project).  
2. Follow the instructions to install the required packages using the provided command.  
3. Run the command `apt-get zlib libjpeg`.  
4. Observe that the command fails with an error.  

**Expected Behavior:**  
The correct installation command should be provided to successfully install the required dependencies.  

**Proposed Fix:**  
Update the documentation to replace:  
```  
apt-get zlib libjpeg  
```  
with:  
```  
apt install zlib1g-dev libjpeg8-dev  
```  
or
```  
sudo apt install zlib1g-dev libjpeg8-dev  
```

**Comment by stevepiercy** [comment]
Let's go with this version, assuming you tested that it works (I don't have a Linux box easily available to verify, and I merely copied that command from the Pillow documentation).

```shell
apt install zlib1g-dev libjpeg8-dev
```

**Comment by incrhst** [comment]
Both versions definitely work and have been tested.
