### ISSUE TITLE
Documenting the use of __ac_local_roles_block__

### ISSUE THREAD

**Issue by adamcheasley** [plone/documentation#183]
As far as I can tell, the above flag is still the only way to actually block acquisition of local roles programmatically. Is there any reason that it is not documented here?
http://docs.plone.org/develop/plone/security/local_roles.html
It is mentioned on this page:
http://docs.plone.org/develop/plone/members/sharing_tab.html?highlight=__ac_local_roles_block__
but it's not really explained at all.

If there isn't a reason, I'll submit a pull request to fix this.

**Comment by polyester** [comment]
There is no reason, so it'd be great if you can submit a pull request

**Comment by polyester** [comment]
was closed with https://github.com/plone/documentation/pull/186, thanks!
