### ISSUE TITLE
old reference manuals: Plone 3 themeing 

### ISSUE THREAD

**Issue by svx** [plone/documentation#197]
Is it ok for everyone if I remove this from the plone 5 docs ?

**Comment by gforcada** [comment]
:+1: for plone 5 docs? i would say so, as long as we provide a them on plone 3 and maybe even on plone 4 docsets

**Comment by svx** [comment]
yes they are in the docs of plone 3 and plone 4, and it will stay that way

**Comment by svx** [comment]
done !
