### ISSUE TITLE
broken link viewlets.xml/ more info

### ISSUE THREAD

**Issue by jensens** [plone/documentation#207]
the more info link above section
http://docs.plone.org/develop/plone/views/viewlets.html#viewlet-behavior
to
https://plone.org/documentation/manual/theme-reference/elements/viewletmanager/override
is broken.

**Comment by svx** [comment]
Yeah, this link is not working.

I found this: http://docs.plone.org/4/en/old-reference-manuals/plone_3_theming/elements/viewletmanager/override.html

Is that still valid for 5 ?
