### ISSUE TITLE
Include UI-installer docs to docs.plone.org

### ISSUE THREAD

**Issue by svx** [plone/documentation#214]
Since the UI-Installer has lot of different options, and because it is still missing, we should include the docs into docs.plone.org

todo:
- update UI-Instaler readme with new links
- include [fetch] docs

**Comment by svx** [comment]
https://github.com/plone/Installers-UnifiedInstaller/issues/27

**Comment by stevepiercy** [comment]
Closing as won't fix for Plone 5.
