### ISSUE TITLE
Remove paster from install part

### ISSUE THREAD

**Issue by svx** [plone/documentation#217]
We have to remove paster from:
http://docs.plone.org/manage/installing/installation.html?highlight=wget#id13

Maybe it is possible to update that with mr.bob ?

**Comment by svx** [comment]
@tisto : Do you know the state of plone.mr.bobtemplates ?

**Comment by gforcada** [comment]
@svx you mean https://github.com/plone/bobtemplates.plone ? It has already a 0.9 release on pypi and I think is already/about-to-be blessed from FWT. So for plone5 on everything should be based on it.

**Comment by svx** [comment]
see #193

**Comment by svx** [comment]
done
