### ISSUE TITLE
Add change-logs to releases 

### ISSUE THREAD

**Issue by svx** [plone/documentation#218]
Add a change-log to each to each release:

- find a place to put them
- find a way to create them automated

**Comment by svx** [comment]
what is with about/changelog ?

Comments ? Opinions ? Please do tell ! :)

**Comment by svx** [comment]
this is a bit more tricky :), we want one location for all change logs, meaning all documentation branches and also theme and papyrus, looking at this list maybe we could put the on community ?

or do we want follow best practices and create CHANGES in all repos, write the stuff down there and post them on community too ?

@polyester @esteele what do you prefer ?

**Comment by polyester** [comment]
Actually, I'd like not so much an automated one, but a more human-readable (and human-mentioninging! ) one. Probably an automated one is also useful; but something like 

- Alice Ace helped remove mentions of Grok from our guidelines
- Bob the Builder fixed a whole set of screenshots. 
- and the following people fixed minor bugs: Carol C, David D, Erica E. Thanks all, you rock!

is much more stimulating and appealing to start working. I know it's work, but maybe we can ask for help in doing it.

**Comment by svx** [comment]
Fine with me :) Not a bad idea, yeah I went to the same talk :)

But still the questions remains, where to put them ?

**Comment by polyester** [comment]
Well, remember, documentation is not code ;-) 

So we can put it where we like. I'd say we make a subfolder in "about", call it "history", and put files in there named 2015-05.rst

**Comment by svx** [comment]
I had the idea, till we came up with #226 does is not make more sense to follow that, even if 'documentation is not code' and speaking about that, if we look at papyrus and the theme we talk more about code :) 

For the naming, I would go with the same name per release, as we do in mr.publisher otherwise it could be confusing.

**Comment by esteele** [comment]
@polyester: We're going to try to do the same thing with core releases. http://dw-dev.dreamwidth.org/129563.html is a good example.

**Comment by svx** [comment]
@polyester with mr.publisher [https://github.com/svx/mr.publisher] we use 'date +%Y%m%d' = version as release tag, till now the idea was to use the same tag on github to tag release in the future as from the next release on, this would look like: 20150505.rst would that be good enough for you ?

The nice thing about that would be that all releases would have the same tag .

**Comment by svx** [comment]
We have to mention that in */contributing* too I guess ?

**Comment by svx** [comment]
@polyester && @esteele 

I tried, result is here: https://github.com/plone/documentation/commit/fcb71dee813f22fb68751d56b7c2ddc242b728ba

something like that ?

**Comment by polyester** [comment]
great!

**Comment by svx** [comment]
done
