### ISSUE TITLE
review PloneTestCase references

### ISSUE THREAD

**Issue by gforcada** [plone/documentation#221]
I was answering a question on Stackoverflow ([this one](stackoverflow.com/questions/29660234)) that pointed to [this page on docs.plone.org](http://docs.plone.org/manage/deploying/testing_tuning/testing_and_debugging/unit_testing.html#id2) where there are some code examples and pointers to PloneTestCase.

I guess we want to change those to plone.app.testing ones right?

**Comment by svx** [comment]
Yes +! !

**Comment by spereverde** [comment]
This was adjusted in the docs, it mentions not using PloneTestCase anymore, see https://docs.plone.org/develop/testing/unit_testing.html#creating-unit-tests
I added a comment to the current docs on the stackoverflow page
