### ISSUE TITLE
Moving a Plone site: Incorporate good posts from mailing list thread

### ISSUE THREAD

**Issue by jean** [plone/documentation#222]
See this thread:
  http://sourceforge.net/p/plone/mailman/message/33830864/
  http://sourceforge.net/p/plone/mailman/plone-users/?viewmonth=201504

**Comment by svx** [comment]
This is already in the docs:

http://docs.plone.org/manage/deploying/copy.html

maybe we should try to make it easier to find and rename it ?

reason:

If I search for 'move plone site to another server' I do not find that with google, so we should try to make it easier to find :)

**Comment by stevepiercy** [comment]
Closing as won't fix.
