### ISSUE TITLE
Broken/Missing images/links

### ISSUE THREAD

**Issue by avoinea** [plone/documentation#225]
http://docs.plone.org/working-with-content/adding-content/adding-files.html
http://docs.plone.org/working-with-content/adding-content/adding-events.html

http://docs.plone.org/develop/addons/components/adapters.html#example-adapters-users
http://docs.plone.org/develop/addons/components/adapters.html#local-adapters

**Comment by svx** [comment]
Yeah, looks like there went something wrong with robots-screenshots and it was not recognized during the test builds
