### ISSUE TITLE
Consistency of docs 

### ISSUE THREAD

**Issue by svx** [plone/documentation#248]
I know this comes from diazo docs and we just include them, but I put it here otherwise we will forget it

http://docs.plone.org/external/diazo/docs/deployment.html?highlight=nginx

is saying compile you nginx with buildout, IMHO since we are telling in our 'main' docs people should use system packages we should stick to that.

People who know what they are doing can stick to compile if they prefer it :)

Also: the example version of nginx is in the diazo docs is a bit outdated ... :)

**Comment by stevepiercy** [comment]
Closing as won't fix for Plone 5.
