### ISSUE TITLE
Upgrade guide not clear?

### ISSUE THREAD

**Issue by jensens** [plone/documentation#249]
Without proofing it myself it looks like our upgrade guide is not perfect and leads to confusion, see discussion here (other mails in thread included).
http://sourceforge.net/p/plone/mailman/message/34093660/

**Comment by polyester** [comment]
It's a bug in the migration script, I'd say. But yes, it's probably good to mention the remedy (hand-running the profile steps) in the 'troubleshooting' section.

**Comment by tkimnguyen** [comment]
I think we're also not mentioning this method for upgrading: https://github.com/plone/documentation/blob/6fa86d6dd7b7d52d4b88c875e1564311b938dfe4/manage/deploying/copy.rst 

I ran into this when someone in the forum said they'd tried upgrading by importing a zexp file. https://community.plone.org/t/upgrade-plone-5-0-5-06-results-in-application-javascript-page/3147/5

**Comment by tkimnguyen** [comment]
Oh I'll open a new issue for that... https://github.com/plone/documentation/issues/738
