### ISSUE TITLE
document how to create custom styles in your theme

### ISSUE THREAD

**Issue by djay** [plone/documentation#250]
esp the new plone 5 way to do this 
https://github.com/plone/Products.CMFPlone/issues/492#issuecomment-100435844

**Comment by djay** [comment]
Ah I can see this is going to happen via a change in the plone.app.theming docs already

**Comment by davilima6** [comment]
Hi @djay, could you please refer that change? I couldn't find it. Is this it? plone/documentation#352

I guess final output should be here: https://github.com/plone/documentation/blob/5.0/develop/plone/forms/wysiwyg.rst
