### ISSUE TITLE
Upgrading add-ons to Plone 5

### ISSUE THREAD

**Issue by ebrehault** [plone/documentation#253]
Hi, I would like to initiate this upgrade guide. Where should it be located ?

**Comment by ebrehault** [comment]
Sorry, I found it https://github.com/plone/documentation/blob/5.0/manage/upgrading/addon_upgrade.rst

**Comment by ebrehault** [comment]
Actually it is not here. That's about deploying add-ons.
So I guess it should be in /develop/something, right ?

**Comment by polyester** [comment]
if you think it will be a one-pager, I'd put it at https://github.com/plone/documentation/tree/5.0/develop/addons/plone5-compatibility.rst, or if you think it's going to be more, create a folder plone5-compatibility there and start with an index.rst in it.

**Comment by ebrehault** [comment]
Thank you Paul. Here is it https://github.com/plone/documentation/blob/addon-upgrade-to-5.0/develop/addons/upgrade_to_50.rst and I made a PR (to 5.0 branch)

Note: regarding the name, I though "upgrade" was more accurate than "compatibility" as compatibility somehow implies it would work on both 4.0 and 5.0.
