### ISSUE TITLE
Documentation about plone.app.vulnerabilities

### ISSUE THREAD

**Issue by envycontent** [plone/documentation#259]
Not exactly a documentation issue but I couldn't see where to file this one:

If I search plone.org for hotfix, I end up at this page:

https://plone.org/products/plone/security/advisories

if I follow the first link on that page I get to here:

https://plone.org/products/plone-hotfix/

which tells me the information is out of date and mentions plone.app.vulnerabilities

Would it be possible please to put a link to some documentation about plone.app.vulnerabilities on that page. Otherwise you end up going round in circles and are none the wiser as to how to apply hotfixes or if there are any...

Thanks

Anne

**Comment by polyester** [comment]
I think it is a documentation issue. We should point out that the canonical listing is https://plone.org/security/hotfixes 

Thanks for pointing it out!

**Comment by envycontent** [comment]
Yes, though I'm intrigued as that listing only goes as far as 2013 (perhaps there were none in 2014/2015?) and I still don't really understand what happens with plone.app.vulnerabilities.

**Comment by polyester** [comment]
There were none in 2014 and 2015, and plone.app.vulnerabilities is the add-on that generates the list at  https://plone.org/security/hotfixes. It is not something that's meant to install into your own site.

I'll write some documentation.

**Comment by envycontent** [comment]
Ah ha. Thanks! Now I understand. Some documentation would be really helpful.
