### ISSUE TITLE
Move from trello to waffle.io ?

### ISSUE THREAD

**Issue by svx** [plone/documentation#264]
Seems no one besides me is using the docs board on trello, should we stop using it and use [waffle](https://waffle.io/) instead ?

**Comment by polyester** [comment]
I think that's OK. I've been looking at zenhub also, but waffle.io is more cross-browser. And is being used by other teams (ploneorg release - team) as well, so has traction already.

**Comment by fulv** [comment]
Ploneintranet uses it too.

**Comment by svx** [comment]
All-right I will try to find out how I can add a organisation repository

**Comment by svx** [comment]
So it seems I have to give waffle.io permissions to the whole organisation, hm ... not sure if I want that.

**Comment by polyester** [comment]
already done for other repos in plone org, so just go ahead. You know you want to press the button ;-)

**Comment by svx** [comment]
where ? I checked the organisation settings and I do not see waffle there.

**Comment by fulv** [comment]
https://waffle.io/plone/documentation

**Comment by svx** [comment]
Yes I saw/see that but is this created with a user or with the box bellow on the waffle website ?

**Comment by svx** [comment]
closing this, since there are only a couple of people working constantly  I do not see that we need that atm :)
