### ISSUE TITLE
Release: 20150518 

### ISSUE THREAD

**Issue by svx** [plone/documentation#265]
- [x] update changelog Plone3 docs
- [x] update changelog Plone4 docs
- [x] update changelog Plone5 docs
- [x] update changelog Papyrus3
- [x] update changelog Papyrus4
- [x] update changelog Papyrus5
- [x] update changelog sphinx.themes.plone
- [x] update server
- [x] upgrade nginx version
- [x] change nginx to new setup
- [x] add nginx config for training.plone.org
- [x] add nginx config for training.plone.org/4
- [x] add nginx config for training.plone.org/5
- [x] landing page for training.plone.org
- [x] custom 404 for training.plone.org/
- [ ] add cloudfare
- [ ] update mr.publisher [add training]
- [x] remove docsets build script from mr.publisher
- [x] check and follow release notes on github
- [ ] tag as *release 20150518* on github
- [x] build Plone 3 docs
- [x] build Plone 4 docs
- [x] build Plone 5 docs
- [x] test docs for Plone 3, 4 and 5
- [x] build Plone 3 docset
- [x] build Plone 4 docset
- [x] build Plone 5 docset
- [x] build training Plone 4
- [x] build training Plone 5
- [x] update stats on papyrus github
- [x] push to server
- [x] publish changelog on community
- [x] add training.plone.org [landing page] to github

**Comment by gforcada** [comment]
go go go! ;)

**Comment by svx** [comment]
old and out of date, closing this now
