### ISSUE TITLE
Add robot.txt for Plone 5 alpha docs

### ISSUE THREAD

**Issue by svx** [plone/documentation#274]
Should we add a robot.txt to the alpha docs of Plone 5 ?

I am asking because I am not sure now search engines and people can find them, but since there will change a lot, bookmarks will most likely brak, so if user now save a page of Plone 5 alpha docs as a bookmark there is a big chance that this bookmark will not work anymore once the 5 docs are official.

On the other hand there is a huge label 'alpha, do not use in production' on the 5 docs for now.

So what you think ? Opinions ? Comments ? Ideas ?

**Comment by jensens** [comment]
i think since we're beta it should be found as alpha docs too. http://docs.plone.org/ should have it in tis dropdown as well. 
But a big red ``alpha`` ribbon (like the github for robbons here https://github.com/blog/273-github-ribbons) in the top left/right corner is anyway a very good idea.

**Comment by svx** [comment]
closing this, we will leave it as it is for the moment and with the next release will will put it in the drop down
