### ISSUE TITLE
Plone 5 with WSGI

### ISSUE THREAD

**Issue by svx** [plone/documentation#279]
Should we add this to docs.plone.org ?

http://blog.toms-projekte.de/run-plone-with-wsgi.html

**Comment by svx** [comment]
Any hints, what would be a good place on docs.plone.org to mention/link to them ?

**Comment by jensens** [comment]
This is very special information. There are so many open questions. But I really would like to see the WSGI publishing pushed a bit and we may want to link it 
As we already have a page here:
https://github.com/plone/documentation/blob/5.0/manage/deploying/wsgi.rst
I would put the link there.

**Comment by svx** [comment]
@jensens thanks ! I will start work on this right now

**Comment by svx** [comment]
done
