### ISSUE TITLE
Mention collective.solr docs in Backend > Search, or maybe Deployment?

### ISSUE THREAD

**Issue by svx** [plone/documentation#281]
The rewrote of the docs of collective.solr is done, during PLOG 2015 was decided to include them, into docs.plone.org from docs for Plone 5 on.

Todo:
- find the right place to put them
- add to current papyrus
- add to new test papyrus written by @jensens and test how that works

**Comment by svx** [comment]
First this need to be fixed:

https://github.com/collective/collective.solr/issues/67

**Comment by svx** [comment]
- create entry pages for different use cases:
1. user who has already a site running and wants to include solr
2. use who is beginning form ' scratch' 

- add, update and rearrange docs for setup and installation for both use cases

**Comment by tisto** [comment]
I don't think it makes a lot of sense to separate those use cases since they are pretty similar (add c.solr, install c.solr, reindex). The only difference when adding c.solr to an existing site is that reindex takes longer. Even if c.solr is installed on a vanilla Plone site, you need to run reindex to include the default content.

**Comment by svx** [comment]
I guess we are talking about different things or I am not clear enough in what I try to say.

The docs are not that clear bout that at the moment, if you look at the docs as a Integrator they are a bit confusing if you 'just' want to add c.s to your already running site.

We did a test last week with 5 different Plone Integrators, and all of them had a hard time to understand the docs.

Do not get me wrong the docs are awesome and it a great start, but at the moment they are more for devs and not for Integrators. :)

Lets talk about that later ! :)

**Comment by gforcada** [comment]
What's the status here? I would like to read html rather than rst :)

**Comment by svx** [comment]
It is still open ? :)

The docs structure and the rst needs cleanup and the docs need review there are confusing in some parts at least for interrogators :)

**Comment by stevepiercy** [comment]
`collective.solr` has its own docs hosted on RTD. We don't need to pull them in, but a mention in the Plone 6 docs would be sufficient.

- [ ] Add a link and brief description copied from its README in [Backend > Search](https://6.docs.plone.org/backend/search.html) as an alternate search tool, or perhaps [Deployment](https://6.docs.plone.org/deployment/index.html), to both:
  - https://collectivesolr.readthedocs.io/en/latest/
  - https://github.com/collective/collective.solr

@jensens @gforcada @sneridagh @davisagli @tisto @MrTango can you give me some context for where this mention would be belong?

**Comment by gforcada** [comment]
IMHO it belongs to `Backend > Search`, and once you learn about how you can improve the search with Solr, then I expect the Solr docs to point you how to deploy them.

Solr is quite a powerful server, so just like Plone, it can span from a single server to multiple servers with replication, sharding and what else that makes it all very complex.

I'm not sure if that really belongs to Plone's documentation... if you want to scale it big, you have to get some learning and probably your company has some tooling already for that etc etc.

**Comment by jensens** [comment]
I would mention there are additional solutions around to enhance the Plone search experience, like collective.solr, collective.elasticsearch,  collective.elastic.plone ... or way better, point to [awesome-plone -> searching and Categorizing](https://github.com/collective/awesome-plone?tab=readme-ov-file#searching-and-categorizing). Overall I would not start adding documentation on non-core addons here.
