### ISSUE TITLE
Source of inspiration(?)

### ISSUE THREAD

**Issue by gforcada** [plone/documentation#286]
While reading planet plone I came across this link:

How to write awesome README files https://github.com/matiassingers/awesome-readme

Maybe we can get some ideas and put them as guidelines and update bobtemplates.plone to use them as well?

**Comment by fulv** [comment]
+1

**Comment by svx** [comment]
Hi,
you know that we already have this covered in the docs right ? :)

There is a difference between README driven development and Documentation driven development, these ones from the example are  more focused on README driven documentation.

Further on we have already a part about how to write a README example [best practices] which is already followed by a couple of add-ons and projects.
The example what we use is taken from the #readthedocs folks and slightly modified for plone.
You can find it here: 
http://docs.plone.org/about/documentation_styleguide_addons.html#readme-example

**Comment by svx** [comment]
closing this, feel free to re-open
