### ISSUE TITLE
http://localhost vs http://127.0.0.1

### ISSUE THREAD

**Issue by svx** [plone/documentation#287]
Currently we do use both in the docs, I want to change for various reasons like:
- unify the docs
- easier for new people, because less confusion
- better ranking 

question: which one we prefer ?

**Comment by polyester** [comment]
localhost. It should still work when ipv6 (and ipv8 and ipv10) are around

https://en.wikipedia.org/wiki/Localhost

**Comment by svx** [comment]
this also should go into 'best practices' btw.

**Comment by svx** [comment]
Plone 5 docs: 55 places
Plone 4 docs: 54 places

that are the 'core' docs without any external, lMHO something for a boring night or the sprint, we should get that fixed asap

**Comment by pbauer** [comment]
:+1: for localhost since it can be memorized even by beginners. It also is consistently used in http://training.plone.org

**Comment by jensens** [comment]
+1 for localhost

**Comment by svx** [comment]
done for Plone 5 branch, besides the docs of varnish and nginx

**Comment by svx** [comment]
Done for 'core-docs' besides for nginx. apache and varnish

**Comment by svx** [comment]
do we still need that in the 4 docs ?

**Comment by polyester** [comment]
would be nice, also simplifies the 'URL exception' list.

**Comment by macagua** [comment]
localhost +1

**Comment by pigeonflight** [comment]
Definitely localhost.

 127.0.0.1 returns an unthemed site out of the box. When using the training.plone.org material one developer thought things were broken because (being smart) he went to 127.0.0.1:8080. 

It may be worth noting somewhere in the docs the difference between 127.0.0.1 and localhost when it comes to theming.

**Comment by svx** [comment]
done !
