### ISSUE TITLE
check /develop/misc

### ISSUE THREAD

**Issue by svx** [plone/documentation#291]
At least under /plone, there are lots of old stuff which is changed or move and so not valid for Plone 5 anymore

**Comment by kcleong** [comment]
For the following parts I am not completly sure if the docs are outdated:

- http://docs.plone.org/develop/plone/misc/context.html#itools-interface

**Comment by kcleong** [comment]
Keeping the iITools docs in place after checking with pbauer

**Comment by kcleong** [comment]
Pull request: https://github.com/plone/documentation/pull/321

**Comment by svx** [comment]
thanks @kcleong !
