### ISSUE TITLE
grok-alert for 5 branch

### ISSUE THREAD

**Issue by polyester** [plone/documentation#296]
the following are *not* correct anymore for Plone5. For now, they are still in that branch, but need fixing.

- [x] develop/addons/schema-driven-forms/creating-a-simple-form/creating-a-package.rst
- [x]  develop/addons/schema-driven-forms/creating-a-simple-form/creating-the-form-view.rst
- [x]  develop/plone/forms/files.rst
- [x]  develop/plone/forms/manual.rst
- [x]  develop/plone/forms/wysiwyg.rst
- [x]  develop/plone/forms/z3c.form.rst
- [x]  develop/plone/functionality/controlpanel.rst
- [x]  develop/plone/i18n/translating_content.rst (that one needs an overhaul anyway...)
- [x]  develop/plone/i18n/misc/html.rst
- [x]  develop/plone/i18n/serving/http_request_and_response.rst
- [x]  develop/plone/i18n/views/browserviews.rst

**Comment by kcleong** [comment]
I've updated all pages, merge request available at: https://github.com/plone/documentation/pull/319

**Comment by polyester** [comment]
and the prize for super-efficiency goes to: @kcleong
