### ISSUE TITLE
Remove/update links to svn.plone.org

### ISSUE THREAD

**Issue by svx** [plone/documentation#297]
For Plone 4 and Plone 5 docs

**Comment by svx** [comment]
/develop/addons/javascript.rst:* http://svn.plone.org/svn/collective/mfabrik.like/trunk/mfabrik/like/viewlets.py
./develop/plone/content/behaviors.rst:* `plone.app.headerimage <https://svn.plone.org/svn/collective/plone.app.headeranimation/trunk/plone/app/headeranimation/behaviors.py>`_.
./develop/plone/content/creating.rst:* `Singing & Dancing <https://svn.plone.org/svn/collective/collective.dancing/trunk/collective/dancing/channel.py>`_.
./develop/plone/content/importexport.rst:* https://svn.plone.org/svn/collective/quintagroup.transmogrifier/trunk/quintagroup/transmogrifier/catalogsource.py
./develop/plone/forms/files.rst:See `example in plone.app.headeranimations <https://svn.plone.org/svn/collective/plone.app.headeranimation/trunk/plone/app/headeranimation/browser/widgets.py>`_.
./develop/plone/forms/z3c.form.rst:* Easy: `plone.app.headeranimation animation and image list manager <https://svn.plone.org/svn/collective/plone.app.headeranimation/trunk/plone/app/headeranimation/browser/forms.py>`_.
./develop/plone/forms/z3c.form.rst:* Complex: `Singing & dancing channel manager example <https://svn.plone.org/svn/collective/collective.dancing/trunk/collective/dancing/browser/channel.py>`_
./develop/plone/functionality/portlets.rst:* `Templated portlet <https://svn.plone.org/svn/collective/collective.easytemplate/trunk/collective/easytemplate/browser/portlets/templated.py>`_
./develop/plone/i18n/translating_content.rst:See https://svn.plone.org/svn/collective/raptus.multilanguagefields/trunk/raptus/multilanguagefields/samples/
./develop/plone/images/templates.rst:<http://svn.plone.org/svn/collective/Products.ATContentTypes/trunk/Products/ATContentTypes/content/image.py>`_.
./develop/plone/misc/html.rst:* http://svn.plone.org/svn/collective/intelligenttext/trunk/README.txt
./develop/plone/serving/publishing.rst:.. * `plone.app.headeranimations animations traversing code <https://svn.plone.org/svn/collective/plone.app.headeranimation/trunk/plone/app/headeranimation/browser/traverse.py>`_.
./develop/plone/sessions/login.rst:* http://svn.plone.org/svn/collective/niteoweb.loginas/trunk/niteoweb/loginas/browser/login_as.py
./develop/plone/sessions/login.rst:* https://svn.plone.org/svn/collective/PASPlugins/Products.LoginLockout/branches/ajung-login-logging/
./develop/plone/views/viewlets.rst:See `collective.fastview <http://svn.plone.org/svn/collective/collective.fastview/trunk/>`_ for updates
./develop/plone/views/viewlets.rst:``<script>`` elements. Example is taken from `mfabrik.like add-on <https://svn.plone.org/svn/collective/mfabrik.like/trunk>`_.
./develop/plone-coredev/plipreview.rst: * https://svn.plone.org/svn/plone/buildouts/plone-coredev/branches/4.1/plips/plip9352-review-davisagli.txt
./develop/plone-coredev/plipreview.rst: * https://svn.plone.org/svn/plone/buildouts/plone-coredev/branches/4.1/plips/plip10886-review-cah190.txt
./develop/plone-coredev/plipreview.rst: * https://svn.plone.org/svn/plone/buildouts/plone-coredev/branches/4.1/plips/plip9352-review-rossp.txt

**Comment by kcleong** [comment]
Pull request ready at https://github.com/plone/documentation/pull/326

**Comment by svx** [comment]
thanks !

**Comment by svx** [comment]
done !
