### ISSUE TITLE
add zcml reference from plone.behavior README.rst to documentation

### ISSUE THREAD

**Issue by jensens** [plone/documentation#308]
https://github.com/plone/plone.behavior/blob/master/README.rst contains some useful parts such as zcml reference with examples. we may want to use this in here https://github.com/plone/documentation/blob/5.0/develop/plone/content/behaviors.rst

**Comment by stevepiercy** [comment]
I think this was resolved and published in https://6.docs.plone.org/backend/behaviors.html. If not, please open a pull request with desired changes. Thank you!
