### ISSUE TITLE
[paster] manage/troubleshooting/exceptions

### ISSUE THREAD

**Issue by svx** [plone/documentation#313]
- remove paster
- check and update document

**Comment by spereverde** [comment]
There are still some references to paster in the docs, I can start a cleanup

Can I remove this zopeskel exception from the common exceptions list?https://docs.plone.org/manage/troubleshooting/exceptions.html#from-zopeskel-basic-namespace-import-basicnamespace 
@svx, @polyester opnions?

**Comment by stevepiercy** [comment]
Closing as won't fix for Plone 5.
