### ISSUE TITLE
develop/addons/helloworld

### ISSUE THREAD

**Issue by svx** [plone/documentation#314]
- needs review
- check and update to Plone 5 and best practices

**Comment by polyester** [comment]
After talking to the training.plone.org people, decided to scrap it and point to the training instead.

**Comment by polyester** [comment]
ah sorry. Scrapped the tutorial.todoapp one. This still needs review/rewrite, or also replacement by training.

**Comment by polyester** [comment]
After talking to the training people, it needs to be scrapped, and replaced with the latest example from training.plone.org. Will close when done that (tomorrow)

**Comment by polyester** [comment]
closed via https://github.com/plone/documentation/pull/446
