### ISSUE TITLE
list of errors for externally-included docs

### ISSUE THREAD

**Issue by polyester** [plone/documentation#33]
collective/tutorial.todoapp: index, list of modules, own searchbox not working, has GH warning
plone.api: has GH warning
plone.app.testing: index, list of modules, own searchbox not working 
(beginning to suspect this is an artifact of sphinx defaults...)

**Comment by svx** [comment]
![todo_app_warning](https://cloud.githubusercontent.com/assets/358860/8643324/9aa064c8-2932-11e5-9ff0-4f8c7042cc8b.png)

**Comment by stevepiercy** [comment]
Closing as won't fix. Feel free to reopen if it is still a thing.
