### ISSUE TITLE
Unable to build under FreeBSD (make externals: Error expanding embedded variable)

### ISSUE THREAD

**Issue by mjollnirpaul** [plone/documentation#334]
Can s/o help?  I want to build the docs for offline use like described on the start page on github.
Here's what I did:
[root@paul-lifebook /usr/local/www/Plone/papyrus]# ./bin/python bootstrap-buildout.py
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-18.0.1.zip
Extracting in /tmp/tmp3IUMcp
Now working in /tmp/tmp3IUMcp/setuptools-18.0.1
Building a Setuptools egg in /tmp/tmpc7FVRV
/tmp/tmpc7FVRV/setuptools-18.0.1-py2.7.egg
Creating directory '/usr/local/www/Plone/papyrus/develop-eggs'.
Generated script '/usr/local/www/Plone/papyrus/bin/buildout'.
[root@paul-lifebook /usr/local/www/Plone/papyrus]# bin/buildout
mr.developer: Queued 'documentation' for checkout.
mr.developer: Queued 'plone.api' for checkout.
mr.developer: Queued 'sphinx-intl' for checkout.
mr.developer: Queued 'sphinx.themes.plone' for checkout.
mr.developer: Skipped checkout of existing package 'sphinx.themes.plone'.
mr.developer: Skipped checkout of existing package 'documentation'.
mr.developer: Skipped checkout of existing package 'plone.api'.
## The current global buildout threat level is:   GUARDED  

Upgraded:
  zc.buildout version 2.2.4,
  setuptools version 7.0;
restarting.
Generated script '/usr/local/www/Plone/papyrus/bin/buildout'.
mr.developer: Queued 'documentation' for checkout.
mr.developer: Queued 'plone.api' for checkout.
mr.developer: Queued 'sphinx-intl' for checkout.
mr.developer: Queued 'sphinx.themes.plone' for checkout.
mr.developer: Skipped checkout of existing package 'plone.api'.
mr.developer: Skipped checkout of existing package 'sphinx.themes.plone'.
mr.developer: Skipped checkout of existing package 'documentation'.
## The current global buildout threat level is:   GUARDED  

Develop: '/usr/local/www/Plone/papyrus/source/plone.api'
warning: no files found matching 'docs/README.rst'
warning: no previously-included files matching '_.pyc' found anywhere in distribution
Develop: '/usr/local/www/Plone/papyrus/source/sphinx-intl'
Develop: '/usr/local/www/Plone/papyrus/source/sphinx.themes.plone'
warning: no previously-included files matching '_.pyc' found anywhere in distribution
Unused options for buildout: 'checkout'.
Updating _mr.developer.
Updating sphinx-build.
Updating sphinx-intl.
Updating transifex-client.
Updating robot.
Updating pybot.
Generated script '/usr/local/www/Plone/papyrus/bin/pybabel'.
Updating pybabel.
Generated script '/usr/local/www/Plone/papyrus/bin/pybabel'.
Updating i18ndude.
Getting distribution for 'i18ndude'.
warning: no previously-included files matching '*.pyc' found anywhere in distribution
no previously-included directories found matching 'src/zope.tal'
Got i18ndude 3.4.2.
Generated script '/usr/local/www/Plone/papyrus/bin/i18ndude'.
[root@paul-lifebook /usr/local/www/Plone/papyrus]# make externals
Error expanding embedded variable.

**Comment by polyester** [comment]
Make sure the get externals.sh script is executable

**Comment by mjollnirpaul** [comment]
There is no externals.sh script.
The Makefile is non-standard.  Solution is to use gmake instead of standard make...

Hint: It would be safer and more portable if people would not use bash extensions in shell scripts and not rely on GNU make extensions but use standard make syntax in Makefiles...
Yes, someday I'll start a Linux-bashing web site... ;)

**Comment by polyester** [comment]
@mjollnirpaul could you check again with the "5.0" branch (currently default)? (sorry but don't have freeBSD available right now. Is there something like a canonical FreeBSD virtualbox/vagrant image?)

**Comment by mjollnirpaul** [comment]
Am Sonntag, 20. September 2015, 14:54:39 schrieb polyester:

> @mjollnirpaul could you check again with the "5.0" branch (currently
> default)? (sorry but don't have freeBSD available right now. Is there
> something like a canonical FreeBSD virtualbox/vagrant image?)

http://www.freebsd.org/where.html

FWIW, it was not hard to find: Click on "Download FreeBSD" on the web 
site www.freebsd.org... ;)

You may want to download the 10.2-Release (current production release) 
and/or the image of 11-current (developer's choice) for any VM you have.

AFAIC these are "bare" OS images, i.e. only the kernel and basic 
userland.  You'll certainly have to install some software like bash etc.
  # pkg install bash

## Good luck!

=|o)

**Comment by stevepiercy** [comment]
Closing as won't fix for Plone 5. We replaced the build system for Plone 6.
