### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by gforcada** [plone/documentation#335]
Clicking on the _Developer manual_ link here http://docs.plone.org/5/en/develop/plone/content/content_rules.html (both plone 4 and plone 5 docs) gives you a permission error on plone.org

Is the content long gone or it is still around somewhere?

**Comment by svx** [comment]
The content is still there, but it too old, we should remove that link or link to the u2d docs part on docs.plone.org

**Comment by polyester** [comment]
the user part should be a link to http://docs.plone.org/5/en/working-with-content/managing-content/contentrules.html, the developer part basically needs to be rewritten (and maybe a link to a 'minimal' example. Maybe https://github.com/collective/collective.contentrules.talesaction, or any others)
