### ISSUE TITLE
Document controlpanel migration formlib -> z3c.form for Plone 5

### ISSUE THREAD

**Issue by tomgross** [plone/documentation#343]
With the removal of formlib dependencies in Plone 5.0b3 many addons with custom controlpanels no longer work:
- collective.solr
- quintagroup.seoptimzer

We should provide an upgrade guide for addon developer on howto upgrade their controlpanels

**Comment by stevepiercy** [comment]
Closing as stale. If someone opens a PR to add it to https://6.docs.plone.org/backend/upgrading/version-specific-migration/upgrade-addons-to-50.html, I'll review it.
