### ISSUE TITLE
Theming documentation

### ISSUE THREAD

**Issue by sneridagh** [plone/documentation#350]
TTW is back (for good) for theming and we have to take advantage from it to attract more people to Plone. Easy quick testing and customization is very important to achieve it. Installers and other quick deployment approaches are great, but we need a good documentation on easy and TTW customization as well. We have the idea to define scenarios like these ones trying to cover the most common use cases.
# Scenarios

**The new to Plone theming scenario.** Maybe non-technical person or IT manager with limited skills want to test drive Plone and wants to do some basic customizations. For example change the logo or change some basic theme colors. This should be done with Plone OOTB.

**The Plone theming initiated.** Maybe a technical or non technical person who wants to gain more Plone skills and want to customize some of the Barceloneta templates. This should be achieved by simply installing c.jbot.

**The Plone theming TTW master.** Maybe a technical or non technical person who wants to add a custom CSS that extends Barceloneta directly. This should be achieved by creating a custom bundle via Resource Registries and add the additional resources or by using p.a.theming TTW cloning/editing features.

**The Plone Diazo theming first degree.** Maybe a technical person who wants to explore Plone theming and wants to modify/extend Barceloneta theme to match some simple customization requirements. This should be achieved by learning how to create a filesystem theme package and learning basic Diazo and how Barceloneta is architectured.

**The Plone Diazo theming adept.** Maybe a technical with a basic knowledge of Plone that wants to integrate a full external theme from an external designer. He should know advanced Diazo and maybe take advantage of some parts of Barceloneta for reuse.

**The working prototype approach.** Used by Plone Intranet. (More details needed)

Any other scenarios we've missed? Contributions are welcome!

The names of the scenarios are open to discussion ;)
# Toolbar

It's also required to document how to customize and extend the new Plone 5 toolbar.
# Control Panel

We need to document how to create new control panel items and add the custom icon correctly.

**Comment by MrTango** [comment]
Hi victor, simone orsi and i will work on the theming training for the next 2,5 days in roma.
We will discuss your idears and try to integrate it with ours.

**Comment by djay** [comment]
Would be great to test and document the technique of theming frontend and back differently from https://github.com/plone/Products.CMFPlone/issues/465

**Comment by davilima6** [comment]
I'd like to help on this one.

**Comment by stevepiercy** [comment]
Closing as stale.
