### ISSUE TITLE
TinyMCE integration and plugin documentation - needs mockup overhaul

### ISSUE THREAD

**Issue by polyester** [plone/documentation#352]
https://github.com/plone/documentation/blob/5.0/develop/plone/forms/wysiwyg.rst needs overhaul to account for mockup

**Comment by polyester** [comment]
@vangheem any pointers? Checking with JC but not really sure. TinyMCE's UI has field for "Custom Plugins", but not much clue what to put in there.

I will overhaul the rest of TinyMCE docs, but how to integrate third-party plugins in the new mockup context, I have no idea.

**Comment by vangheem** [comment]
I'll see what I can do. A lot of those docs do not make any sense in 5.

**Comment by polyester** [comment]
Quite a lot can simply be ripped out. I'll start on that.

I've updated the end-user manual at http://docs.plone.org/5/en/working-with-content/using-tinymce-as-visual-editor and there's initial docs for the site-setup screen at http://docs.plone.org/5/en/adapt-and-extend/config/tinymce.html. And enabling safe-html is already documented elsewhere, so can go. 

What's missing is
- how to enable third-party plugins
- and maybe 'hacking on tinymce', or maybe that should just go too.
- I don't know if that "Customizing TinyMCE options" with GenericSetup is still valid

**Comment by vangheem** [comment]
"Customizing TinyMCE options" is all done with the configuration registry now. No more tinymce.xml

I'll update and make additional tweaks right now.

**Comment by vangheem** [comment]
@polyester https://github.com/plone/documentation/commit/29ecd81b2d038796d90722262da04f461a125571

I just committed directly. I hope that's okay.

**Comment by vangheem** [comment]
uh oh! https://travis-ci.org/plone/documentation/builds/81162468

I'll see what I screwed up. Sorry about that.

**Comment by vangheem** [comment]
Oh wait, looks like it's failing for everyone :)

**Comment by polyester** [comment]
yep, there's something wrong with the travis config since switching branches. Investigating but not my strong point.

**Comment by svx** [comment]
Maybe check:

https://github.com/plone/papyrus/blob/5.0/checkouts-documentation.cfg

there is the line:
#documentation is special, we want full history and push URL
documentation               = git ${remotes:plone_push}/documentation.git egg=false branch=5.0

you renamed the 5 branch to master, maybe that is why it is complaining ?

**Comment by polyester** [comment]
no, there is no more master branch. The branch is still 5.0, only it is now default.

I think it has to do with the
- mkdir -p source && ln -s ../../documentation source/documentation
- mkdir -p buildout-cache/downloads
- python bootstrap-buildout.py
- bin/buildout -N -t 3 buildout:checkout=documentation sources:documentation="fs
  documentation egg=false"

in the .travis.yml, since now that symbolic linking is already done by papyrus. It errors with the message "mr.developer: Directory for package 'documentation' doesn't exist.". So I will now try an attempt without symlinking documentation, but just pulling it with git.

**Comment by polyester** [comment]
Travis seems to work now. OK, it's agonizingly slow, but seems to work. I may have accidentally disabled some caching, although by far the most time is spent in making robot-screenshots. Still, how was it,  "cattle, not pets"? Then I'm making mules to carry the heavy load.

@svx if you have some secret magic sauce to make travis run faster, that would of course be hugely appreciated.
