### ISSUE TITLE
list of broken links

### ISSUE THREAD

**Issue by polyester** [plone/documentation#36]
I've run "make linkcheck", and a large number of links are broken. I've fixed a number of them already, prioritizing the end-user docs. 

The list is in the repo, at https://github.com/plone/documentation/blob/master/broken-20140331.txt

for the moment: if you fix a broken link, update that file and push.

**Comment by svx** [comment]
updated list: https://github.com/plone/documentation/blob/master/broken-links-nov2014.txt

**Comment by fulv** [comment]
I found this issue when I was looking for what to do about [this broken link](https://plone.org/documentation/kb/using-unauthorized-modules-in-scripts), which is on `develop/plone/security/sandboxing.rst`.

I checked this file and could not find it:  https://github.com/plone/documentation/blob/5.0/broken-20140331.txt

But it is in https://github.com/plone/documentation/blob/4.3/broken-links-nov2014.txt
(notice 4.3 vs 5.0)

So the question is:  has anyone decided what to do about the kb articles?

**Comment by polyester** [comment]
at the Stroopwafel and Munich doc-sprints, people looked through the kb and decided to scrap the whole thing. There may still be some valid nuggets of information in there, but the ratio of valid versus outdated-to-plain-dangerous is not favorable, to say the least.

So links to the kb should be removed. If you happen to find one that contains sane, still-valid info, the content of the kb-article should go into the docs.

**Comment by svx** [comment]
closing this we know that we have lots of broken links, they are fixed step by step on the way and will included into the coming docs test framework

:)
