### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by svx** [plone/documentation#381]
latest change-log is missing, there is only one called pre-alpha, there should be an up to date one or no one, having only a pre-release change-log online is not really prefect.

**Comment by svx** [comment]
@polyester you did a release on 12 of December 2015 and you did not updated the changelog, again ... please fix that !

**Comment by thet** [comment]
Maybe I should have updated it? I did the latest change in papyrus

**Comment by svx** [comment]
@thet well, than you also should update: https://github.com/plone/papyrus/blob/5.0/CHANGES.rst :)

But I am talking about: https://github.com/plone/documentation/tree/5.0/about/history

**Comment by svx** [comment]
Will be fixed with the upcoming build, we moved it out of the source of the docs, according to GA, almost no one was looking at them, now the repo will follow 'best practices' and the Changelog is now under CHANGES under / of the repo.
We excluded it from sphinx, so it will not produce any errors or warnings.

The branches with the changes [docs and papyrus]:

https://github.com/plone/documentation/tree/release_mar2016-01

https://github.com/plone/papyrus/tree/release_mar2016-01

**Comment by svx** [comment]
done, ticket got forgotten, closing
