### ISSUE TITLE
Updated information for Plone 5

### ISSUE THREAD

**Issue by svx** [plone/documentation#382]
http://docs.plone.org/about/reading.html#id2 is still showing information for Plone 4, this is could be confusing since we are reading the Plone 5 docs, 
- needs up to date pictures
- needs to be updated to Plone 5

**Comment by deesto** [comment]
Hi,

Even though this is marked 'closed', the only procedure available for upgrading Plone to date (13 Jan 2016) seems to be the 4.x minor upgrade procedure, which, I assume, is deprecated for 5.x. There is a document specifically for "Upgrading Plone 4.x to 5.0", but currently this shows only code diffs and other changes and is not procedural, though it claims to be "instructions".

How different are the upgrade procedures between versions v4 and v5? Are there plans to make these upgrade instructions more explicit?

Thanks!

**Comment by deesto** [comment]
Apologies: a referenced issue is marked closed, not this issue itself. My question remains valid, though. Thanks!

**Comment by svx** [comment]
@deesto If you thing what you mentioned is still an issue, please open a new ticket, this issue here is complete different one, and for this it is a bit confusing having your concern mentioned, here :)

Thanks !
