### ISSUE TITLE
docset not found

### ISSUE THREAD

**Issue by svx** [plone/documentation#383]
Zeal and dash are not able to find the latest docset:

http://docs.plone.org/plone5.xml

**Comment by svx** [comment]
Just tested:

works with zeal and with dash

**Comment by polyester** [comment]
could you make a screenshot for https://github.com/plone/documentation/issues/382 ?

**Comment by svx** [comment]
OSX, Ubuntu or both ?

**Comment by polyester** [comment]
both would be great; OSX I don't have but could do Ubuntu later tonight, but if you have both handy that'd be great.

**Comment by svx** [comment]
OK I'll make a zip, Ubuntu is already done, now moving on to OSX

**Comment by svx** [comment]
@polyester there you go:

https://download.leftxs.org/plone/dash-screens.tar.gz
