### ISSUE TITLE
Outdated info about systemd/upstart

### ISSUE THREAD

**Issue by svx** [plone/documentation#385]
http://docs.plone.org/manage/deploying/production/restarts.html

this needs to be updated to best systemd practices and also with a note that upstart and init.d is old practice even if they still work on for example 14.04 ppl not use that like that anymore

**Comment by svx** [comment]
OK what is handy ?

Examples for Ubuntu:

16.x and 14.x -> systemd ? Or should we mention upstart for 14.x

12.x will go away :)

What we should do with Debian, CentOS, etc ?

@polyester ?

**Comment by svx** [comment]
The docs are based since some time on 16.04, still 14.04 is not EOL

## Solution
Rewrite docs in a way that the main focus is on supervisior [since we have that already in the Ansible docs] cron and sytemd.

Drop a line with links to upstart [telling is old, soon gone]

init.d should go.

@polyester @smcmahon do you have comments or suggestions on that ?

**Comment by stevepiercy** [comment]
Superseded by https://github.com/plone/documentation/issues/1327
