### ISSUE TITLE
Needs update: ubuntu-production

### ISSUE THREAD

**Issue by svx** [plone/documentation#387]
http://docs.plone.org/manage/deploying/production/ubuntu_production.html

telling ppl to do dist-uprades on production machines is at least, lets say questionable, there is a difference between apt-upgrade and dist-uprade 

we should take care about that, maybe ppl have reasons to run a certain kernel for example and we do not want to break their setups

upgrade
    upgrade is used to install the newest versions of all packages
    currently installed on the system from the sources enumerated in
    /etc/apt/sources.list. Packages currently installed with new
    versions available are retrieved and upgraded; under no
    circumstances are currently installed packages removed, or packages
    not already installed retrieved and installed. New versions of
    currently installed packages that cannot be upgraded without
    changing the install status of another package will be left at
    their current version. An update must be performed first so that
    apt-get knows that new versions of packages are available.

dist-upgrade
    dist-upgrade in addition to performing the function of upgrade,
    also intelligently handles changing dependencies with new versions
    of packages; apt-get has a "smart" conflict resolution system, and
    it will attempt to upgrade the most important packages at the
    expense of less important ones if necessary. So, dist-upgrade
    command may remove some packages. The /etc/apt/sources.list file
    contains a list of locations from which to retrieve desired package
    files. See also apt_preferences(5) for a mechanism for overriding
    the general settings for individual packages.

**Comment by svx** [comment]
On a further note this document also still refers to: /5.0rc1 !

**Comment by polyester** [comment]
also changed for 4.3 branch now
