### ISSUE TITLE
Fix nginx config of docs.plone.org

### ISSUE THREAD

**Issue by svx** [plone/documentation#389]
With the switch of the docs to Plone 5 as 'master' docs in nginx some ulrs and rewrites broke, for example:

http://docs.plone.org/external/plone.api/docs/api/content.html

is not working

**Comment by polyester** [comment]
see also https://github.com/plone/documentation/issues/353

**Comment by svx** [comment]
I fixed that temp. with redirecting api.plone.org to http://docs.plone.org/develop/plone.api/docs/index.html. Better than nothing at least for the moment. 

But please ppl, things like that should be tested before you switched the docs version in nginx .

And I disagree with the comment in #353, this can be tested and configured before you switch, sorry but I think a little less excitement and doing things too quickly is not always the best way to go.
Yeah I know Plone 5 is great but we still want to have a working setup :)

**Comment by polyester** [comment]
Rewrites in NGINX in place for 
- moving plone.api from /external to /develop, 
- we are pulling in current version of buildout.coredev docs instead of having own outdated version.
