### ISSUE TITLE
tests on travis 

### ISSUE THREAD

**Issue by svx** [plone/documentation#391]
Since the artifacts upload is now disabled why we still use this 'overkill' setup ?

There is no need to build a full Plone for the current setup, 'just' fetching all the docs + external and building without robot is enough and would certainly speed up testing on travis.

Or do I miss something ?

**Comment by polyester** [comment]
I consider the screenshots an integral part of the documentation, and would like to know if a commit breaks building the full docs, incuding them. 

Hopefully in near future phantomjs will be friends with robotframework again, and using http://datakurre.pandala.org/2012/09/speed-up-your-plone-add-on-tests-on.html (but then for 5) speed can be improved.

**Comment by svx** [comment]
But in this case you should make travis really failing and not 'just' give an error and let continue otherwise the whole tests makes no sense 
![failng-robot](https://cloud.githubusercontent.com/assets/358860/10222470/8232b18c-6854-11e5-886f-19eca372d612.png)

As see you 'make html' continues after robot is failing.

**Comment by svx** [comment]
solved
