### ISSUE TITLE
cleanup travis files

### ISSUE THREAD

**Issue by svx** [plone/documentation#392]
atm we have
![travis-files](https://cloud.githubusercontent.com/assets/358860/10221368/44978146-684e-11e5-86d6-bdff5495ddf9.png)

3 different travis files in the repo, this can be confusing, so this should be cleaned up a bit :)

**Comment by svx** [comment]
@polyester would you mind to remove the old ones ? I am asking you because you were afaik the last one working on that ?

If not I will remove the ones called bak and bak.old.

less is more :)

**Comment by polyester** [comment]
closed in https://github.com/plone/documentation/pull/393
