### ISSUE TITLE
Tools for starting developer

### ISSUE THREAD

**Issue by svx** [plone/documentation#4]
Include docs over handy tools, trips and tricks for starting developers, like search plugins, editor configs and testing applications

**Comment by svx** [comment]
include links to #224 and #223

**Comment by svx** [comment]
as above said, we will do that with gists, too, since we have now the setup to include gists into docs.plone.org, this will be nice, hopefully.

**Comment by gforcada** [comment]
What's the benefit of gists over plain normal code blocks on rst docs?

**Comment by svx** [comment]
That it is easier to download or for them, if people want to use for example a config for an editor. ONe pther nice aspect is it, that is is easier for people to contribute, IMHO

**Comment by stevepiercy** [comment]
This issue is obsolete, and maintaining this is beyond our capacity. Each project now includes (or should include) sufficient information for running code quality checks and tests. Closing as won't fix.
