### ISSUE TITLE
Checking alt tags of images

### ISSUE THREAD

**Issue by svx** [plone/documentation#408]
The alt descriptions of pictures needs to be checked, some of them are not really clear, for example on:

http://docs.plone.org/working-with-content/adding-content/adding-images.html

the description of the first image is: Add new-menu.png

And the picture is showing the menu how and how to add an image, this could be possible confusing

**Comment by jogendra** [comment]
Hi @svx Can I take this issue?

**Comment by stevepiercy** [comment]
Closing. We endeavor to require accessibility in all images and now videos in Plone 6 docs.
