### ISSUE TITLE
Varnish 4 - config mistake?

### ISSUE THREAD

**Issue by svx** [plone/documentation#425]
Just came it across during working on varnish 4 configuration tweaks ...

In the docs on: http://docs.plone.org/manage/deploying/caching/varnish4.html under round robin
![varnish_4_possible_error](https://cloud.githubusercontent.com/assets/358860/11090747/d33d0fa6-8874-11e5-8ce1-33bb3404bf4e.png)

We use the names app1 and app2 for the backends, but in the round robin configuration we use:

```
sub vcl_init {
    new cluster1 = directors.round_robin();
    cluster1.add_backend(site1);    # Backend site1 defined above
    cluster1.add_backend(site2);    # Backend site2 defined above
}
```

According to the official varnish docs [https://www.varnish-cache.org/docs/trunk/users-guide/vcl-backends.html] that should be changed to:

```
sub vcl_init {
    new vdir = directors.round_robin();
    vdir.add_backend(app1);
    vdir.add_backend(app2);
}
```

Meaning not site1 and site2 but app1 and app2

@cleberjsantos what do you think ?

**Comment by cleberjsantos** [comment]
@svx Ops!.. Sorry!  Yes +1
