### ISSUE TITLE
write documentation about deploying plone in all the possible ways

### ISSUE THREAD

**Issue by giacomos** [plone/documentation#43]
for ex.:
- saltstack
- ansible
- puppet
- etc..etc..

note: all the examples should be done based on the unified installer

**Comment by svx** [comment]
Hm .... checking the best practices on how we do deploys and installer, I vote for follwong the 'best practices' and stick with what we have which is: unified installer and our ansible kit.

Usually if people use something else like puppet or salt, they know their tool and so they know how to add dependencies and such stuff.

@smcmahon, @polyester what do you think ?

**Comment by polyester** [comment]
In the section on "managing Plone", I agree. Universal Installer, and Ansible. Maybe including Vagrant. But that's it.

In the "Quickstart" though, we should mention the cloud-installers like Bitnami; maybe with a warning that they are externally produced; yet the bitnami one is kept very much up to date for instance.

**Comment by svx** [comment]
@polyester hm I am not sure about that, the idea is that the docs are core stuff and our own installer, further is ther the plan to have a on the new plone.org a new installer/getplone site and on this site we will mention the third party ones like bitnami/plock and all the others.

Reason: bitnami and plock installer are build different and working different there are **not** conform with our docs.

**Comment by djay** [comment]
Not sure if this is the right ticket but looking at the current documetnation there is a need for a guide similar to https://plone.org/documentation/faq/where-can-i-host-my-plone-site which helps questions like
https://community.plone.org/t/need-comments-on-how-to-upload-the-plone-site-to-my-domain-via-ftp/1318.

ie if you don't know the word deploy but do know cpanel or ftp, how to understand your options for getting a plone site on a url? I think this needs to be both in the manual and in the new plone.org. If not in great detail in the manual it should introduce the subject and point at plone.org for your options.

**Comment by stevepiercy** [comment]
Superseded by several trainings, which are updated from time to time or will be archived.
 
- https://training.plone.org/plone-deployment/index.html
- https://training.plone.org/deployment/index.html
- https://training.plone.org/wsgi/index.html
- https://training.plone.org/deployment/opsworks/index.html
