### ISSUE TITLE
can we add an "in this section" checkbox to the search?

### ISSUE THREAD

**Issue by tkimnguyen** [plone/documentation#432]
so if I'm searching for 'gzip' in the Apache docs at http://docs.plone.org/manage/deploying/front-end/apache.html I don't get sent to (say) Diazo docs

**Comment by svx** [comment]
This ticket should be filed under: https://github.com/plone/sphinx.themes.plone ! :)

Unfortunately that is not possible, I mean you can add the check-box, but the built-in search of sphinx which we are currently using is limited, you can define a search area but this is not working properly, at least not deep in subdirs.

There is a long standing open idea to hook up solr or elasticsearch which would give you way better results and also the possibility of filtering but no one had time to work on this yet.

**Comment by tkimnguyen** [comment]
Sorry, I just assume "docs" so this would be where to file the issues, and it's not a theme problem but a functionality issue :) Well heck we should at least just use Plone search!!!

**Comment by svx** [comment]
@tkimnguyen I am sorry but I do not understand this, would you mind to evaluate what you mean by:

"Well heck we should at least just use Plone search!!!"  ?

**Comment by tkimnguyen** [comment]
It was meant to be humorous :) and it could be totally ridiculous but could we not take the generated docs html and css and serve them from a Plone site? Then we would have the search in this section feature.
