### ISSUE TITLE
plone.directives (grok alert?)

### ISSUE THREAD

**Issue by fulv** [plone/documentation#434]
http://docs.plone.org/develop/plone/forms/schemas.html#multi-choice-example

This example does a `from plone.directives import form`, but `plone.directives.form` depends on `five.grok`.

My question:  is `five.grok` (and all the `grokcore` namespace packages) acceptable because it's not the _real Grok_, or did we miss a big chunk of degrokkification?

(See #296)

**Comment by davisagli** [comment]
This needs to be degrokkified.

In this case it's as simple as importing Schema from plone.supermodel.model instead of plone.directives.form

**Comment by fulv** [comment]
What about `form.widget`?

**Comment by fulv** [comment]
I'm guessing `from plone.autoform import directives as form`?
