### ISSUE TITLE
grok-alert for plone.directives

### ISSUE THREAD

**Issue by fulv** [plone/documentation#436]
The following files need fixing, as `plone.directives.form` depends on `five.grok`:
- [ ] develop/addons/schema-driven-forms/further-reading.rst 
- [ ] develop/plone/functionality/controlpanel.rst 
- [ ] develop/addons/schema-driven-forms/intro.rst 
- [ ] develop/addons/schema-driven-forms/form-types/add-forms.rst 
- [ ] develop/addons/schema-driven-forms/form-types/edit-forms.rst 
- [ ] develop/addons/schema-driven-forms/form-types/display-forms.rst 
- [ ] develop/addons/schema-driven-forms/form-types/page-forms.rst 
- [ ] develop/plone/forms/files.rst 
- [ ] develop/addons/schema-driven-forms/form-types/base-forms-and-schema-forms.rst 
- [ ] develop/plone/members/member_basics.rst 
- [ ] develop/addons/schema-driven-forms/customising-form-behaviour/widgets.rst 
- [ ] develop/plone/forms/z3c.form.rst 
- [ ] develop/addons/schema-driven-forms/customising-form-behaviour/vocabularies.rst 
- [ ] develop/addons/schema-driven-forms/customising-form-behaviour/fieldsets.rst 
- [ ] develop/addons/schema-driven-forms/customising-form-presentation/layout-templates.rst 
- [ ] develop/addons/schema-driven-forms/customising-form-behaviour/validation.rst 
- [ ] develop/plone/forms/vocabularies.rst 
- [ ] develop/addons/schema-driven-forms/customising-form-presentation/error-snippets.rst 
- [ ] develop/addons/schema-driven-forms/customising-form-behaviour/actions.rst 
- [ ] develop/plone/forms/schemas.rst 

See #434.

**Comment by staeff** [comment]
I am working to solve the grok-alert for some of the above mentioned pages. Everything that belongs to the schema-driven-forms section. (see also: https://community.plone.org/t/clean-up-documentation-section-schema-driven-forms/2163)

**Comment by stevepiercy** [comment]
This issue is stale, and we now have docs for schema-driven forms https://6.docs.plone.org/backend/schemas.html
