### ISSUE TITLE
Do not fetch README and CHANGES 

### ISSUE THREAD

**Issue by svx** [plone/documentation#443]
This is slightly related to #226 

After spending the last two weeks reading about different ways of documentation and docs setups, I reached the conclusion that we doing it wrong.

Outline:

Usually the 'only' people who benefit from that are developers or integrators, most of the 'normal' user are not interested  or understand  a changelog, at least not in the way how 99% of these are written.

Further on we are not doing 'readme driven documentation' which is a certain way of how to do documentation.
Even further, developers like to integrate fancy buttons from travis or other services into readmes, which is completely fine and cool, because the not only look cool, they also show important and interesting stats and facts about your project.

But these buttons are not really adding an value to your docs in how to use or work on your add-on or project and showing them on docs.plone.org is confusing for user because they do not understand them, they are not nice integrated into the theme and we 'destroy' the consistency of the docs, since the buttons also not unified and lots of people use a different amount and style of them.

So IMHO we would be way better of to have a 'clean' docs directory, with a simple structure like

/docs
   -> /docs/index
   -> /docs/whatever1
   -> /docs/whatever2

In index we just link to the readme and the changelog, so both of them are still easy reachable via for example docs/plone.org/external/foo.

One other nice thing would be that we would be able to fix partly https://github.com/plone/papyrus/issues/78 because with this setup we always get a nice index file

**Comment by polyester** [comment]
I would agree. So steps needed would be:
- [ ] make that clear in the guideline
- [ ] make the mr.bob template do the right thing
- [ ] fix current repositories that put **way** too much info into their README

number 3 will be the most work...

**Comment by svx** [comment]
One other nice plus, it would make sphinx silence because we would get way less warnings:

/home/travis/build/plone/papyrus/source/documentation/develop/addons/bobtemplates.plone/bobtemplates.plone/README.rst:: WARNING: document isn't included in any toctree

/home/travis/build/plone/papyrus/source/documentation/develop/coredev/README.rst:: WARNING: document isn't included in any toctree

/home/travis/build/plone/papyrus/source/documentation/develop/plone.api/README.rst:: WARNING: document isn't included in any toctree

/home/travis/build/plone/papyrus/source/documentation/external/ansible-playbook/README.rst:: WARNING: document isn't included in any toctree

/home/travis/build/plone/papyrus/source/documentation/external/collective.transmogrifier/README.rst:: WARNING: document isn't included in any toctree

/home/travis/build/plone/papyrus/source/documentation/external/collective.transmogrifier/docs/README.rst:: WARNING: document isn't included in any toctree

/home/travis/build/plone/papyrus/source/documentation/external/diazo/README.rst:: WARNING: document isn't included in any toctree

/home/travis/build/plone/papyrus/source/documentation/external/diazo/docs/oldchanges.rst:: WARNING: document isn't included in any toctree

/home/travis/build/plone/papyrus/source/documentation/external/diazo/lib/diazo/tests/allow-curly-brackets/README.rst:: WARNING: document isn't included in any toctree

/home/travis/build/plone/papyrus/source/documentation/external/diazo/lib/diazo/tests/copy/README.rst:: WARNING: document isn't included in any toctree

/home/travis/build/plone/papyrus/source/documentation/external/diazo/lib/diazo/tests/replace/README.rst:: WARNING: document isn't included in any toctree

/home/travis/build/plone/papyrus/source/documentation/external/plone.app.caching/README.rst:: WARNING: document isn't included in any toctree

/home/travis/build/plone/papyrus/source/documentation/external/plone.app.caching/docs/README.rst:: WARNING: document isn't included in any toctree

/home/travis/build/plone/papyrus/source/documentation/external/plone.app.caching/docs/index.rst:: WARNING: document isn't included in any toctree

/home/travis/build/plone/papyrus/source/documentation/external/plone.app.contentlisting/README.rst:: WARNING: document isn't included in any toctree

/home/travis/build/plone/papyrus/source/documentation/external/plone.app.contenttypes/README.rst:: WARNING: document isn't included in any toctree

/home/travis/build/plone/papyrus/source/documentation/external/plone.app.dexterity/README.rst:: WARNING: document isn't included in any toctree

/home/travis/build/plone/papyrus/source/documentation/external/plone.app.event/README.rst:: WARNING: document isn't included in any toctree

/home/travis/build/plone/papyrus/source/documentation/external/plone.app.robotframework/README.rst:: WARNING: document isn't included in any toctree

/home/travis/build/plone/papyrus/source/documentation/external/plone.app.testing/README.rst:: WARNING: document isn't included in any toctree

/home/travis/build/plone/papyrus/source/documentation/external/plone.app.theming/README.rst:: WARNING: document isn't included in any toctree

**Comment by svx** [comment]
I guess nr 3 would be something what I would call `slow work in progress`, lets start with all the new ones followed by all the ones in core, and to do it right, add a test/check to jenkins, if you try to push and the readme is too long or there is no /docs/index with a link to readme and changelog the push will be denied :)

**Comment by svx** [comment]
I fixed that for bobtemplates https://github.com/plone/bobtemplates.plone/pull/133

**Comment by stevepiercy** [comment]
Closing as won't fix.
