### ISSUE TITLE
Inconsistency in @@sharing docs

### ISSUE THREAD

**Issue by zopyx** [plone/documentation#449]
The example uses "Sits Manager" vs. "Sits Coordinator"...should be the same name..but what means "sits"??? Typo and should be "site"?

http://docs.plone.org/develop/plone/security/local_roles.html#adding-a-role-to-the-sharing-tab

**Comment by svx** [comment]
@zopyx thanks for reporting !

PR with fix is on the way

**Comment by svx** [comment]
fixed and done !
