### ISSUE TITLE
URLs of docs.plone.org may become stable

### ISSUE THREAD

**Issue by zopyx** [plone/documentation#450]
You are using these URLs for older Plone docs

http://docs.plone.org/4/
http://docs.plone.org/3

but not for Plone 5.
In case of documentation that might be specific to Plone 5.1 you will break links and bookmarks that go to the Plone 5.0 related documentation.

**Comment by smsubham** [comment]
Hey
I  would like to contribute ? Please help me get started.

**Comment by stevepiercy** [comment]
We now use #.docs.plone.org consistently.
