### ISSUE TITLE
Consistency of documentation versions and URLs

### ISSUE THREAD

**Issue by svx** [plone/documentation#453]
I guess this is also kind of connected to #450 ?

Our usage of versions and URLs in not currently consisted, which may confuse user, for sure new user ...
## Outline

Plone 5
docs.plone.org:
http://docs.plone.org/manage/index.html

Plone 4
http://docs.plone.org/4/en/
http://docs.plone.org/4/en/manage/index.html

Plone 3
http://docs.plone.org/3/en/
http://docs.plone.org/3/en/manage/index.html

We should go with /en or without but having to different ways is confusing

**Comment by stevepiercy** [comment]
Closing in favor of https://github.com/plone/documentation/issues/1140
