### ISSUE TITLE
Plone 4 docs - version switcher order

### ISSUE THREAD

**Issue by svx** [plone/documentation#454]
The order of versions in the switcher is confusing, we should use the same order through all versions, meaning go up:
3,4,5

or down

5,4,3

now we have a mix what is just confusing

**Comment by svx** [comment]
Fixed in https://github.com/plone/papyrus/commit/1060be6427fd2778379557263caecf9aeca77b8e

**Comment by svx** [comment]
The is not working because of the way the version switcher is build - reverted .... great .... :)

**Comment by polyester** [comment]
closed via https://github.com/plone/papyrus/pull/79 (and equivalents for 3 and 5 branches)
