### ISSUE TITLE
Usage of versions

### ISSUE THREAD

**Issue by svx** [plone/documentation#455]
I am sorry to bring that up again [I am ? :)] , but this never got solved properly.

When we came up with the way how we version the docs, we thought that found a good solution, but after working more with docs, talking to lots of other docs ppl from lots of other projects, we should bring that back to the drawing board.

IMHO we should use a schema which is more clear for people, meaning all people and not only developer or people who work with plone since some time.

New user, not always know the versions, so they do not know that 5 is the latest version. 
If you browse to docs.plone.org you will get per default the 'latest stable' but this is only known for people who already work with plone, we just can't assume that this is completely clear for everyone.

I suggest a naming like:

You type docs.plone.org and you get directed to docs.plone.org/latest

This show user immediately that they are on the latest version.

IMHO that is important since we use docs.plone.org for user and dev docs, so the way how the docs are build should also logic for user and not only focused on devs :)

I apologize if developers feel offended now, this is not my intention, I just want to try to get the best for both worlds !

**Comment by polyester** [comment]
I agree we should _carefully_ re-think the URL scheme. Carefully because we will incur a Google hit any way we do it, so better get it really right this time.

Also it needs more study and thought on how to set rel=canonical stuff in the header, otherwise search engines also punish for having multiple URL's leading to the same content. https://en.wikipedia.org/wiki/Canonical_link_element
I'm not quite sure how to set those using sphinx.

Maybe we should make a full "DIP" (Document Improvement Proposal) out of it, and in any case have it looked over by multiple people before deciding.

**Comment by svx** [comment]
rtd is doing that: https://docs.readthedocs.org/en/latest/canonical.html and also pylons: https://github.com/Pylons/pylons_sphinx_theme/pull/8

**Comment by svx** [comment]
OK, this is a reminder, to find time, during the Boston Conference [2016] and brainstorm about that.
Our current setup is bringing up more and more issues :)

As already said above this is something what we should do really carefully, it will have impact on SEO/google/bookmarks but we still have to fix that in one way.

## Challenges

Needs a logic for devs and user:

Our current setup is more focused on devs and less on user, this is getting 'worse' over time and more releases.

We are getting too many versions into the version, switcher, as nice that is for devs as less ideal that is for user, because for them is it confusing, quite often they do not know the difference between 5.0 and 5.1. so for them that is not really helpful, which makes the docs less functional for users.

The versioning is not consistence, I know we decided it that way, but still when we did so we had no experience, having docs for 3.5/4.x/5.0/5.1 is not really that logical and great.

We are getting issues with search, having a schema like: docs.plone.org [landing page], docs.plone.org/latest which is an alias of the latest version this waywe would better for be able to search specific versions and it would make more sense for user.

Taking this further, this is also the approach used by lots of other projects so we can learn and use their experience :)

We have already some other tickets, describing more/other challenges:
- https://github.com/plone/documentation/issues/450
- https://github.com/plone/documentation/issues/453

One other adventure is the versioning of Plone itself, but yeah we can't fix that here :)

Strictly following  semantic versioning as far as I understand it Plone 5.1 should be Plone 6 ?
For docs this would be perfect, since the is quite a difference in the docs between 5.0 and 5.1 :)

Edit1: This also would help with having a nice docs landing page, which would be able to 'guide' user to the different parts of the docs :)

Edit2: Change URL schema

**Comment by stevepiercy** [comment]
Closing in favor of https://github.com/plone/documentation/issues/1140
