### ISSUE TITLE
Should we use apt v1 or apt v2 throuh the docs ?

### ISSUE THREAD

**Issue by svx** [plone/documentation#461]
Since 14.04 there is also apt v2 on Ubuntu, which is the new versions with a nicer ci, faster and shorter.

I want to avoid mixing them in the docs, so personally I use v2 since a long time, but I am never sure which one to use in the docs.

**Comment by gforcada** [comment]
We could avoid it all together by just  saying "install X Y Z" see the official docs of your distribution (and point to some distributions: Ubuntu,  Fedora/RHEL...)

Does that make sense?

**Comment by gforcada** [comment]
Actually, now that I think a bit more on it, we are moving towards ansible, salt, and what not, so they already instrument these low-level tools, so even more of a reason to not talk about one or the other, but just point the package names you want to install...

my 0,2 cents (one for each comment :-)

**Comment by polyester** [comment]
afaik, "apt" is available since Jessie (april 2015) on Debian, and since 14.04 on Ubuntu. I'd say it's safe to use on the 5.0 branch of the docs.

**Comment by stevepiercy** [comment]
Closing as won't fix. It's obsolete.
