### ISSUE TITLE
Add Screenshots?

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/documentation#466]
Just went through the exercise on https://5.docs.plone.org/working-with-content/managing-content/ploneformgen/sql_crud

Under "Inserting Rows" where it has "Connection ID" and "Arguments" (twice), can we add a screenshot? I'm too embarassed to say how much time I just wasted because I misunderstood this line: "On separate lines, specify "string1" and "string2". (Leave off the quotes.)"

A picture is worth a thousand words. I'm happy to add the screenshot but I think they're automatically generated somehow?

**Comment by polyester** [comment]
Since I haven't **quite** mastered the art of "adding a few extra products to the testing fixture in order to do screenshots", having a manual screenshot is much better than nothing, so please go ahead. There's quite a few in this folder already.

Important:
- use PNG as the file format if possible
- filenames without spaces, special chars and such. sql_crud.png would be optimal

**Comment by 3dogMcNeill** [comment]
Great! I will do that. Thanks!

On Wed, Dec 9, 2015 at 11:54 AM, polyester notifications@github.com wrote:

> Since I haven't _quite_ mastered the art of "adding a few extra products
> to the testing fixture in order to do screenshots", having a manual
> screenshot is much better than nothing, so please go ahead. There's quite a
> few in this folder already.
> 
> Important:
> - use PNG as the file format if possible
> - filenames without spaces, special chars and such. sql_crud.png would
>   be optimal
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/plone/documentation/issues/466#issuecomment-163322377
> .

## 

_Christina McNeill_
IRC: cmcneill

**Comment by 3dogMcNeill** [comment]
Just went to try to do this....how the heck do I add an image anyway? I'm
editing through the GitHub web interface. Maybe I should clone the repo and
do it locally, but in what folder should I put the images?

On Wed, Dec 9, 2015 at 4:28 PM, Christina McNeill cmcneill@plone.org
wrote:

> Great! I will do that. Thanks!
> 
> On Wed, Dec 9, 2015 at 11:54 AM, polyester notifications@github.com
> wrote:
> 
> > Since I haven't _quite_ mastered the art of "adding a few extra products
> > to the testing fixture in order to do screenshots", having a manual
> > screenshot is much better than nothing, so please go ahead. There's quite a
> > few in this folder already.
> > 
> > Important:
> > - use PNG as the file format if possible
> > - filenames without spaces, special chars and such. sql_crud.png
> >   would be optimal
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/plone/documentation/issues/466#issuecomment-163322377
> > .
> 
> ## 
> 
> _Christina McNeill_
> IRC: cmcneill

## 

_Christina McNeill_
IRC: cmcneill

**Comment by polyester** [comment]
I'm not 100% on how to do it through the GitHub web interface. When cloning locally, it's a simple "git add mypicture.png". 

As for folders: just put in the same one as the .rst file is in, that's the easiest to keep track of.

**Comment by polyester** [comment]
ah, there is that suspicious 'new file' button on the webinterface; so through the web should be: 
- create branch
- hit the "new file" button on the correct directory
- and this would be a good test of how easy the GitHub webinterface is from there ;-)

**Comment by 3dogMcNeill** [comment]
Ok, I have literally spent 4 hours trying to add 4 screenshots and make
some clarification edits. I cloned the repo locally, I tried using GitHub
Desktop—couldn't figure out how to make commits to 4.3 branch through
command line; with Desktop, ended up making PR to master when I thought I
was pushing to "my" local version—it didn't work, I can't find the files I
added or the ones I changed, so I quit.

This is way too hard! And I REALLY want to help make the documentation
better! Here's the thing: I'm not a programmer, I never will be, and I
refuse to become one in order to make writing changes.

On Fri, Dec 18, 2015 at 5:18 PM, polyester notifications@github.com wrote:

> ah, there is that suspicious 'new file' button on the webinterface; so
> through the web should be:
> - create branch
> - hit the "new file" button on the correct directory
> - and this would be a good test of how easy the GitHub webinterface is
>   from there ;-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/plone/documentation/issues/466#issuecomment-165909924
> .

## 

_Christina McNeill_
IRC: cmcneill

**Comment by 3dogMcNeill** [comment]
And also, screenshots can't be added through the web.

On Mon, Dec 21, 2015 at 11:58 AM, Christina McNeill cmcneill@plone.org
wrote:

> Ok, I have literally spent 4 hours trying to add 4 screenshots and make
> some clarification edits. I cloned the repo locally, I tried using GitHub
> Desktop—couldn't figure out how to make commits to 4.3 branch through
> command line; with Desktop, ended up making PR to master when I thought I
> was pushing to "my" local version—it didn't work, I can't find the files I
> added and changed so I quit.
> 
> This is way too hard! And I REALLY want to help make the documentation
> better! Here's the thing: I'm not a programmer, I never will be, and I
> refuse to become one in order to make writing changes.
> 
> On Fri, Dec 18, 2015 at 5:18 PM, polyester notifications@github.com
> wrote:
> 
> > ah, there is that suspicious 'new file' button on the webinterface; so
> > through the web should be:
> > - create branch
> > - hit the "new file" button on the correct directory
> > - and this would be a good test of how easy the GitHub webinterface
> >   is from there ;-)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/plone/documentation/issues/466#issuecomment-165909924
> > .
> 
> ## 
> 
> _Christina McNeill_
> IRC: cmcneill

## 

_Christina McNeill_
IRC: cmcneill

**Comment by polyester** [comment]
I'm sorry; that is something we will have to improve then. (also for safety; you deleted the whole 4.3 branch in the process. Easily enough to restore, but that means the process is not well enough documented)

If you could do the following, I will try to make it into a much better non-programmer guideline:
- send me (old-school, by email) the updated .rst files, and the screenshots)

again, sorry for the timeloss, but let's see if we can turn this around positively by creating a clearer step-by-step guide, using these edits as example.

**Comment by polyester** [comment]
ah, found them already. 
https://github.com/plone/documentation/commit/aeaed22b874ace77f3c8bb529ff455a3226bb6d8 and
https://github.com/plone/documentation/commit/e3eda04ab10eab3d881c1e9e661adb37ea41816b, so to see.

I'll work from there

**Comment by 3dogMcNeill** [comment]
omg, I did?! yikes. sorry. 

After I made the PR, I wasn't sure how to stop it from being added so I closed it. I thought that was closing my PR, not deleting the whole branch.

**Comment by polyester** [comment]
no problem, it shows we need better documentation ;-)

I'll have to find a computer where I can install github-desktop, then make some screenshots using that.

**Comment by stevepiercy** [comment]
Closing as won't fix for Plone 5.
