### ISSUE TITLE
Add documentation/about to docs.plone.org

### ISSUE THREAD

**Issue by thet** [plone/documentation#467]
Why isn't the about section included in docs.plone.org? I find it very useful, especially to reference the styleguide here: https://github.com/plone/documentation/blob/5.0/about/documentation_styleguide.rst

**Comment by polyester** [comment]
not quite sure what you mean; http://docs.plone.org/about/index.html is included directly from the main page.

**Comment by thet** [comment]
Absolutely `True`. Did oversee this. Maybe it was too late yesterday...
