### ISSUE TITLE
Add Plone and JavaScript style guides

### ISSUE THREAD

**Issue by thet** [plone/documentation#469]
I thought this was already done, but apparently not.

We need our styleguide referenced in "Developing for Plone" main section:
- https://github.com/plone/plone.api/blob/master/docs/contribute/conventions.rst
- http://patternslib.com/pattern-styleguide/#main-content
- And a internal reference to https://github.com/plone/documentation/blob/5.0/about/documentation_styleguide.rst (related to #467)

/cc @plone/framework-team for approving the plone.api styleguide as our official styleguide. This involves moving the styleguide out of there into ... buildout.coredev/docs? or somewhere else?

**Comment by jensens** [comment]
I think we already approved the plone.api styleguide as offical at some point.

**Comment by jcbrand** [comment]
@thet I added the Javascript styleguide here: https://github.com/plone/documentation/commit/b1b973c4234bde0f4c6c4b31327cd2fabc03dd73

It's still in the "styleguides" branch of plone.documentation. I remember discussing this with @polyester somewhere on a ticket, but I don't find that discussion anymore. You were also involved in that ticket, can you remember which one it might be?

**Comment by polyester** [comment]
@jcbrand I think it just somehow never made it to pullrequest; it should be a PR I think. Looks good, I'll merge when it's there.

**Comment by thet** [comment]
@jcbrand tnx!

**Comment by jcbrand** [comment]
Oh, I just made the pull request @thet, but you're welcome to close it and create a new one after.

https://github.com/plone/documentation/pull/471

**Comment by thet** [comment]
np, rewrote history and deleted the comment :)

**Comment by thet** [comment]
awesome, even the python styleguide is in place.

@polyester there is some more valuable information in https://github.com/plone/plone.api/blob/master/docs/contribute/conventions.rst - especially the git workflow and release process chapters. they do not really fit into the styleguide, though. i'll create a new section for this and do a pull request, ok?

**Comment by thet** [comment]
Done in https://github.com/plone/buildout.coredev/pull/149
