### ISSUE TITLE
Reduce nesting in "Developing for Plone"

### ISSUE THREAD

**Issue by thet** [plone/documentation#470]
Looks like there is some unnecessary nesting in http://docs.plone.org/develop/index.html
I guess this has something to do with how external docs are included. The nesting looks awkward - some menu items have only one submenu item with the same title. In case of "Developing for Plone Core" there is even no table of contents.
It would look much nicer and cleaner, if we can get over some limitation and try to restructure and fix this.

**Comment by polyester** [comment]
That's related to https://github.com/plone/documentation/issues/443

Each externally-fetched repo has a wildly different way of structuring their docs section, making it hard to create a uniform nesting-depth here. This will have to be fixed in the external repos, ideally.

**Comment by polyester** [comment]
closed via https://github.com/plone/documentation/pull/583
