### ISSUE TITLE
Correct well known names

### ISSUE THREAD

**Issue by thet** [plone/documentation#475]
Some names are not not written correctly consistently:
- GitHub should be written in CamelCase: https://en.wikipedia.org/wiki/GitHub
- JavaScript should be written in CamelCase: https://en.wikipedia.org/wiki/JavaScript

... there are possibly more, but those two are the ones I recognized until now.

**Comment by svx** [comment]
Since we also use github [like in urls] I suggest we keep and check for GitHub and github, maybe we can even write a test which is smart enough to detect the difference between a url and a non-url

**Comment by svx** [comment]
@thet can I close this ? I think so, right, it got fixed, maybe not on all places yet, but on lots of them :)

**Comment by thet** [comment]
Sure! Thanks for keeping an eye on this. I'll close so you don't have to.
