### ISSUE TITLE
Nginx Config Example for PHP

### ISSUE THREAD

**Issue by l34marr** [plone/documentation#485]
This link http://alasdoo.com/2010/12/xdv-plone-and-phpbb-under-one-nginx-roof/ described at http://docs.plone.org/manage/deploying/front-end/nginx.html#php-with-nginx-and-php-fpm seems unreachable. Any other good references or consider a rewrite?

**Comment by svx** [comment]
Do we really want to keep that in our docs anyway ? I mean it is not about running Plone with Nginx it is about setting up Nginx with PHP ....

If we want to keep that I would suggest that we link to the official Nginx documentation :)

**Comment by smcmahon** [comment]
+1 for getting rid of it. PHP on nginx is a speciality unto itself. We don't want to maintain that kind of documentation, or even links to it.
