### ISSUE TITLE
Remove mention of PIL update install docs

### ISSUE THREAD

**Issue by svx** [plone/documentation#491]
Should we update: http://docs.plone.org/develop/plone/images/ ?
- removing PIL
- update Pillow docs, mention about installation of certain packages: libjpeg62-dev libfreetype6 [Ubuntu] and libjpeg-turbo-devel freetype-devel [Fedora/CentOS]

We already have  libjpeg62-dev mentioned in: http://docs.plone.org/manage/installing/installation, should we update that with libfreetype6, too ?

**Comment by polyester** [comment]
+1 on removing PIL, I would probably suggest having the install instruction on Pillow relatively simple (although including libfreetype6 might be a candidate) and have it point to https://pillow.readthedocs.org/en/latest/installation.html for all the details, which is quite up to date, with specific instructions for various operating systems.

**Comment by svx** [comment]
Please review https://github.com/plone/documentation/tree/fix_%23491
- rename pil to pillow
- update pillow.rst
- update installation.rst with mention about pillow dependencies
- update requirements with note about pillow dependencies

The wording is not perfect yet, but IMHO it fixes the confusion and also makes clear [ I hope] that the user may need to install some dependencies for pillow which are not dependencies for plone itself.
@polyester, @smcmahon, @do3cc please review and tell if that is OK, please do not merge immediately, I want to make sure that we do it right this time :)

**Comment by smcmahon** [comment]
How about these edits to the particular sections of pillow.rst:

Plone uses Pillow, a fork of the Python Imaging Library (PIL) for low-level image manipulation and decoding, particularly for GIF, JPEG and PNG image formats.

...

# Installing Pillow

For instructions how to install Pillow and its dependencies, please read:

https://pillow.readthedocs.org/en/latest/installation.html

Note particularly the dependencies on the development packages of libjpeg and libz. Other image format support may be required for special projects, but libjpeg and libz are required for GIF, JPEG and PNG support.

**Comment by svx** [comment]
Awesome, will fix that later tonight ! Thanks a lot !

**Comment by svx** [comment]
Done !
