### ISSUE TITLE
[Guideline] : setup.py -> README vs /docs

### ISSUE THREAD

**Issue by svx** [plone/documentation#492]
How we want to handle this ?

What do I mean:

As you can see in the repo of plone.versioncheck [https://github.com/plone/plone.versioncheck], the setup.py fetches the README

```
long_description = '{0}\n\n{1}'.format(
    open('README.rst').read(),
    open('CHANGES.rst').read()
)
```

I do see the point, because this is nice for pypi, but this creates the issue that this approach is not following our 'best practices', I do not have a /docs dir, and so all my CI tests for documentation are failing and yelling at me :)

Further on, README driven documentation will get harder as longer the README will get :)

This is btw, not meant to criticise this awesome application nor the developers, we do have this with lots of other repositories too, it just I came this now across because of my angry CI :)

**Comment by polyester** [comment]
Maybe you can clarify, I do not understand exactly. Our guidelines https://github.com/plone/documentation/blob/5.0/about/documentation_styleguide.rst do specify to have a short README.rst and a CHANGES.rst in the top level, and have the full docs in /docs.

**Comment by svx** [comment]
Yes, if you check https://github.com/plone/plone.versioncheck, you will see a README and a Changes but you do not see a /docs directory.
Following our best practices I run CI checks and check if a repo contains a /docs, if not CI yells at me :)

At the moment the README is not a README followin our best practices of how a README should look like, it is currently used as place for the whole documentation, which is what is called readme driven documentation.
This README is used in setup.py, meaning if you upload to pypi, you will have all the docs on the pypi page, which is nice.

One easy solution would be to move all this into /docs as plain rst, [no sphinx, just rst] and adjust the README.

**Comment by polyester** [comment]
ah, it's about the docs (or lack of /docs) of the **package** plone.versioncheck itself, not about how it works to pull in other packages. I didn't quite get why this ticket is in our repo.

Well, then the idea generally is:
- docs of plone.versioncheck have to be changed before they can be pulled into the Plone docs. 
- file an 'enhancement' ticket in https://github.com/plone/plone.versioncheck/issues (or do a  pull request if you have spare time)

**Comment by svx** [comment]
@jensens would you mind if I try to change that and send you a PR for review ?

@polyester it is not only about pulling in this package to docs.plone.org it is also about repository layout and CI, I am busy with setting up CI for documentation checks in repositories according to our best practices.

**Comment by polyester** [comment]
@svx you should probably have it send out messages with "nobody expects the Spanish CI" as header, that fits nicely in the Python style  ;-)

**Comment by stevepiercy** [comment]
Closing as won't fix.
