### ISSUE TITLE
mention how to install libfreetype on various OS

### ISSUE THREAD

**Issue by polyester** [plone/documentation#495]
with https://github.com/plone/documentation/pull/494 and https://github.com/plone/documentation/pull/493 we mention freetype (which in turn is requisite for Pillow). The OS-level instructions are Ubuntu/Debian specific, for the moment. 

If feasible, we should mention other OS's, although https://pillow.readthedocs.org/en/latest/installation.html does not mention installing freetype on OSX is necessary. 
Another option is to point to the pillow-docs for all other OS's except Debian/Ubuntu for now.

**Comment by svx** [comment]
fixed with #502
