### ISSUE TITLE
How to setup proper testing for development

### ISSUE THREAD

**Issue by svx** [plone/documentation#5]
How to create a working testing setup for development and how to use it, like travis, jenkins and so on

**Comment by svx** [comment]
Should we include:

https://plonetrainingtesting.readthedocs.org/en/latest/ ?

@tisto would you mind to have a look at http://docs.plone.org/external/plone.app.testing/docs/source/index.html, is that still valid ?

**Comment by stevepiercy** [comment]
Closing as won't fix. Each project now includes (or should include) its own specifications for code quality checks and how to run tests.
