### ISSUE TITLE
Change the way of testing

### ISSUE THREAD

**Issue by svx** [plone/documentation#504]
The way how we test documentation local or with travis should be improved :) 
IMHO our current way of doing tests could see some changes.
- tests still take too long
- split them into smaller ones to be more flexible

This gives the advantage that we would be able to run
'micro-tests' on latest commit see: https://github.com/plone/papyrus/issues/86

Currently is is a pain to do link and spell check in a sane way, because it is hard to write good tests for this issues, because we still have too many not working links or typos, for example.

We only need to run robot-tests if we have changes on images, so we do not need that all the time, further on I do not see the point of building a whole Plone setup, just to be able to run spell checks, sure we do need that for robots and final testing for a new release, but most of the time this is just overkill :)

I propose 'micro testing' do it often and do it fast !

One possible solution:

Change mr.docs in that way that he can detect all files not only files under /docs [make him more flexible], with that we can use him, for fast testing on travis and local, for te begin we could run spell and link checks at least on every commit, and since we just testing the last commit, this only literary takes a couple of settings, well if you run it on travis a bit longer, since travis is always slow :)

**Comment by svx** [comment]
List of tests:
[some of them we already have]
- check links
- check that we do not use 'here or click here' in/for links
- check typos
- check 'code-examples' how ?
- check 'OS package examples' how ?
- check file age
- check /docs
- check README
- check 'length of intro'
- check 'length of document' 
- ....

**Comment by svx** [comment]
more info here: https://github.com/plone/papyrus/issues/86

**Comment by stevepiercy** [comment]
In Plone 6, we now have https://6.docs.plone.org/contributing/setup-build.html

For Plone 5, this will not be implemented.
