### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by gforcada** [plone/documentation#514]
Looking at [content rules docs](http://docs.plone.org/develop/plone/content/content_rules.html) I came across these two links which are dead (at least ask for log in):

https://plone.org/acl_users/credentials_cookie_auth/require_login?came_from=https://plone.org/documentation/kb-old/creating-content-rule-conditions-and-actions

https://plone.org/acl_users/credentials_cookie_auth/require_login?came_from=https://plone.org/documentation/kb-old/content-rules

Are they still around and can be more or less copy&pasted so their content is not lost?

**Comment by polyester** [comment]
the user manual should go, that's at http://docs.plone.org/working-with-content/managing-content/contentrules.html now. 

The developer manual was heavily outdated, is based on Plone 3, and says "Last modified: 2554 days ago" (!!!). So both links should go, and there may be a need for someone to write a manual on how to code content rules.

**Comment by flipmcf** [comment]
Just updating what I see, when I see it.
