### ISSUE TITLE
Update introduction video in plone.app.theming manual 

### ISSUE THREAD

**Issue by vikas-parashar** [plone/documentation#517]
In [plone.app.theming manual](http://docs.plone.org/external/plone.app.theming/docs/#introduction) the [introduction video](https://vimeo.com/42564510) provided uses Plone 4.3 and was uploaded 3 years ago. It should be updated with new introductory video using Plone 5.

![image](https://cloud.githubusercontent.com/assets/5694967/12887713/3fc45e5a-ce9c-11e5-9485-f6707758446b.png)
_(screenshot of video uploaded on vimeo)_

**Comment by svx** [comment]
This should be filed under plone.app.theming, since we 'fetch' the docs from there.

I opened a ticket there: https://github.com/plone/plone.app.theming/issues/99

**Comment by svx** [comment]
Since this issue is open the plone.app.theming repo, I will close it here.
