### ISSUE TITLE
Best practices for upgradeSteps incremental numbering?

### ISSUE THREAD

**Issue by idgserpro** [plone/documentation#519]
We're missing a "recomendation" or "best practices" section of how to give version numbers to upgradeSteps in packages. For the package itself we have [PEP 0440](https://www.python.org/dev/peps/pep-0440/) or even [semver](http://semver.org/) but not something similar when we're talking about upgradeSteps.

@mauritsvanrees do you know if there's some kind of "informal specification" for this versioning numbering in GenericSetup itself?

**Comment by mauritsvanrees** [comment]
There used to be alphabetical sorting, which meant this order: 1, 10, 11, 2, 3, etc. You want numerical sorting here, which I think is correctly done currently. As far as I know, versions with dots work fine too.

In practice, this is what I do:
- start with 1000. This avoids problems with ancient GS that used alphabetical sorting.
- just add 1 each time you need a new metadata version.
- if your package version number changes, but your profile stays the same and no upgrade step is needed, you should not change the metadata version.
- if you make changes for a new major release, you should increase the metadata version significantly. This leaves room for small metadata version increases on a maintenance branch. Example. You have branch master with version 1025. You make backwards incompatible changes and you up the version to 2000. You create a maintenance branch where the next version will be 1026.

**Comment by idgserpro** [comment]
Thanks @hvelarde for the insight and @mauritsvanrees for the explanation. The "start with 1000" is consistent as well with [bobtemplates](https://github.com/plone/bobtemplates.plone/blob/158a286f2a1078e33d4891d9b4cdf082d68e77c1/bobtemplates/plone_addon/src/%2Bpackage.namespace%2B/%2Bpackage.name%2B/profiles/default/metadata.xml.bob).

@davilima6 pointed out your PR at https://github.com/plone/documentation/pull/520 and this explanation you just gave above would be really nice to have, with a small note saying that specially with old legacy packages, this definition may not be present, but it's important for new packages. Then, this issue can be closed.

**Comment by mauritsvanrees** [comment]
Done on that pull request in https://github.com/plone/documentation/commit/953417a1badc5aa8c1a217164a884559b6fe0293

**Comment by idgserpro** [comment]
Thanks @mauritsvanrees. Now I remember some really old links about this subject like http://plone.org/documentation/kb/version-numbers-in-cmfquickinstaller and https://www.mail-archive.com/zopeskel%40lists.plone.org/msg00111.html
