### ISSUE TITLE
Styling on guilabel is not clear on website

### ISSUE THREAD

**Issue by neilferreira** [plone/documentation#521]
I was reading http://docs.plone.org/develop/plone/content/dynamic_views.html#permission-for-changing-the-view-template-of-an-item and it was unclear that "Modify view template" is the permission need to achieve this.  Figured that quoting this would make it clearer in the documentation and noticed that it looks like this in the source:

```
A user needs the :guilabel:`Modify view template` permission to use the
dynamic view dropdown.
```

Is there meant to be styling applied to this? Is there any way we can make it clearer?

**Comment by svx** [comment]
:guilabel: should style it, if that is not working, then we have to check why it is not, could be wrong syntax or css related

**Comment by svx** [comment]
This is fixed now, but we should style it a bit better
![modify_view](https://cloud.githubusercontent.com/assets/358860/14281358/df3f5462-fb38-11e5-963d-9dc915901bf8.png)

@polyester any ideas ? Change the background or something else ?

**Comment by polyester** [comment]
Yes, added pull request to add light yellow background
