### ISSUE TITLE
purge="false" in http://docs.plone.org/adapt-and-extend/theming/resourceregistry.html#bundle-definition

### ISSUE THREAD

**Issue by zopyx** [plone/documentation#525]
there is 

`purge="false"`

used here:

http://docs.plone.org/adapt-and-extend/theming/resourceregistry.html#bundle-definition

I think this should `False`

**Comment by cewing** [comment]
@zopyx if that's an error, then its an error in the source code.  The [`registry.xml`](https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/profiles/dependencies/registry.xml#L1112-L1123) file in the `dependencies` profile in Products.CMFPlone contains that code (it's a direct copy of the original from the time when that doc was written).  I've got the same basic reference in my [PR updating that documentation](https://github.com/plone/documentation/pull/518).

If it's a bug in the original code, that'd be good to know.

**Comment by zopyx** [comment]
Boolean values in GS related files are True|False as  in

http://docs.plone.org/develop/addons/components/genericsetup.html

So this looks like a typo to me.

2016-02-17 19:48 GMT+01:00 Cris Ewing notifications@github.com:

**Comment by cewing** [comment]
@zopyx I wonder then if it's actually a bug in that documentation.  The reason I ask is that grepping through the Plone coredev buildout code, there are 27 instances of `purge="false"` and 29 of `purge="False"` in xml files in profiles.  

If it is in fact case sensitive in GenericSetup then we have a bunch of bugs here.

If it's not case sensitive, then the docs should either reflect that, or should state that using uppercase is "Best Practice" or "convention" or something like that.

Either way, some clarification seems in order.

**Comment by zopyx** [comment]
I think I am wrong. From the GS code:

   def _convertToBoolean(self, val):
        return val.lower() in ('true', 'yes', '1')$

Never seen configurations using 'yes' or '1' as boolean values...well, I
think the issue can be closed.
