### ISSUE TITLE
Bundle info about demo sites an/or different installation procedures 

### ISSUE THREAD

**Issue by svx** [plone/documentation#527]
Currently the info about these is spread about different places in  the docs
- quickstart
- installation

and some other places, this makes it really hard to maintain them and also keep an overview what we have or not have documented already !

Solution:
- one place where we have them
- if necessary link to the documents

There is a different between a 'demo site' where you can browse to and just start trying and stuff like plan9, docker, heroku, where you first have to do some actions, like downloading, installing or so on.

We should try to clarify that in our the docs, because of the user point of view that is a difference, telling a 'less technical' person, just browse to demo.plone.org and try it out is different from telling `just install application x and now download the installer` or something like that.

**Comment by cewing** [comment]
I think that for the sake of maintainability we should push toward putting all documentation of single topics into a single location, and then linking to that location from other places where the information would help.

One other thing.  Can we try over time to remove uses of the word "just"?  It's a word that carries the meaning that what you are discussing is trivial, simple, easy.  And if the reader is having trouble with the concept, using it can make them feel like they are stupid or missing something. I'd love it if we can move away from letting that happen.

**Comment by svx** [comment]
@cewing yes that is exactly my idea !

+1 on 'just' too !

**Comment by svx** [comment]
'Just' checked, and we should/could remove/update/change it on at least 380 places :)

**Comment by stevepiercy** [comment]
Closing as complete. https://6.docs.plone.org/install/index.html
