### ISSUE TITLE
isort version requirement.

### ISSUE THREAD

**Issue by jochumdev** [plone/documentation#530]
I've been searching for over an hour until i found out that [these](https://github.com/plone/documentation/blob/5.0/develop/styleguide/python.rst#grouping-and-sorting) settings only work with a recent version of isort.

My systems isort is 3.9.2 while pip gives 4.2.2.

Is that something other people need, can someone add this?

**Comment by gforcada** [comment]
As a matter of reference [these](https://github.com/plone/buildout.coredev/blob/5.0/experimental/qa.cfg) are the exact pins used by jenkins to report about code analysis errors on already cleaned up packages.

**Comment by svx** [comment]
Is it an idea to rewrite this whole part in a different way ? I am asking this because where possible I want to get rid of putting certain/exact version in the docs, versions will change/update and so stuff like this will keep us busy with updating/fixing versions of certain software pieces in the docs, we should avoid that where we can :)

**Comment by gforcada** [comment]
@svx that's why I referenced to an external file that will be always the reference, as it's the one used by jenkins and reported to developers. So, usually 100% accurate on its version pins.

**Comment by svx** [comment]
@gforcada yes, but the docs mention two things:
- isort 
- _You can also use plone.recipe.codeanalysis with the flake8-isort plugin enabled to check for it._

I would like to change that, if possible because this could be confusing, IMHO it is easier at least for new ppl to mention one tool, with wordings like _you can also use X_ you make it harder, also for support and help, so question:
Which of the both is **best practices** to use ?

**Comment by gforcada** [comment]
@svx well actually both :-)

plone.recipe.codeanalysis does a full analysis of your source code, not only python, and although isort (for import sorting) is used you still have to install it separately to be able to use it as a command line script

But we could simplify it by saying: _plone.recipe.codeanalysis is the one-stop-tool for any QA needs, see its documentation for further details_

Does that sound better?

**Comment by svx** [comment]
yes ! :)

**Comment by svx** [comment]
@gforcada Do we really want to point to a configuration from _experimental_ ?

What I try to say it, that this maybe not the best idea in terms of docs/communication/marketing ?

@polyester do you have an opinion on that, I mean sure we do use them with our _own stuff_ but if possible I would like to avoid to mention links with experimental_  :)

**Comment by polyester** [comment]
"one obvious way to do it" always wins. And laziness.

So, would it be possible and/or a good idea to have a repo with 'dev best practices dotfiles' which people can just git-pull to stay up to date? 
And indeed, have that not be called /experimental but /bestpractices is surely better in terms of marketing...

**Comment by gforcada** [comment]
experimental was the only folder in buildout.coredev that was more or less good enough for that configuration purpose, still, that cfg file could be reduced to something like:

```
[buildout]
parts = code-analysis

[code-analysis]
recipe = plone.recipe.codeanalysis
multiprocessing = True
check-manifest = True
clean-lines = True
directory = src # adjust accordingly
```

@polyester as for a _dev best practices dotfiles_ that should be [bobtemplates.plone](https://github.com/plone/bobtemplates.plone) which already has a `code-analysis` section in its [buildout.cfg](https://github.com/plone/bobtemplates.plone/blob/master/bobtemplates/plone_addon/buildout.cfg.bob) although it needs some updates.

So we could point to the one in bobtemplates.plone actually.

The one in experimental is for core Plone packages (where we can not turn on flake8-plone-api).

**Comment by svx** [comment]
So coming back to these, that would mean we have to maintain two different versions of the docs, one for code-development and one for development/using bob.templates ?

**Comment by gforcada** [comment]
@svx I'm lost with your last comment, the original question was about how to install isort, and on comment https://github.com/plone/documentation/issues/530#issuecomment-187637211 I suggest to rephrase the isort mention with _plone.recipe.codeanalysis is the one-stop-tool for any QA needs, see its documentation for further details_.

So if anyone is wondering about isort versions (or any other tool mentioned on the code style guide) they should check plone.recipe.codeanalysis.

**Comment by jochumdev** [comment]
closing this, question was answered by @gforcada
