### ISSUE TITLE
Fix link for fixing a Plone 3.1 buildout and little improvements

### ISSUE THREAD

**Issue by idgserpro** [plone/documentation#532]
The link http://www.netsight.co.uk/blog/resurrecting-old-plone-3-buildouts in http://docs.plone.org/manage/troubleshooting/buildout.html#plone-3-1 is broken. You can only find it in archive.org, in fact, at https://web.archive.org/web/20150308151931/http://www.netsight.co.uk/blog/resurrecting-old-plone-3-buildouts.

When you go there, you have an option to go to https://plone.org/documentation/kb-old/repair-a-plone-3.1-buildout (but asks for login) and http://developer.plone.org/troubleshooting/buildout.html - that doesn't redirect to http://docs.plone.org/manage/troubleshooting/buildout.html but at least is the same structure.

How can we improve this section? Can we have what was in https://plone.org/documentation/kb-old/repair-a-plone-3.1-buildout here at docs.plone.org? In Plone 3 documentation branch there's a little more info in http://docs.plone.org/3/en/manage/troubleshooting/buildout.html#plone-3-1 and I think a small paragraph saying "if you're unsure about pinning, download Plone Unified Installer in https://plone.org/products/plone/releases/3.1.7 since it has a correct buildout cache fot it's needed packages" would be a nice touch to have.

Somewhat related: 
https://stackoverflow.com/questions/29261927/looking-for-buildout-cfg-for-old-version-of-plone-pre-3-2
http://lists.plone.org/pipermail/plone-product-developers/2010-February/009662.html
http://product-developers.narkive.com/AEXFnB95/versions-cfg-for-plone-3-1-6-7
http://maurits.vanrees.org/weblog/archive/2010/04/nonewplone

**Comment by svx** [comment]
Would it an idea to get rid of that in the Plone 5 docs at all ?

Troubleshooting buildout is important to have, but can we have that version independent where we can ?

We should fix that for docs.plone.org/3 and maybe update the section in docs.plone.org [currently 5] to be up to date ?

Maybe we can rewrite it that we do not need to pin it to certain version, I mean where that is possible.

**Comment by idgserpro** [comment]
If you think it's better to remove it from Plone 5 and leave at Plone 3 branch, that's fine. It's nice to be version independent but sometimes that's not possible, in the case of Plone 3.1, since it wasn't fully eggfied, so we have some rough edges and that's why we posted these specific links.

We didn't do a PR for your approval since we can't yet have a contributor's agreement, that's why this is opened as an issue.

**Comment by stevepiercy** [comment]
Closing as won't fix for Plone 5.
