### ISSUE TITLE
Bypassing language check seems wrong

### ISSUE THREAD

**Issue by djowett** [plone/documentation#537]
From https://github.com/plone/documentation/blob/5.0/develop/plone/searching_and_indexing/query.rst#bypassing-language-check 

> All portal_catalog() queries are limited to the selected language of the current user. You need to explicitly bypass the language check if you want to do multilingual queries.
> 
> Example of how to bypass language check:
> 
> all_content_brains = portal_catalog(Language="")

This seems wrong with Plone.app.multilingual, perhaps its true with LinguaPlone?  From my experiment below, `catalog.searchResults({'Language': ''})` just shows you content with no language set.  You'll have to take my word on that of, but you _can_ see that a catalog search with no parameters returns ALL content in the site (the 3 languages below are the only ones enabled).

```
(Pdb) len(catalog.searchResults({'Language': ''}))
30
(Pdb) len(catalog.searchResults({'Language': 'en'}))
107
(Pdb) len(catalog.searchResults({'Language': 'de'}))
17
(Pdb) len(catalog.searchResults({'Language': 'pt'}))
4
(Pdb) len(catalog.searchResults())
158
(Pdb) 
```

What DO we want to say here?

**Comment by djowett** [comment]
For the record this experiment was on Plone 4.3 / Plone.app.multilingual 2.x

**Comment by jensens** [comment]
On Plone 5 this does not work at all, because the LinguaPlone catalog patch is not there anymore, also not if PAM is activated.

In Plone 5 a LanguageRootFolder is also an `INavigationRoot`. So `plone.app.querystring` already fixates all this to the current `INavigationRoot` if no other `path` is given. Not sure how this is handled in sitemap, search et al. At least either `Language='all'` nor `Language=''` has any positive effect on the search. It moreover results in an empty result.

**Comment by djowett** [comment]
IIUC  the way to do this in Plone 5 (assuming you've not installed LinguaPlone somehow!) is just to specify `path='/'`.  In comparision `Language='all' will give 0 results, whereas `Language=''` will give you content with no language set - not usually what you want.

**Comment by erral** [comment]
That's right, the Language='all' is needed in LP and PAM 1.x

https://github.com/plone/Products.LinguaPlone/blob/master/Products/LinguaPlone/patches.py#L30

https://github.com/plone/plone.app.multilingual/blob/1.x/src/plone/app/multilingual/catalog.py#L26

Although the language folders are also marked to be INavigationRoot, in LP the language of the content is not enforced inside the language folder (in PAM there's a subscriber that moves the content to the appropriate folder)
