### ISSUE TITLE
styleguide best pratices 

### ISSUE THREAD

**Issue by svx** [plone/documentation#541]
Situation - example

apt-get install

currently we mix different code-blocks for that in the docs, we use

```
.. code-block:: console
```

```
.. code-block:: bash
```

```
.. code-block:: shell
```

according to the lexer docs:

```
Lexers for various shells

class pygments.lexers.shell.BashLexer
Short names:    bash, sh, ksh, shell
Filenames:  *.sh, *.ksh, *.bash, *.ebuild, *.eclass, *.exheres-0, *.exlib, .bashrc, bashrc, .bash\*, bash\*, PKGBUILD
MIME types: application/x-sh, application/x-shellscript
Lexer for (ba|k|)sh shell scripts.

New in version 0.6.

class pygments.lexers.shell.BashSessionLexer
Short names:    console, shell-session
Filenames:  *.sh-session, *.shell-session
MIME types: application/x-shell-session, application/x-sh-session
Lexer for simplistic shell sessions.
```

should we settle on console or bash ?

**Comment by polyester** [comment]
before we get accused of 'bashism', let's pick the most general. So either console or shell would get my vote, not sure what is the most easy term for beginner-users. Linux users tend to call it 'shell', not sure what the most used term for Windows and OSX is. 
Either way, +1 on picking one.

**Comment by svx** [comment]
Already I will make a PR with a updated version of our style-guide

**Comment by svx** [comment]
Done with: https://github.com/plone/documentation/commit/897afa58daa4a807b9860ee532b8c3cdb7340e03
