### ISSUE TITLE
plone.api in code examples?

### ISSUE THREAD

**Issue by gforcada** [plone/documentation#542]
I found out that http://docs.plone.org/develop/plone/content/workflow.html need some serious love and decided to give it a go.

Now I'm wondering if it will be ok to simplify some code examples using plone.api. I guess it's ok right? The target audience is usually not core developers but ecosystem developers right?

**Comment by svx** [comment]
IMHO yes, if its 'best practice' do so, I say yes go for it ! :)

**Comment by gforcada** [comment]
Should we put that somewhere in the documentation styleguide?

**Comment by svx** [comment]
Sure, if you give an example I will add it to the style-guide

**Comment by svx** [comment]
@gforcada just an idea, but maybe a 'thing' to try, would it be an idea to try http://www.sphinx-doc.org/en/stable/ext/intersphinx.html to include examples from our training docs ?

@pbauer, @do3cc, @fulv, @fredvd and all the others, what do you think ?

**Comment by do3cc** [comment]
I'd have loved to use this a lot in the training manual to link to the plone docs, but you need to declare hooks in the target to link to (afair)
But links from the docs to the training manual are imho a bug. The training manual should not be better for reading consumption than the official docs itself. The training manual is meant as an aide for the training.
Oh well, at least the air is better, here in my ivory tower. :wave:

**Comment by svx** [comment]
Yeah, reading further it is not that easy to do it properly, anyway just thought it could be an idea :), looks like I was too fast with posting this as an idea, sorry for the noise !

**Comment by do3cc** [comment]
And it is a good one ;-)

**Comment by gforcada** [comment]
No action since then, so let's put it at rest 😄

**Comment by stevepiercy** [comment]
Are you sure about closing this issue? See:

https://6.dev-docs.plone.org/backend/workflows.html

Thank you for reviewing and closing obsolete issues. I'm in Discord in #Documentation if you have any questions about what we have planned for Plone 6 docs.

**Comment by stevepiercy** [comment]
I've updated that page with a TODO and a link to a [new issue](https://github.com/plone/documentation/issues/1308) that supersedes this one. Yes, we still need to migrate the Workflows docs from 5.2 to 6.0 and revise them.
