### ISSUE TITLE
Needs updates: develop/plone/i18n/contribute_to_translations.rst

### ISSUE THREAD

**Issue by svx** [plone/documentation#544]
Our docs here are quite out of date:
- referring to Plone 4.x
- referring to Plone 5 as future
- we need to check the examples here and howtos

**Comment by svx** [comment]
@vincentfretin would you mind to check sometime ?

**Comment by svx** [comment]
@vincentfretin ping ! :)

**Comment by vincentfretin** [comment]
@svx I somehow missed the first ping, I will take a look.

**Comment by vincentfretin** [comment]
I did a quick edit https://github.com/plone/documentation/commit/672757452d6d9e183e5fb047399b4c963eb94a4c
