### ISSUE TITLE
Can we exclude _locales from the build source?

### ISSUE THREAD

**Issue by svx** [plone/documentation#546]
@polyester according to https://github.com/plone/documentation/commit/2a84ad3a116265d66516f97f7327955871c8011a you were the last one working on _locales.

Can we exclude _locales from the build source, meaning add it to _exclude_patterns_ in https://github.com/plone/papyrus/blob/5.0/conf/conf.py ?

Is this needed for translations ? Looks like I am not able to find docs about that, well or I am too stupid to find them.

**Comment by polyester** [comment]
yes, as far as I know they can be excluded. It's easy to generate locales from the source, and that's how it should be done. (Note for sprint discussion in the future: probably only on a fixed release/milestone, not after every PR)

What I am not clear on (and has no docs) is how to do the 'load those into Transifex, and pull the translation back from Transifex' part which should come after. That's something I never did, I guess only @giacomos can truly tell (and document). 

There's the options for transifex in the makefile, but as they would run against a live project, I have no clue how we could safely test/CI that, and I was never brave enough to simply run them and see what happens.

**Comment by svx** [comment]
Ok !

another question would be do we have to put them into git ? I do not know how it works, but if we 'just' need them once a while for pushing translations into Transifex, they do not have to be in git right ?

**Comment by polyester** [comment]
They can be excluded from git.

**Comment by polyester** [comment]
whoops let me re-phrase that. There should be an **empty** directory _locales, but as git does not store empty directories, it should have a txt file saying "here go .po files that can be generated on demand" or something like that.

**Comment by svx** [comment]
Why we need an empty directory ? Is it not created when you generate the .po files ?

**Comment by svx** [comment]
https://github.com/plone/papyrus/pull/98
