### ISSUE TITLE
jenkins.plone.org documentation

### ISSUE THREAD

**Issue by gforcada** [plone/documentation#547]
Hi @plone/documentation-team !

On jenkins.plone.org repository there are some spare documentation, on how to do certain task related to CI/Jenkins.

They are automatically published in [ReadTheDocs](http://jenkinsploneorg.readthedocs.org/en/latest/), but as we have docs.plone.org, would it make sense to move them there?

The only downside I see is the update frequency... we are not adding/fixing the (super) small documentation that we have, but as usual, developers are impatient and as soon as I push docs on github I would like to see them online :-)

And given the nature of the documentation, maybe it make sense to only link instead of embed?

**Comment by svx** [comment]
Depends on the setup, if the idea is to have them under docs.plone.org/FOO is will be tricky to embed them properly at least for the moment.
I have another project were I do that, but it asks for some webserver and sphinx configuration tweaking I am not sure if we want to spend time and energy on that for now. 

Certainly in the long run, it would be something to think of :)
I guess a link would be easier, better for the time being.

If the idea is to have them under a own url, we can do same as we do for the training docs, which means pushing is done via travis.

**Comment by gforcada** [comment]
My gut feeling is that the audience for that documentation is really small and it has to be up to date really fast, as I have some ideas for mr.roboto where it reports back to Github and pointing the users to some docs about how to solve the issue, so keeping it external and having a page explaining where to find them I think it would be more than enough by now.

**Comment by svx** [comment]
+1

Just make sure to tell us the link so that we can add it to the docs :)

**Comment by svx** [comment]
closing this now, feel free to re-open !
