### ISSUE TITLE
line length in package documentation

### ISSUE THREAD

**Issue by thet** [plone/documentation#548]
Until recently we always applied the PEP8 line length restriction to 79 columns also for CHANGES.rst and README.rst.

IMO these files are documentation and should also apply the restructured text styleguide http://docs.plone.org/about/rst-styleguide.html#line-length-translations

We already have this mentioned in the Python styleguide: https://github.com/plone/documentation/blob/5.0/develop/styleguide/python.rst#line-length

> [the 79 column line length rule] explicitly does not aply to documentation .rst files. For rst files, use semantic linebreaks.

I propose to use _semantic linebreaks_ for all `.rst` files, including `README.rst`, `CHANGELOG.rst` and even doctests. It's better for readability and it's more consistent too.

**Comment by thet** [comment]
The above only if we don't add a linebreak at every colon because that gets unreadable. We should only break at every sentence.

**Comment by gforcada** [comment]
:+1: I'm already using it on my projects and it's way more relaxed.

**Comment by thet** [comment]
added a pull request for explicitly mentioning changes.rst and readme.rst: #549
