### ISSUE TITLE
Typo in http://docs.plone.org/external/plone.app.dexterity/docs/behaviors/schema-only-behaviors.html

### ISSUE THREAD

**Issue by zopyx** [plone/documentation#561]
Minor typo in third listing (sorry, could not find the source).

http://docs.plone.org/external/plone.app.dexterity/docs/behaviors/schema-only-behaviors.html

form plone.autoform.interfaces import IFormFieldProvider

instead of

from plone.autoform.interfaces import IFormFieldProvider

**Comment by gforcada** [comment]
If you see `external` in a docs.plone.org URL it means that it fetches the docs from somewhere else, namely `plone.app.dexterity` in your case.

So the pull request should be done against this file: https://github.com/plone/plone.app.dexterity/blob/master/docs/behaviors/schema-only-behaviors.rst

**Comment by gforcada** [comment]
Although it seems the docs were already updated in the git repository but not on docs.plone.org

@plone/documentation-team is that correct? Can we get an updated version up? Or it is still the _waiting for 5.0.3_ phase?

**Comment by svx** [comment]
@gforcada @zopyx 

yes: https://community.plone.org/t/next-docs-released-delayed-in-favor-of-plone-5-0-3/1718

We know that is not an ideal situation, we are working on faster releases, but currently that is our situation, apologizes for any inconvenience

**Comment by svx** [comment]
@zopyx 

https://github.com/plone/plone.app.dexterity/pull/209

@gforcada This was not yet fixed in the docs of plone.app.dexterity

**Comment by svx** [comment]
Fixed in https://github.com/plone/plone.app.dexterity/pull/209
