### ISSUE TITLE
http://docs.plone.org/external/plone.app.dexterity/docs/behaviors/schema-only-behaviors.html outdated for Plone 5

### ISSUE THREAD

**Issue by zopyx** [plone/documentation#562]
http://docs.plone.org/external/plone.app.dexterity/docs/behaviors/schema-only-behaviors.html

uses 

from plone.autoform.directives import form

However this import does not work with Plone 5.0.2

  File "/home/ajung/src/pp.client-plone/pp/client/plone/behaviors.py", line 2, in <module>
    from plone.autoform.directives import form
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/home/ajung/src/pp.client-plone/parts/instance/etc/site.zcml", line 16.2-16.23
    ZopeXMLConfigurationError: File "/home/ajung/.buildout/eggs/Products.ATContentTypes-2.2.10-py2.7.egg/Products/ATContentTypes/configure.zcml", line 18.2-18.44
    ZopeXMLConfigurationError: File "/home/ajung/.buildout/eggs/plone.app.collection-1.1.4-py2.7.egg/plone/app/collection/configure.zcml", line 9.2-9.45
    ZopeXMLConfigurationError: File "/home/ajung/.buildout/eggs/plone.app.querystring-1.3.12-py2.7.egg/plone/app/querystring/configure.zcml", line 11.2-11.42
    ZopeXMLConfigurationError: File "/home/ajung/.buildout/eggs/plone.app.registry-1.3.7-py2.7.egg/plone/app/registry/configure.zcml", line 12.4-12.34
    ZopeXMLConfigurationError: File "/home/ajung/.buildout/eggs/plone.app.registry-1.3.7-py2.7.egg/plone/app/registry/browser/configure.zcml", line 6.4-6.43
    ZopeXMLConfigurationError: File "/home/ajung/.buildout/eggs/plone.app.z3cform-1.1.8-py2.7.egg/plone/app/z3cform/configure.zcml", line 10.2-10.41
    ZopeXMLConfigurationError: File "/home/ajung/.buildout/eggs/plone.app.widgets-2.0.2-py2.7.egg/plone/app/widgets/configure.zcml", line 14.2-14.41
    ZopeXMLConfigurationError: File "/home/ajung/.buildout/eggs/Products.CMFPlone-5.0.2-py2.7.egg/Products/CMFPlone/configure.zcml", line 108.4-112.10
    ZopeXMLConfigurationError: File "/home/ajung/src/pp.client-plone/pp/client/plone/configure.zcml", line 16.4-21.6
    ImportError: cannot import name form

**Comment by jensens** [comment]
i fixed this in https://github.com/plone/plone.app.dexterity/commit/6a49084fb81f7eba381c95a49ca7471d0a587080
