### ISSUE TITLE
pintail

### ISSUE THREAD

**Issue by gforcada** [plone/documentation#566]
https://blogs.gnome.org/shaunm/2016/03/27/build-documentation-sites-with-pintail

It does not have support for rst by now, but maybe if added it could help us move forward?

**Comment by svx** [comment]
Hi,
would you mind to evaluate why moving to pintail would be a improvement  ? 

Looking at it I can not see any point why such a move would be helpful but maybe I am missing something ?

With our current setup which is by all means not perfect and needs lots of improvements we can do more than with pintail, and as you said pintail can' t even handle rst atm :)

I am all in for looking how pintail evolves over time, if it does ? :) But I can not see the point to moving to it :)

**Comment by gforcada** [comment]
I saw that blog post and that seemed quite similar (merging lots of doc repos together) approach/problems so I thought that it would be best to reuse/contribute to another tool than keeping our own.

I will not be the one maintaining one or another so I can not really judge, but if our approach is general enough we should try to get other projects to use it, so the maintenance/development is shared across projects.

My point of view was basically that the docs team is understaffed, so if we can get external help on parts of it all the best.

Specially given that the guy behind pintail is working in documentation and for Red Hat for a **very long** time, so I guess that pintail will not be dropped next week :-) (I personally know him as well).

**Comment by svx** [comment]
We share already :)

Parts of the #writethedocs community are using parts of our setup at least the parts which are not Plone specific and it works the other way around, too meaning we use parts of setups form others :)

So yeah we share ! :)

We have more the challenge of keeping/writing/improving our docs.

Thanks for the pointer anyway ! 

I will close this one, feel free to re-open ! :)
