### ISSUE TITLE
Cataloging/Indexing info distributed over several places.

### ISSUE THREAD

**Issue by jensens** [plone/documentation#571]
http://docs.plone.org/develop/plone/searching_and_indexing/indexing.html and
http://docs.plone.org/external/plone.app.dexterity/docs/advanced/catalog-indexing-strategies.html
need a merge, its almost the same, dup information, but both are having info the other does not have.

This one 
http://docs.plone.org/develop/plone/searching_and_indexing/catalog.html
targets the ZCatalog and should be considered too while rewriting the chapter.

**Comment by stevepiercy** [comment]
Closing in favor of #1730.
