### ISSUE TITLE
Update Styleguide

### ISSUE THREAD

**Issue by svx** [plone/documentation#578]
```
Usage of Sphinx within your project is optional, but if you want your add-on to (also) be documented for instance on Read The Docs it is highly recommended. Put the associated Makefile and conf.py into the /docs directory.
```

Should be updated, we do not want sphinx and related files in /docs the we just want **plain**  rst in /docs.

So meaning we should rewrite that, plus give an example how you can do that, including gitignore and all that.

**Comment by stevepiercy** [comment]
See https://6.docs.plone.org/contributing/documentation/
