### ISSUE TITLE
Change offending statement about migrating old JavaScript to new Plone 5 style

### ISSUE THREAD

**Issue by thet** [plone/documentation#579]
manage/upgrading/version_specific_migration/p4x_to_p5x_upgrade.rst:239:Plone tries to provide a shim for those that are stubborn to migrate.

^^ The above should be changed, because it's offending. It also reflects our best practice on JavaScript dependency management. The new hip thing in the JavaScript community is already closer to the ES6 standard by using the standardized import mechanisms.

**Comment by svx** [comment]
Does someone has a good suggestion how to re-phrase that ?

**Comment by rnixx** [comment]
In Plone 5.0, Plone will still recognize these jsregistry.xml files. Plone tries to provide a shim for them. It does this is by adding all jsregistry.xml JavaScripts into the "plone-legacy" Resource Registry bundle. This bundle simply includes a global jQuery object and includes the resources in sequential order after it.

However, you should at least consider migrating your resources as described in https://github.com/collective/example.p4p5 to gain control over your dependencies or if you want to keep backward compatibility to older Plone versions in your Add-Ons
