### ISSUE TITLE
Remove nesting

### ISSUE THREAD

**Issue by svx** [plone/documentation#580]
It seems I can' t find the old ticket anymore, so a new one.

Under /develop we have still this nesting, which does not looks good and is also confusing, see the pic:

![screen-develop-nesting](https://cloud.githubusercontent.com/assets/358860/14246671/f481d73a-fa68-11e5-9b2c-cddcbdd7cf4c.png)

This got partly fixed, bit we should finish that, one step could be to fix the naming in the headers of https://github.com/plone/documentation/blob/5.0/develop/index.rst.

Do we have any ideas for better naming to fix and avoid that ?

**Comment by polyester** [comment]
old ticket is at https://github.com/plone/documentation/issues/470

I'll see if I can think of good solution. It will involve re-naming headlines in a few external repos, but that's acceptable I think.

**Comment by svx** [comment]
There was another ticket with a screen-shot even but yeah,lets fix that :)

**Comment by svx** [comment]
@polyester not certainly in the external ones, we could also rename them in the index of develop on documentation.

I say it depends where it would make more sense  :)

**Comment by svx** [comment]
We can also override them:

http://www.sphinx-doc.org/en/stable/markup/toctree.html
