### ISSUE TITLE
Feature, have (more) stable urls for plone5 docs

### ISSUE THREAD

**Issue by do3cc** [plone/documentation#591]
It would be nice to have this url:
http://docs.plone.org/5/en/

This would help here:
https://github.com/plone/bobtemplates.plone/issues/135

**Comment by polyester** [comment]
That URL is valid, but it wouldn't help here. The guide got moved to http://docs.plone.org/about/documentation_styleguide.html (or, as you wish, http://docs.plone.org/5/en/about/documentation_styleguide.html
so the actual name changed.

see https://github.com/plone/bobtemplates.plone/pull/136 for fix

**Comment by do3cc** [comment]
Yes I know.
I did not made myself clear.
bobtemplates.plone links to this page.
We got the request to have a link to http://docs.plone.org/4/en/about/documentation_styleguide.html
in case of plone 4.
Instead of making an if else in the template, I'd prefer to have something along the lines of
http://docs.plone.org/{plone.major_version}/en/about/documentation_styleguide.html

**Comment by do3cc** [comment]
Oh I get it now, I myself did not read the original bug report properly.
You would redirect to the shorter url, so this would work. The issue we are actually having is that the current url is invalid, which is a totally different problem

**Comment by polyester** [comment]
I interpreted 1letter's request as "while the URL is broken, point to the plone4 one", so fixing the URL would solve the problem. But my interpretation may be wrong.

**Comment by do3cc** [comment]
You got it right, I got it wrong. That is my interpretation, and I am always right.
