### ISSUE TITLE
Plone 4: Should we update install instuctions?

### ISSUE THREAD

**Issue by svx** [plone/documentation#592]
The install docs of Plone 4 http://docs.plone.org/4/en/manage/installing/installation.html#installing-plone-using-the-unified-unix-installer pointing to Plone 4.3.6 should we update to the latest ?

Also the part of the installation differs from the part we have now in Plone 5 should we add missing pictures and so on ?

**Comment by smcmahon** [comment]
The installers for Plone < 5 do not have the dialog interface. So, no update needed for that.

**Comment by svx** [comment]
@smcmahon thanks ! 

I was thinking about the Plone version, in the [installation part](http://docs.plone.org/4/en/manage/installing/installation.html)

We have written there

>  Substitute the latest version number for 4.3.6 in the instructions below.

Which should be enough, but knowing that lots of people 'just' do copy and paste maybe it would be better to update ?

**Comment by gforcada** [comment]
@svx IMHO on the 4.x docs I would only update version numbers (so 4.3.8), maybe bugfixes if someone feels like it, but we have enough with 5 to also keep track of 4 docs... just my opinion though

**Comment by svx** [comment]
fixed by: https://github.com/plone/documentation/commit/f9b80d0d479d0a2d786bef309adea2d7c7ff9377
