### ISSUE TITLE
Fix  'Migrating Older Addons' section

### ISSUE THREAD

**Issue by khanstark** [plone/documentation#595]
The `mismatched anonymous define` block is out of place and merges into the content...  

![manifest](https://cloud.githubusercontent.com/assets/17498833/14326667/a7f75bde-fc4c-11e5-9c0e-6ac160f00844.png)

**Comment by svx** [comment]
@khanstark would you mind to evaluate a bit more ?

:)

**Comment by khanstark** [comment]
removing the verbatim and making it italic or something like that would be an option...

**Comment by khanstark** [comment]
@svx any suggestions for this?

**Comment by staeff** [comment]
@svx @khanstark I don't where to put it, but the problem can be solved in css, like so:

```
 a.internal code { white-space: normal } 
```

**Comment by khanstark** [comment]
@staeff how can reST related problem be solved by css code?

**Comment by staeff** [comment]
@khanstark because a certain html gets generated from the ReST and this is formatted with CSS (https://github.com/plone/sphinx.themes.plone). A good candidate to make the css change would be basic.css, but I can't find it.

**Comment by svx** [comment]
Does anyone, feels like work on that ? I rather skip that and focus on the new theme.

@polyester any thoughts ?

**Comment by staeff** [comment]
@svx, @polyester - I made the fix that I suggested above here: https://github.com/plone/sphinx.themes.plone/pull/39. I could not figure out how to make the papyrus - repo check out my branch and use it via the buildout. But checking it out manually worked.
You thing this is a ok solution for this bug?

**Comment by svx** [comment]
Fixed with: https://github.com/plone/sphinx.themes.plone/pull/39

@staeff you can tell mr.developer to use _your_ branch that should work :)

I merged it, we'll see :)

Thanks !
