### ISSUE TITLE
z3c.form docs - review

### ISSUE THREAD

**Issue by svx** [plone/documentation#604]
https://github.com/plone/documentation/blob/5.0/develop/plone/forms/z3c.form.rst

needs a review, we mention there still Plone 3 and 4 this could be confusing, if we really need that we should update the docs for Plone 3 and 4 and link to them. 
- are the docs still valid for Plone 5 ?
- can we remove mention of Plone 3 and 4, here ?

**Comment by sverbois** [comment]
What about moving the _http://docs.plone.org/develop/addons/schema-driven-forms/index.html_ section
in the _http://docs.plone.org/develop/plone/forms/index.html_ section ?
For me the first reading about standalone forms in Plone should be the "Schema-driven forms" section.

**Comment by staeff** [comment]
Hi @svx @sverbois just fyi, I created a post on community (https://community.plone.org/t/clean-up-documentation-section-schema-driven-forms/2163) that is related to this ticket. I did not come around to review the z3c.form.rst document, but hope to make it at some point.
I'd love to hear your opinions on the community-post, if you have any.

**Comment by stevepiercy** [comment]
Closing as fixed in Plone 6 documentation: https://6.docs.plone.org/backend/schemas.html. Please reopen if not correct.
