### ISSUE TITLE
Suggested doc update A slight twist of the RewriteRule solved problems with "there was an error loading modal"

### ISSUE THREAD

**Issue by svx** [plone/documentation#607]
Via the feedback form:

I have a Plone site, fronted by Apache 2.2, under a domain that is a Swedish word. I have one domain with Swedish characters and one domain with umlauts removed.
I made two rewrite rules pointing to the same Plone site, each line  according to the Plone docs for using Apache as a frontend.

I found that I could not do modal login in Plone 5, (And I had the same problem with the current Plone4 site) 
I had to login entering example.com/login as the url in the browser adress field.

Working with my migration to Plone5 and Apache 2.4 (since I upgraded to Debian Jessie) I found a solution.

I turns out that, with my multiple rewite rules where only domain varies, Apache might use another domain name, which makes modal fail. 
And yes, I had specified "UseCanonicalName on", it did not help.

The http://docs.plone.org/manage/deploying/front-end/apache.html#introduction give this example of a rewrite rule:

RewriteRule ^/(.*) http://localhost:8080/VirtualHostBase/http/yoursite.com:80/Plone/VirtualHostRoot/$1 [P,L]

I suggest that yoursite.com is replaced with %{HTTP_HOST} in the example:

RewriteRule ^/(.*) http://localhost:8080/VirtualHostBase/http/%{HTTP_HOST}:80/Plone/VirtualHostRoot/$1 [P,L]

When I did this change and removed the multiple lines with RewriteRule, where only the domain name varied, and kept only one line with %{HTTP_HOST}  as the domain name,I got rid of all "there was an error loading modal" with both some Plone4 sites and my new Plone5 site.

Note: This needs to be verified on Apache 2.2 as well. I have upgraded all my servers to Debian Jessie and have no longer any instances of Apache 2.2

**Comment by svx** [comment]
Would someone who is using Apache like to do a review ? I do not use Apache :)

**Comment by polyester** [comment]
yep, using  %{HTTP_HOST} is the way to do it, and yep it works on apache2.2

**Comment by svx** [comment]
I guess I am missing something, because this also would mean we have to update the whole example right ? Because we would have to add:

> RewriteCond %{HTTP_HOST}   !^www.yoursite.com [NC]

otherwise how apache now what %{HTTP_HOST} is ?

Does you have a working setup with that what we could change into an example ?

**Comment by svx** [comment]
Done please review: https://github.com/plone/documentation/pull/632

**Comment by svx** [comment]
This got already merged, people if you merge stuff please check if there is still a ticker open :)
