### ISSUE TITLE
Update: http://docs.plone.org/about/contributing.html

### ISSUE THREAD

**Issue by svx** [plone/documentation#608]
Currently it is not that easy to understand where and how people should open a ticket...

It seems that people get confused with the different repos for the docs itself [docs/papyrus/theme] and with the difference between 'core' docs and 'external' docs like dx.

It seems even core-devs, getting confused.

Possible solution:

Update the docs and clarify all this different things.

In a prefect world they would be one issue tracker and not this 'messy' mix of all this different ones :)

**Comment by gforcada** [comment]
@svx you can always say "In case of doubt, always report to documentation issue tracker" then someone points things out and copies them around if needed. Just like with the code the fallback is CMFPlone

**Comment by svx** [comment]
done, a long time ago, closing - feel free to re-open :)
