### ISSUE TITLE
migrate relevant parts of Plone upgrade guide

### ISSUE THREAD

**Issue by tkimnguyen** [plone/documentation#615]
https://old.plone.org/documentation/manual/upgrade-guide has good info

it is still being referred to from this page http://docs.plone.org/develop/plone/misc/upgrade.html?highlight=migrate

**Comment by svx** [comment]
@polyester This was already done right ?

**Comment by tkimnguyen** [comment]
Not as far as I know

**Comment by tkimnguyen** [comment]
I guess a lot of it is done but I haven't looked it over in detail: http://docs.plone.org/manage/upgrading/index.html

**Comment by stevepiercy** [comment]
Closing as nothing clear that needs to be done. https://6.docs.plone.org/upgrade/index.html
