### ISSUE TITLE
Dead link in "Ask for help"

### ISSUE THREAD

**Issue by icemac** [plone/documentation#619]
[Ask for help](http://docs.plone.org/askforhelp.html) tells about a "general questions forum" but the link is dead an there seems to be no such forum on https://community.plone.org
So I am not sure how to fix this sentence.

Source code of the link in question:

> Follow the structure of the forum by creating your topic in a proper location (subforum). If you are in doubt where to create your topic, post to the `general questions <https://plone.org/support/forums/general>`_ forum.

**Comment by svx** [comment]
Yeah, the launch of new plone.org site broke that, I fixed that in https://github.com/plone/documentation/pull/620
