### ISSUE TITLE
Integrated README of plone.app.vocabularies?

### ISSUE THREAD

**Issue by jensens** [plone/documentation#640]
I have no idea how to get this into docs.plone.org, but the README at 
https://pypi.python.org/pypi/plone.app.vocabularies
contains valuable information. We should pull it in.

**Comment by svx** [comment]
@jensens any idea where a good place would be ? 

I guess somewhere under /develop ?

If you tell me where, I will create a PR for https://github.com/plone/plone.app.vocabularies which includes following our guidelines about READMES, a /docs dir and so on.

**Comment by svx** [comment]
@jensens @gforcada ping ! Where would be a good place to include it ?

**Comment by gforcada** [comment]
What about https://docs.plone.org/develop/plone/functionality/index.html ?

**Comment by stevepiercy** [comment]
Superseded by https://github.com/plone/documentation/issues/1306
