### ISSUE TITLE
Portlet documentation: z3cform instead of deprecated formlib?

### ISSUE THREAD

**Issue by fgrcon** [plone/documentation#643]
http://docs.plone.org/develop/plone/functionality/portlets.html: 

...
This document contains quick how-to information only. Please visit the This document contains quick how-to information only. Please visit the **Portlets reference manual**  for in-depth information.
...
**Portlets reference manual** points to :  http://docs.plone.org/4/en/old-reference-manuals/portlets/index.html

**Comment by stevepiercy** [comment]
Closing as fixed https://6.docs.plone.org/classic-ui/portlets.html
