### ISSUE TITLE
Remove paster ?

### ISSUE THREAD

**Issue by svx** [plone/documentation#644]
In http://docs.plone.org/develop/plone/functionality/portlets.html we still have some reference to paster, even if there is a deprecated message.

Should we remove that let's say from the 5.1 docs on, so that we slowly can get rid of the latest paster references and tell people more about bobtemplates ?

**Comment by gforcada** [comment]
IMHO we should get rid _completely_ of it. bobtemplates.plone is already mature enough and has been used enough to be a viable replacement.

Better talk about something that we maintain rather than something that no one cares nor fixes nor improves anymore.

**Comment by svx** [comment]
Yeah looking closer into: http://docs.plone.org/develop/plone/functionality/portlets.html I also spot a lot of grok stuff.

What is the current deal with Plone 5 and portlets ? We really should update/improve/review this !

**Comment by stevepiercy** [comment]
Closing as won't fix.
