### ISSUE TITLE
Add plone version as variable

### ISSUE THREAD

**Issue by svx** [plone/documentation#646]
with this we only have to update that in one place, way better for consistency

**Comment by svx** [comment]
@polyester 

We could use: http://www.sphinx-doc.org/en/stable/config.html#confval-rst_epilog

This would mean, we only have to update that setting in conf.py

Example:

Plone 5.0.9 will be released, currently we have to run a find and replace through the whole docs for replacing 5.0.8 with 5.0.9 - with a setting like this in our config:

``` python
rst_epilog = """
.. |plone5| replace:: Plone 5.0.9
"""
```

We would be good to go !

## Actions needed to resolve that:
- [ ] add rst_epilog to conf.py [papyrus]
- [ ] adjust rst source files to use this $VAR
- [ ] update docs

**Comment by svx** [comment]
@polyester do you have a opinion on that ? :)

**Comment by stevepiercy** [comment]
Here's how Pyramid addressed this issue. Pyramid has multiple versions and branches for each major release. Currently we have branches `1.6-branch`, `1.7-branch`, and `master`.

In our [conf.py](https://github.com/Pylons/pyramid/blob/master/docs/conf.py):

``` python
import pkg_resources
# ...
version = pkg_resources.get_distribution('pyramid').version
```

Then in our docs, especially installation and tutorials where we need to use the current version:

``` rst
#. Use ``pip`` to get :app:`Pyramid` and its direct dependencies installed:

   .. parsed-literal::

      $ $VENV/bin/pip install "pyramid==\ |release|\ "
```

Thus we never have to replace. It automatically stays up to date.

Although off-topic, we also do a couple of nifty things with multiple versions/branches. We found that search engines indexed old versions of Pyramid, users would click the first search result, and end up on outdated or unreleased versions of our documentation. This caused much frustration to the user and to those providing support. So we addressed the matter as follows.

`master` is where unreleased development occurs and from which new releases are cut. It's docs are built at: http://docs.pylonsproject.org/projects/pyramid/en/master/ Note the friendly red "Documentation in Progress" badge in the lower right.

`1.7-branch` is the stable and latest release for Pyramid. Its docs are at http://docs.pylonsproject.org/projects/pyramid/en/latest/ or http://docs.pylonsproject.org/projects/pyramid/en/1.7-branch/

`1.6-branch` is the previous branch. Its docs are at http://docs.pylonsproject.org/projects/pyramid/en/1.6-branch/ Note the friendly red button "Read the latest version of this page". This requires a package `pylons_sphinx_latesturl`, and some changes to `conf.py`:
- https://github.com/Pylons/pyramid/blob/master/docs/conf.py#L58-L59
- https://github.com/Pylons/pyramid/blob/master/docs/conf.py#L129-L145

For the presence or absence of badges, in `conf.py`:
- https://github.com/Pylons/pyramid/blob/master/docs/conf.py#L149-L156
- https://github.com/Pylons/pyramid/blob/1.7-branch/docs/conf.py#L149-L156
- https://github.com/Pylons/pyramid/blob/1.6-branch/docs/conf.py#L146-L153

**Comment by svx** [comment]
@stevepiercy great, but this is not the way how we build our docs, so this will not work for us.

About branches, we use a different setup.
Like I said already earlier and during the conference, we are busy rebuilding our whole docs setup. 
Lots of stuff will change/is changing.
Since we have to deal with lots of history and also content for different audiences we are doing this slowly and trying to be carefully, so yes some stuff is taking a bit longer.

We also deal with lots of other stuff in our docs and build setup, which last time I checked pyramid is not doing, like auto-screenshots generation and so on.

So it is a bit different than a usual sphinx setup :)

**Comment by svx** [comment]
@polyester ahem little issue :), that is not working in a

```
.. code-block::
```

out of the box, which is kind of what we need ...

**Comment by stevepiercy** [comment]
@svx what is the sample rendered output?

For Pyramid, we changed some `.. code-block::` to `.. parsed-literal::` whenever the current version needed to be rendered in the output.

**Comment by stevepiercy** [comment]
Closing as complete. We now have substitutions defined in `conf.py`.
