### ISSUE TITLE
update  documentation/working-with-content/managing-content/ploneformgen/creating_content.rst 

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/documentation#649]
Plone 5.0

There doesn't seem to be a way to set the body text/content area of a Document/Page content type. I think this level of customization is not allowed TTW? Using `obj.setText` does not work and didn't find an alternative in the portal_catalog. 

[This example](https://github.com/plone/documentation/blob/5.0/working-with-content/managing-content/ploneformgen/creating_content.rst) works great if you just want to take form data and insert into a document's metadata (keywords, description, title, etc.).

If form data can't be mapped to body text, this example should be modified and noted that this isn't available TTW in Plone 5.

![screenshot](https://cloud.githubusercontent.com/assets/7101218/16338179/fa0d5f20-39e8-11e6-9cf2-91112f326c46.png)

**Comment by stevepiercy** [comment]
Closing as won't fix for Plone 5.
