### ISSUE TITLE
Accesing the portal_catalog Tool in TAL Template

### ISSUE THREAD

**Issue by l34marr** [plone/documentation#650]
With http://docs.plone.org/develop/plone/searching_and_indexing/query.html#accesing-the-portal-catalog-tool I try to access the `portal_catalog` tool in a template, but run into `AttributeError: 'LazyMap' object has no attribute 'searchResults'`.
I guess it should be
`<div tal:define="portal_catalog nocall:context/portal_catalog" />`
Anyone helps to confirm?

**Comment by gforcada** [comment]
IMHO one should simply call the view to get the data and do the heavy operations on python code rather than on templates, where they run on restricted python and thus are far more slow.

**Comment by pe82** [comment]
I am getting the same error

**Comment by gforcada** [comment]
@pe82 does the proposed solution from @l34marr works for you?

**Comment by pe82** [comment]
I actually went through the shell...

```
from zope.component.hooks import setSite
setSite(site)
catalog = site.portal_catalog
```

That gave me the right catalog instead of throwing a LazyMap error.

**Comment by stevepiercy** [comment]
Closing. Nothing to do here.
