### ISSUE TITLE
Update: http://docs.plone.org/develop/plone/misc/slideshow.html

### ISSUE THREAD

**Issue by svx** [plone/documentation#663]
Via feedback-widget:

At least in the moment Carousel is not working with Plone5, we should adjust the page in the docs.

Question is there a sideshow add-on which is working with Plone5 ?

Here is also a linked thread on SO: https://stackoverflow.com/questions/34728580/plone-5-0-and-carousel-2-2-1

**Comment by stevepiercy** [comment]
Closing as won't fix.
