### ISSUE TITLE
fix references to Zope Management Interface and ZMI

### ISSUE THREAD

**Issue by tkimnguyen** [plone/documentation#670]
As of Plone 5 we have been removing mentions of Zope and have changed the Site Setup panel name from "Zope Management Interface" to just "Management Interface". We should do this consistently in the docs. Similarly for "ZMI" maybe we should go with "MI"?

**Comment by gforcada** [comment]
Well then instead of MI let's call it Management Interface, as MI feels weird (_maybe they wanted to say IM_ one can wonder)

**Comment by tkimnguyen** [comment]
"PMI" (Plone Management Interface)? (sounds very similar to ZMI for Americans... "zee")

**Comment by svx** [comment]
IMHO I would prefer "Management Interface", people know that term already, introducing a new one like "PMI" is possible confusing for user.

If we really would like to start using a new term, this should be done carefully and slowly, for example we could do that with the release of Plone 6, where we also mentioning that in the release notes/changes/what is new in Plone 6.
Doing so now is IMHO less ideal.
But yeah, we should use one term consistent through the docs

**Comment by gforcada** [comment]
:+1: for "Management Interface", we already switched to that on the controlpanel right? (On 5.x I mean)

**Comment by tkimnguyen** [comment]
Yes, we changed it to Management Interface when you visit localhost:8080

**Comment by svx** [comment]
PR for review is here: https://github.com/plone/documentation/pull/789

**Comment by tkimnguyen** [comment]
I reviewed the PR but it was merged before I could complete the review!

**Comment by svx** [comment]
I will create a new PR, later on, no worries and thank you !

**Comment by svx** [comment]
@tkimnguyen https://github.com/plone/documentation/pull/790

**Comment by tkimnguyen** [comment]
thx @svx!
