### ISSUE TITLE
broken link to plone contributor agreement

### ISSUE THREAD

**Issue by oz123** [plone/documentation#672]
http://docs.plone.org/develop/coredev/docs/agreement.html

The link for the agreement has a typo: http://plone.org/foundation/contributors-agreement/agreement.pdf/at_download/file.

**Comment by svx** [comment]
This is already fixed in: https://github.com/plone/buildout.coredev/commit/b99a706effe6fbf84ed28910a586d013df85b458

It will be updated on docs.plone.org with the next docs release

**Comment by oz123** [comment]
Thanks for the quick reply. We should port this fix to the 5.0 branch too. I will do a separate PR.

**Comment by ableeb** [comment]
I received this issue report about the contributor’s agreement link from someone submitting a contributors agreement. 

> Please note that the link text on https://docs.plone.org/develop/coredev/docs/contributors_agreement_explained.html#contributors-agreement-for-plone-explained is https://plone.org/foundation/contributors-agreement/agreement.pdf alright, but the clickable text is not; instead, it simply reloads the page, and thus causes some confusion.

This is the rendered link
https://docs.plone.org/develop/coredev/docs/contributors_agreement_explained.html#id1

This is the text:
The Plone Contributor Agreement can be found at: `https://plone.org/foundation/contributors-agreement/agreement.pdf`_

**Comment by svx** [comment]
Fixed again in https://github.com/plone/buildout.coredev/pull/386, will be online after the PR is merged with the next deployment of the docs.

**Comment by ableeb** [comment]
@svx Thx!  
cc @tobiasherp who reported it

**Comment by tkimnguyen** [comment]
That link really should point instead to https://plone.org/foundation/contributors-agreement/ rather than directly to the PDF, and IMO the duplicated information (on docs.plone.org and on plone.org) is going to cause us grief. I will take this over to https://github.com/plone/buildout.coredev/pull/386

**Comment by stevepiercy** [comment]
This was fixed years ago.
