### ISSUE TITLE
Explain git-rebase - extend git-cherry-pick docs

### ISSUE THREAD

**Issue by svx** [plone/documentation#673]
Having some docs about cherry-picking is nice, thank you for that !!!

Lots of times, we do more than one commit to a branch, for example if we review and improve a PR, with the result that even cherry-picking is getting harder.

In order to make it maybe a bit easier we could add some simple docs about rebasing first and after that do cherry-pick

**Comment by polyester** [comment]
yes, squashing them can be good, and should be explained. Although it can also get messy when branches are left lying around. 
https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history is a well-written longer text on both the joys and the dangers

**Comment by svx** [comment]
BTW, we need to clean a bit, we have currently a lot of branches lying around

**Comment by gforcada** [comment]
Maybe more than re-writing something that has been explained somewhere else we should just point to those links?

**Comment by svx** [comment]
@gforcada I am more  in favor of picking stuff we need and include it in our docs, the experience over the last year show that this is more trust-able, than relying on a 'third party link'.   

It is a bit more work for now, but less work in the long run :)

**Comment by stevepiercy** [comment]
/me opens a big can of Nope-Ass™!
