### ISSUE TITLE
Cleanup repository

### ISSUE THREAD

**Issue by svx** [plone/documentation#675]
Currently we have a couple of branches lying around.
We should fix and merge or remove them as longer we wait as harder and more work it gets.
- identify status of branch
- fix and merge or remove

**Comment by staeff** [comment]
Maybe it helps to give feedback here about the branches we know? `staeff-fix-form` is still something I intend to work on.

**Comment by svx** [comment]
Well that is what I meant with

```
identify status of branch
```

But as you wish :) :
A full overview telling which are open PRs is here: https://github.com/plone/documentation/branches/all 
-  mrtango-plone5-theming Updated 10 months ago by MrTango 
-  installing_plone_osx_update Updated a year ago by svx 
-  update_nginx Updated 8 months ago by svx 
-  frisi-resource-bundles Updated 8 months ago by polyester 
-  fulv-patch-1 Updated 7 months ago by fulv 
-  frisi-resources-bundles Updated 7 months ago by frisi 
-  svx_add_versions Updated 5 months ago by svx 
-  portal-actions-control-panel Updated 4 months ago by ebrehault 
-  mrtango-external-catalog Updated 2 months ago by MrTango 
-  staeff-fix-form Updated 2 months ago by staeff 
-  svx_plone4_fix_addons Updated 2 months ago by svx 
-  feature/theming-scenarios Updated 2 months ago by pilz 
-  security-guidelines Updated 14 days ago by svx 
-  svx_improve_rst-styleguide Updated 5 days ago by svx

**Comment by svx** [comment]
Hi, @staeff, @MrTango and @djowett if you find a minute, would you mind to check, the state of the branches? 

Thanks !

@MrTango  Do you know the status of this branch: https://github.com/plone/documentation/tree/mrtango-plone5-theming ?

@staeff Do you know the status of this branch: https://github.com/plone/documentation/tree/staeff-fix-form ?

@djowett Do you know the status of this branch: https://github.com/plone/documentation/tree/djowett-patch-1 ?

**Comment by djowett** [comment]
@svx minute spent :-) mine is in https://github.com/plone/documentation/pull/697 and can be merged IMO,  but some test fails inexplicably - perhaps it's easier just to delete it?

**Comment by svx** [comment]
@djowett nah :) I will include it manually , it is useful, right ? :)

**Comment by djowett** [comment]
Yup, was useful to me :)

**Comment by svx** [comment]
@djowett done, by: https://github.com/plone/documentation/pull/724

**Comment by svx** [comment]
@MrTango @staeff ping !

**Comment by staeff** [comment]
hey @svx, sorry for being so late replying here. For now I removed the branch.

**Comment by svx** [comment]
@staeff np :)

**Comment by stevepiercy** [comment]
I deleted any branch that is 1 year old or older, except for protected branches for older versions of Plone documentation. I also deleted branches without a PR. Closing as fixed.
