### ISSUE TITLE
Error in Code Snippet for "Setting the template of an individual widget"

### ISSUE THREAD

**Issue by pgrunewald** [plone/documentation#683]
Regarding the snippet from http://docs.plone.org/develop/plone/forms/z3c.form.html#setting-widget-templates:

First line says:

``` python
from zope.app.pagetemplate import ViewPageTemplateFile as Z3ViewPageTemplateFile
```

This import fails for Plone 4.3.7 and newer. The correct line should be:

``` python
from zope.browserpage.viewpagetemplatefile import ViewPageTemplateFile as Z3ViewPageTemplateFile
```

Other than that, the signature of `updateWidgets()` is also incorrect, which should say `updateWidgets(self, prefix=None)` to fullfil the interface `z3c.form.interfaces.IForm`.

best regards

**Comment by gforcada** [comment]
@pgrunewald would you mind providing a pull request to fix it?

**Comment by pgrunewald** [comment]
Oh, apparently I missing the Contributor's Agreement. Will be submitted soonish.

**Comment by pgrunewald** [comment]
@gforcada I have signed the agreement. Will the "Plone Contributors Agreement verifier" re-evaluate my PR automatically or does it have to be triggered manually?

**Comment by gforcada** [comment]
@pgrunewald closing and reopening the pull request does the trick :-)
