### ISSUE TITLE
dead link: doctests

### ISSUE THREAD

**Issue by fgrcon** [plone/documentation#687]
https://plone.org/documentation/tutorial/testing/doctests  in page: http://docs.plone.org/develop/testing/doctests.html.

**Comment by gforcada** [comment]
@sneridagh @svx  is there a way to get to it still? I can not access old.plone.org and see the content to copy it over...

**Comment by polyester** [comment]
if you have login on old.plone.org, it can be retrieved from https://old.plone.org/documentation/kb-old/testing/doctests
But beware, there are (slightly geriatric) dragons there: that tutorial was written for Plone 3. And thus may have to go into the plone3 branch, if at all.

**Comment by stevepiercy** [comment]
Closing as obsolete and won't fix.
