### ISSUE TITLE
should we include documentation on how to recover admin password?

### ISSUE THREAD

**Issue by tkimnguyen** [plone/documentation#689]

**Comment by gforcada** [comment]
maybe the question should be: _any reason not to do so?_

**Comment by tkimnguyen** [comment]
Ah I think it is here already: http://docs.plone.org/manage/deploying/zope.html?highlight=admin#adding-users-from-command-line-reset-admin-password so maybe it just needs some more text that includes the word "recover" (which is the keyword many would be looking for).

Also noticed that that section links to https://plone.org/documentation/faq/locked-out which has not been migrated from https://old.plone.org/documentation/faq/locked-out. It seems to be more complete than what is currently at docs.plone.org...
