### ISSUE TITLE
blank screen shots on http://docs.plone.org/adapt-and-extend/config/resource-registries.html

### ISSUE THREAD

**Issue by tkimnguyen** [plone/documentation#691]
![screen shot 2016-09-02 at sep 2 10 29 46 am](https://cloud.githubusercontent.com/assets/815418/18209161/3128e768-70f8-11e6-995d-df34fba53190.jpg)

**Comment by polyester** [comment]
fixed for now; will investigate generating screenshots with phantomjs. Less pretty, more reliable.
