### ISSUE TITLE
Update: Documentation structure & styleguide

### ISSUE THREAD

**Issue by svx** [plone/documentation#703]
Currently we have the a note saying:

> If you use bobtemplates.plone to generate the layout of your add-on, the recommended files will already be there, and in the right place. You'll still have to write the content, though.

Unfortunately this is currently only partly the case, we still have an issue:

https://github.com/plone/bobtemplates.plone/issues/169

So ... we should fix bobtemplates asasp. or adjust the note :)

**Comment by gforcada** [comment]
bobtemplates.plone has been fixed :-)

**Comment by svx** [comment]
Nice, closing this ! :)
