### ISSUE TITLE
include more info on editors

### ISSUE THREAD

**Issue by tkimnguyen** [plone/documentation#706]
from https://testthedocs.org/training/basic/tools/editors.html in https://github.com/plone/documentation/blob/5.0/about/helper_tools.rst (also the Docker for it)

**Comment by svx** [comment]
@tkimnguyen Here we go, not finished, yet but hopefully it will be soon.

![screen-sublime-for-writing](https://cloud.githubusercontent.com/assets/358860/21720648/a49180b8-d424-11e6-855d-e80927d2c5aa.png)

Still, not sure yet what is better, putting it into a blog post or as part of docs.testthedocs.org

**Comment by stevepiercy** [comment]
Closing as won't fix. Not our job. Any editor works.
