### ISSUE TITLE
Switch from PFG to collective.easyform

### ISSUE THREAD

**Issue by svx** [plone/documentation#711]
Currently we still have in the docs for Plone 5 a huge part about PFG, should we change this to collective.easyform?

If so, what is the state of collective.easyform and also of its docs ?

**Comment by svx** [comment]
@prakharjoshi do you know the state of the docs of collective.easyform ?

**Comment by svx** [comment]
@prakharjoshi ping !

**Comment by prakharjoshi** [comment]
@svx  Sorry for missing this part and replying that late. I guess easyforms is ready for plone 5 and we have 2.0.0a1 release. We can add these in our docs. Let me know if I can help you in that.

**Comment by svx** [comment]
@prakharjoshi awesome !

What is the state of the docs ?

- are they up to date
- do we have docs for 'integrators' ? 
- do we have screen-shots [robot-framework] ?
- ...

:)

**Comment by plone-foundation** [comment]
Until we're out of alpha, we should keep it out of the main Plone
documentation.

**Comment by svx** [comment]
We are currently far away from putting it there. But it would be nice to get the docs in order so that later on this is 'easy' to include.

**Comment by tkimnguyen** [comment]
There are quite a few open bugs left in https://github.com/collective/collective.easyform/issues so maybe we need a concerted push to fix and test it.

**Comment by svx** [comment]
Closing this for now, as c.e is still alpha and not the default replacement for PFG, yet

**Comment by tkimnguyen** [comment]
@svx I don't think it being alpha is a strong enough reason to close this and not to start mentioning easyform instead of PFG. PFG uses Archetypes, which we are going to officially drop support for in Plone 6, which is in the (yes, yes) yet to be published new roadmap. Easyform is still marked as alpha only because no one really has ownership and is willing to pull the trigger. I think it's ready to be marked as a production release 2.0.0. Just needs doing.

**Comment by svx** [comment]
@tkimnguyen Please read the whole thread :)

It is not "only" about being "alpha".
There are currently other various reasons, changing from "alpha" to stable will not cut it.

I will try my best to explain that in a moment:

# Documentation

- There is currently *no* up to date documentation, with up to date screen shots in the repo, what is there is old docs with images for Plone 4.

- The docs which are there are currently not following best practices and style-guide.
- There are currently no proper docs for end user at all

# Functionality

With PFG you can do a lot, you have lots of adapters for exporting, saving and so on. What is the status of CE here ? Can I save input in various data bases or various formats and so on ?

## Why is this a thing ?

Because if you are used to PFG and you may use certain adapters, you can't do that currently with CE.

This is a important point to think about, how to communicate that, what is the alternative, is the alternative workable for end user ?

Saying this is better, but sorry you can't do xyz anymore OOTB is tricky to say at least.

# Developer VS End-user

Yeah, it is nice that CE is DX ! Sure ! But to be honest 99.9% of user like end user will not care, they may not even no the difference why should they, they use the UI to add a form.

# One vs Many

You could say now, no problem we add CE and PFG to the docs.
Sure we can do that but this is tricky, too. We should need to find a good and understandable way to explain that to all user not only developer.

# The End

I am not against CE in the docs, not at all ! But I truly think we should be careful how we do it and how we explain the differences and alternative workarounds if there any needed.
Further I also have the strong opinion that the docs for of CE should be excellent for developer *and* for en user.

**Comment by stevepiercy** [comment]
Closing in favor of #1104 and we won't be updating Plone 5 docs.
