### ISSUE TITLE
Extend guidelines with part about .github dir

### ISSUE THREAD

**Issue by svx** [plone/documentation#715]
We use this directory to add templates like, how to contribute which will show up on GitHub, if people for example open an issue, see https://github.com/plone/documentation/tree/5.0/.github for more information.

**Comment by svx** [comment]
copy from duplicate;

GitHub blog posts on .github/:
https://github.com/blog/2111-issue-and-pull-request-templates

...and CONTRIBUTING.md:
https://github.com/blog/1184-contributing-guidelines

**Comment by stevepiercy** [comment]
We now have a new project for the Plone organization to cover all the community health files. Closing as complete. See:

https://github.com/plone/.github
