### ISSUE TITLE
Add more docs about how to contribute to plone not only to docs

### ISSUE THREAD

**Issue by svx** [plone/documentation#718]
- Add more docs on how to contribute to plone as in to the organization, currently we cover on how to contribute to the docs, we should add a part on how to contribute to the whole project and also cover parts like that we prefer branches over forks for pull requests and the reasons behind that

**Comment by stevepiercy** [comment]
Pyramid has some good material that could be adapted for Plone and its docs.

https://github.com/Pylons/pyramid/blob/master/contributing.md

https://github.com/Pylons/pyramid/blob/master/HACKING.txt

**Comment by svx** [comment]
IMHO as we are on it, we should mention the difference between `core` and `collective`.

Do we have some old docs somewhere about that ?

 The difference between both and the different requirements like you do not need to sign the PCOA if you work in/with `collective`, but you will need to do that for `core`

**Comment by stevepiercy** [comment]
Done. See https://6.docs.plone.org/contributing/index.html
