### ISSUE TITLE
Extend guildelines with what to do for if you create a repo in github.com/plone

### ISSUE THREAD

**Issue by svx** [plone/documentation#719]
Extend current docs with parts like:

- .github dir and unified 'guidelines label'

**Comment by stevepiercy** [comment]
GitHub blog posts on `.github/`:
https://github.com/blog/2111-issue-and-pull-request-templates

...and CONTRIBUTING.md:
https://github.com/blog/1184-contributing-guidelines

**Comment by stevepiercy** [comment]
Is this issue different from #715 or a duplicate? Maybe combine them into one?

**Comment by svx** [comment]
duplicate of #715, closing
