### ISSUE TITLE
readme example lacks reference to docs style guide

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#723]
As a newbie to Plone documentation, I had no idea that there was a [style guide](http://docs.plone.org/about/index.html). I only knew about it because a Pyramid sprinter pointed it out to me.

I suggest adding the link to the style guide in the [README example](https://github.com/plone/documentation/blob/40e7fb74ea2c26b0e17e3d6eac309f3cd80a8ae2/about/documentation_styleguide.rst#readme-example) and to other repos as needed.

I can't decide whether it should go under the heading of "Documentation" or "Contribute". I'm leaning toward "Contribute" because the style guide is mostly for showing contributors how to follow Plone's documentation conventions. What do y'all think?

**Comment by svx** [comment]
IMHO, this should/will be solved in another way, I had 'just' no time to finish it yet !

The plan is to add under `Contribute` one link to a document which will explain/ give an overview about the whole process and not 'only' the README style-guide.

Also all links in the 'GitHub contribute info box' will link to this doc.

With this is gives a much better overview, and we will not mess up the README with adding more and more 'loose' links. 
It is important to keep  it smooth and clean, READMEs are not 'only' for devs anymore, these days, there are also part of your 'brand/marketing' and used by 'normal' user too.

**Comment by stevepiercy** [comment]
@svx let's see what you have in mind.

I'd be happy to run through your unfinished idea as a still new-to-Plone user/developer/documenter. I face many of the same challenges you face with Plone as with being a core contributor to Pyramid and other projects under the Pylons Project (docs, training, and marketing).

**Comment by svx** [comment]
Fixed with https://github.com/plone/documentation/commit/c204ca8ee85f438d1486af14ced1b3efc74083d6
