### ISSUE TITLE
Varnish 3 

### ISSUE THREAD

**Issue by svx** [plone/documentation#725]
Varnish 3 is eol and if I got it right, also there will be no more security updates from 2017 on.

Personally I would like to move the docs about Varnish 3, to for example, `old reference` and  add a note/warning that this version is eol.

If you still run on a older Ubuntu LTS version like 12.04 LTS, you will have to prepare an upgrade anyway because 12.04 EOL is April 2017.

**Comment by hvelarde** [comment]
I already killed it; nobody is going to install Varnish now on a 12.04 LTS machine.
