### ISSUE TITLE
Add Ubuntu 16.04, remove 12.04 from the docs

### ISSUE THREAD

**Issue by svx** [plone/documentation#726]
Currently we still mention Ubuntu 12.04 in the installation docs, since 12.04 will be eol in April 2017, and 16.04 is now working, I would like to:

- remove 12.04 from the docs
- add 16.04 next to 14.04

**Comment by gforcada** [comment]
One of the big changes on 16.04 is that python 2.7 is no longer installed by default and that /usr/bin/python may point to python3.5 as well.

**Comment by svx** [comment]
OK, but this is not a problem, we add that, we have currently docs for 12.04 and 14.04 which are also different.

But anyway thanks for the reminder ! :)

**Comment by svx** [comment]
done !
