### ISSUE TITLE
Update: http://docs.plone.org/develop/plone/misc/upgrade.html

### ISSUE THREAD

**Issue by svx** [plone/documentation#744]
Thanks to @tkimnguyen we have some improvements. Thanks !

Still this needs some more love, currently it is still out of date since we are mentioning lots of old Plone 4 things, like upgrading to Plone 4.1. and AT and so on.

For 5.1 we should update all that, and if necessary set a link to the Plone 4 docs.

The current situation is possible confusing for user.

**Comment by stevepiercy** [comment]
Done in https://6.docs.plone.org/upgrade/index.html
