### ISSUE TITLE
Add https to docs.plone.org

### ISSUE THREAD

**Issue by svx** [plone/documentation#745]
It is 2017, lets switch to https://docs.plone.org

**Comment by zachwelch** [comment]
+1.  I recently changed all of my sites to HTTPS, thanks to the one-line certificate acquisition/installation process available from the CLI via LetsEncrpyt.  It's trivial to produce new certificates and renewals are automatically handled by a cronjob.

**Comment by tkimnguyen** [comment]
@zachwelch we use CloudFlare for docs.plone.org so it's even easier than that :)

**Comment by tkimnguyen** [comment]
@smcmahon any reason why we shouldn't activate https for docs?

**Comment by svx** [comment]
To make it more clear, this is on my list for the next maintenance window for this server, this ticket is meant as an reminder for my self :)

There are also still some settings which have to be adjusted in the config, since we proxy different domains and such stuff.

Meaning I will do it, there is no actions which needs to be taken by others :)

**Comment by svx** [comment]
done !
