### ISSUE TITLE
Update styleguide: line-length and sentences

### ISSUE THREAD

**Issue by svx** [plone/documentation#747]
Reading over it, we really should update and improve that !

Currently we have for example:

> Each sentence in the documentation can be turned into a .po string.
> Breaking sentences with linebreaks would mean a translator will only see part of the sentence, making it impossible to translate.
> 

Personally I think this is not so cool, do not get me wrong from the technical point of view it is 100% right, but from the point of writing and readability, like reading the docs on your desktop or mobile that is not the best solution.

Possible solution:

- [ ] rewrite it to tell people to 'aim' for sentences which are not longer than 30 words.
- [ ] Shorter is better as long as it is a complete sentence.
- [ ] A sentence fragment doesn't really work.
- [ ] Do the transition slowly, page by page, there is no need to hurry.

This is smoother and easier to read and to translate, too !  

Another advantage will be that Google and Bing liking it [SEO] 

Background info
=============

- https://insidegovuk.blog.gov.uk/2014/08/04/sentence-length-why-25-words-is-our-limit/

- https://www.tu-chemnitz.de/phil/english/sections/linguist/independent/kursmaterialien/TechComm/acchtml/hirev2.html#length

- https://blog.bufferapp.com/optimal-length-social-media

**Comment by stevepiercy** [comment]
Closing as won't fix.
