### ISSUE TITLE
Error in: Overriding a view class in a product

### ISSUE THREAD

**Issue by lukebrannon** [plone/documentation#772]
The Plone 5 documentation for _Overriding a view class in a product_ <http://docs.plone.org/develop/plone/views/browserviews.html#overriding-a-view-class-in-a-product> results in a TypeError:  page() takes at least 4 arguments (5 given).

The error is caused by the layer attribute in the zcml for browser:page
Referencing older packages zcml should be?:

<configure
        xmlns="http://namespaces.zope.org/zope"
        xmlns:browser="http://namespaces.zope.org/browser"
        i18n_domain="example.policy">
      <browser:page
          name="register"
          class=".customregistration.CustomRegistrationForm"
          permission="zope2.View"
          for="Products.CMFPlone.Portal.PloneSite"
          />
    </configure>

> zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/home/someone/Plone/plone51/baseInstance/parts/instance/etc/site.zcml", line 16.2-16.23
    ZopeXMLConfigurationError: File "/home/someone/Plone/plone51/buildout-cache/eggs/Products.ATContentTypes-2.2.13-py2.7.egg/Products/ATContentTypes/configure.zcml", line 18.2-18.44
    ZopeXMLConfigurationError: File "/home/someone/Plone/plone51/buildout-cache/eggs/plone.app.collection-1.2.1-py2.7.egg/plone/app/collection/configure.zcml", line 9.2-9.45
    ZopeXMLConfigurationError: File "/home/someone/Plone/plone51/buildout-cache/eggs/plone.app.querystring-1.4-py2.7.egg/plone/app/querystring/configure.zcml", line 11.2-11.42
    ZopeXMLConfigurationError: File "/home/someone/Plone/plone51/buildout-cache/eggs/plone.app.registry-1.3.12-py2.7.egg/plone/app/registry/configure.zcml", line 12.4-12.34
    ZopeXMLConfigurationError: File "/home/someone/Plone/plone51/buildout-cache/eggs/plone.app.registry-1.3.12-py2.7.egg/plone/app/registry/browser/configure.zcml", line 6.4-6.43
    ZopeXMLConfigurationError: File "/home/someone/Plone/plone51/buildout-cache/eggs/plone.app.z3cform-2.1-py2.7.egg/plone/app/z3cform/configure.zcml", line 10.2-10.41
    ZopeXMLConfigurationError: File "/home/someone/Plone/plone51/buildout-cache/eggs/plone.app.widgets-2.0.6-py2.7.egg/plone/app/widgets/configure.zcml", line 12.2-12.41
    ZopeXMLConfigurationError: File "/home/someone/Plone/plone51/buildout-cache/eggs/Products.CMFPlone-5.1a2-py2.7.egg/Products/CMFPlone/configure.zcml", line 108.4-112.10
    ZopeXMLConfigurationError: File "/home/someone/Plone/plone51/checkouts/git/src/product.membership/src/product/membership/configure.zcml", line 11.2-11.32
    ZopeXMLConfigurationError: File "/home/someone/Plone/plone51/checkouts/git/src/product.membership/src/product/membership/browser/configure.zcml", line 21.2-26.6
    TypeError: page() takes at least 4 arguments (5 given)

**Comment by MrTango** [comment]
This zcml registration expects that you define a template in the view class, did you?
The example could be better though.
This is a better example i thing: https://training.plone.org/5/mastering_plone/views_1.html

**Comment by svx** [comment]
@MrTango should it be a idea to remove the old example and instead link to the training ?

**Comment by fulv** [comment]
Also, shouldn't the `for` attribute point to an interface?

**Comment by lukebrannon** [comment]
@MrTango Since you're sub-classing RegistrationForm shouldn't the template defined there remain valid?

@fulv I wondered about that, but when I tried to reference my interface based on IDefaultPloneLayer the view wasn't overriden.  I will verify that again.

**Comment by lukebrannon** [comment]
@fulv So using my interface as defined in the documentation results in the the view _not_ being overridden.  If I use 'Products.CMFPlone.interfaces.IPloneSiteRoot' the view _is_ overridden. Looking through configure.zcml for plone.app.users, the actual 'register' view is for 'plone.app.layout.navigation.interfaces.INavigationRoot'.

**Comment by fulv** [comment]
My earlier comment was about the for="Products.CMFPlone.Portal.PloneSite".
But if you use IPloneSiteRoot instead of PloneSite, I have no objection.

However, going back to the documentation example:  are you sure you ran the
GenericSetup import step to register the Browser Layer?

**Comment by lukebrannon** [comment]
I've gone back and forth between a few documents and this is what I've found:
[Specify files and code from another package](http://docs.plone.org/develop/addons/components/zcml.html#overrides) provides a correct example of the required zcml.  The documentation in question is missing the _for_ attribute, which causes it to error out and break the instance. The override documentation does provide further explanation on what to do with your custom class, so I think we can just update it with the proper zcml.  The question then becomes which is better practice? To specify the marker interface of the original view, or create your own marker interface which inherits it (and then needs to be marked)? Seems like using the original interface is less intrusive (I should add for the example given (ie the registration form).

**Comment by fulv** [comment]
I think keeping the original interface is better in the context of this doc.  Defining your own interface would be a different use case, i.e. making a specialized browser page that only applies to more specific contexts that provide your interface.

Referring back to the beginning of this thread, the `layer` attribute is essential, as it is the one discriminant that allows your overridden browser page to be registered.  Without it, you would get a conflict error when Zope starts.

Thanks for sleuthing!

**Comment by lukebrannon** [comment]
Thanks @fulv.  I've [updated](https://github.com/plone/documentation/compare/lb_overideClassView)  my branch accordingly and added a note about the permission and marker interface.
