### ISSUE TITLE
Improve docs structure

### ISSUE THREAD

**Issue by svx** [plone/documentation#776]
Currently we serve *external* parts like dexterity and others under */external*.

IMHO we should adjust that in order to get rid of */external*.

Reasons:

- */external* unnecessary for user
- */external* is confusing for user
- */external* is not needed at all

Solution:

- [ ] adjust 'pull' location of docs we fetch [needs to be done in papyrus]
- [ ] adjust nginx [301] to make sure that links are still working 

@polyester what do you think ?

We do not need to rush that, IMHO if we do that with papyrus 1.5 it would be fine.

**Comment by svx** [comment]
Linked to: https://github.com/plone/papyrus/issues/144

**Comment by stevepiercy** [comment]
Closing as won't fix. We're moving toward Diátaxis Framework and we use git submodules now.
