### ISSUE TITLE
Header size in 5.1 upgrade docs is confusing

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/documentation#780]
Pull request #743 by @svx at the end of last year changed various headers, plus other stuff.
The [5.1 upgrade docs](https://github.com/plone/documentation/blob/5.1/develop/addons/upgrade_to_51.rst) have suffered a bit there I think. The page has a title "Upgrade a custom add-on to Plone 5.1" at level `h1` and then all other section headers are at `h2`.  But all those sections are about one plip, my QuickInstaller plip.

I think it should be one section "Installation code" at level `h2` and all others at `h3`.  This leaves room for more upgrade notes for other plips at the `h2` level.

Options:
1. Indeed keep "Installation code" at `h2` (`========`) and move all others to `h3` (`-----------`).
2. Since these QuickInstaller upgrade docs are so large, move them to a separate file.

I am happy to implement either of those options.
Do you have a preference, or a better idea?

BTW, I am about to write some documentation about the [retina plip](https://github.com/plone/Products.CMFPlone/issues/1483), which is why I noticed this.
Please feel free to bug PLIP implementers about missing upgrade documentation.

**Comment by svx** [comment]
@mauritsvanrees adjusted with: https://github.com/plone/documentation/commit/46f1605b9670e6ee3f24b7b4cd4d1a4d4d58f010

**Comment by mauritsvanrees** [comment]
Perfect, thank you!
