### ISSUE TITLE
Developer docs about GenericSetup should be split

### ISSUE THREAD

**Issue by svx** [plone/documentation#782]
Great that we have these awesome docs, but :)
currently the docs about GenericSetup (/develop/addons/components/genericsetup.rst) are too long.

In order to enhance readability we should split these one huge long file into shorter parts [chapters].

As rule of thumb it is always handy, to aim for a file which is not longer than 1000 lines [which is already long]

**Comment by stevepiercy** [comment]
Closing as won't fix, as we have adopted the Diátaxis Framework for structure of docs.
