### ISSUE TITLE
add docs on plone.app.discussion

### ISSUE THREAD

**Issue by tkimnguyen** [plone/documentation#794]
...as per https://community.plone.org/t/forum-board-extension-for-plone/3619/10

**Comment by svx** [comment]
@tkimnguyen 

I see here some challenges :)

- having the same info on two different places maybe confusing
- having the same info on two different places is hard to keep up to date
- having the same info on two different places under the same main domain (plone.org) is not so cool for seo 

I completely agree with you we **should** have this **awesome** docs somewhere, **thank you again for taking the time and write them !!!**

I am just not sure yet what would be the best approach in the long run, cause we should also keep in mind that hopefully more people add docs like this, too !

**Comment by MrTango** [comment]
It makes sense to improve the PAD docs, but th step by step example for the forum, is a tutorial and should go into the training docs.

**Comment by svx** [comment]
I am in favor of a own 'tutorial repo'

This way you have more freedom to come up with a good and smart structure and setup without depending on already existing and slightly unclear structure, see https://github.com/plone/training/issues/253

**Comment by tkimnguyen** [comment]
Yeah I wasn't intending to keep the same info in two places... (p.a.d. could use its own docs but I wasn't thinking about that). I was thinking that docs.plone.org should at least explain the feature, how to enable it, how it works. training.plone.org should include the tutorial I started in the forum.

**Comment by stevepiercy** [comment]
@tkimnguyen I'm closing this issue as stale. Feel free to migrate that tutorial into a new directory under `docs/`, assuming it is still useful. We now use MyST and Markdown and have a shiny new theme. Let me know if you need any help with that.
