### ISSUE TITLE
Update dev docs about portlets

### ISSUE THREAD

**Issue by svx** [plone/documentation#798]
[This needs an update](https://docs.plone.org/develop/plone/functionality/portlets.html):

- even if it mentioned that paster is deprecated, we should remove all paster stuff and rewrite the docs to show bob template examples

- needs check if info about Plone 4.1 can be removed or should updated to Plone to 5.1

Example:
![portlet_docs_old_info](https://cloud.githubusercontent.com/assets/358860/23801473/9003dd04-05b0-11e7-9886-b9a1acd9d290.png)

**Comment by stevepiercy** [comment]
Closing as won't fix.
