### ISSUE TITLE
docs unclear about where to put code

### ISSUE THREAD

**Issue by iham** [plone/documentation#801]
https://docs.plone.org/develop/plone/i18n/translating_content.html#native
**where is "in your code"?**

making a field languageindependent is pretty standard, but having 4! ways to do that is confusing on the one hand and gets frustrating, if the docs don't tell how in every case.

btw: trying to make a field language independent only for one plone instance (based on a "policy package") is not possible, i guess. the model.xml seemed to offer a way to do that, but didn't work...

**Comment by stevepiercy** [comment]
This probably has been solved. If not, please reopen with sufficient details.

See https://6.docs.plone.org/i18n-l10n/index.html
