### ISSUE TITLE
Improve: Docs about how to contribute

### ISSUE THREAD

**Issue by svx** [plone/documentation#802]
We should tell:

- send better a couple of small PRs than one huge one
- give nice examples, like a gist with a git-hook or so, and explain people to run local tests, this should be not to heavy, like not use my own setup as example, since We do not want to scare people.

**Comment by tomgross** [comment]
And: Give instructions on how to build the documentation locally.

**Comment by loechel** [comment]
@tomgross I have made a pull request that makes it possible and easy to build the docs locally --> #920 

Might one of you have a look and review?

**Comment by stevepiercy** [comment]
Also requested in https://github.com/plone/documentation/issues/822#issuecomment-295663293

**Comment by stevepiercy** [comment]
See Contributing in Plone 6 docs (temporary URL): https://6.dev-docs.plone.org/contributing/index.html
