### ISSUE TITLE
Check: Server preparation docs

### ISSUE THREAD

**Issue by svx** [plone/documentation#803]
We should check:

https://5.docs.plone.org/manage/deploying/preparing.html

For example I am not sure about the current state of the Fedora part.
Do you need to install python2.7 and python2.7-dev on the latest Fedora versions ?

**Comment by gforcada** [comment]
According to [Fedora 23 release notes](https://docs.fedoraproject.org/en-US/Fedora/23/html/Release_Notes/sect-Release_Notes-Changes_for_Developers.html) it switched to python3 by default, and thus, you *do* need to install python2.7 manually

**Comment by newbazz** [comment]
I would like to get a bit more information on this issue and would like to work on this issue.

**Comment by svx** [comment]
This issue is about checking, if the documentation at https://docs.plone.org/manage/deploying/preparing.html is still up to date.

This part of the docs was written some time ago, when the mentioned Operating Systems still had Python 2.7 as default Python.

Besides the version of Python it may be possible that names of packages got changed.

As you can see already in the comment above, this document is not correct for Fedora and also for Ubuntu for example, since these do not ship Python 2.7 as default Python anymore.

This ticket is about verifying the packages (dependencies) you need for installing Plone on the mentioned Operating Systems.

**Comment by newbazz** [comment]
okk so is there anything to be updated at present?

**Comment by svx** [comment]
Most certainly yes, as @gforcada already wrote, the Fedora part is outdated.

If you decide to take this issue and work on it, you need to install Plone on the mentioned Systems.

Steps to do (example for Fedora):

* Download the latest Fedora
* Install latest Fedora (VirtualBox or something else)
* Follow the docs on https://docs.plone.org/manage/deploying/preparing.html to try to install Plone.
* Fix possible issues, like installing Python 2.7
* Document your steps, what you had to do to install Plone
* Create a branch of the docs
* Update you branch with your findings, like ``dnf install python2.7`` (example)
* Create a Pull Request
* Have fun !

**Comment by newbazz** [comment]
ooh thats quite difficult I want to try an easier issue at first.

**Comment by stevepiercy** [comment]
Superseded by https://github.com/plone/documentation/issues/1647
