### ISSUE TITLE
Minimal build section in requirements?

### ISSUE THREAD

**Issue by jensens** [plone/documentation#807]
Why do we have the minimal build section under installation-requirements? To me, this is a bit misplaced.

https://docs.plone.org/manage/installing/requirements.html#minimal-build

**Comment by svx** [comment]
Yeah I know ... :)

BTW, we have already a [ticket](https://github.com/plone/documentation/issues/758) for that :) and for https://github.com/plone/simple-plone-buildout/issues/1.

Currently we give people two different options/examples which is/could be confusing, the second one is btw mentioned on plone.org.

We should fix that soon to avoid misunderstandings cause docs.plone.org differs currently from the info on plone.org.  

Thanks for reminding !

**Comment by tkimnguyen** [comment]
Yes we need to axe this from https://docs.plone.org/manage/installing/requirements.html
