### ISSUE TITLE
Term "Retina" ok in docs?

### ISSUE THREAD

**Issue by jensens** [plone/documentation#812]
see https://github.com/plone/documentation/pull/781

**Comment by svx** [comment]
Hm, good one, according to https://en.wikipedia.org/wiki/Retina_Display this is really a Apple thing, they even have the copyright for the name "Retina display".

Could/should we add "High Resolution Displays" ?

**Comment by polyester** [comment]
the most used term (that I've seen used in computer magazines, websites, etc and increasingly also in Linux and Windows manuals) is HiDPI. Yes, that would deserve an entry in the glossary...

**Comment by fgrcon** [comment]
should also be changed in  imaging control panel ...

**Comment by svx** [comment]
OK steps to do:

- create pr to fix that in  imaging control panel
- update docs

Should I forgot something ?
