### ISSUE TITLE
contact form customization page is out of date

### ISSUE THREAD

**Issue by tkimnguyen** [plone/documentation#813]
https://github.com/plone/documentation/blob/5.1/develop/plone/functionality/contactform.rst is no longer correct. It is not possible to customize the contact form that way because Plone 5 no longer uses PTs and CPTs. 

It is also currently not possible to customize the contact form TTW, EXCEPT maybe by

- injection of JavaScript
- CSS trickery
- Diazo theme tomfoolery

**Comment by tkimnguyen** [comment]
Oh it's as easy with Diazo tomfoolery as I'd hoped!

```
  <!-- change wording of contact form and thank you -->
  <rules if-path="/contact-info">
    <replace css:content="#content > div > div.documentDescription">
        <div class="documentDescription">Fill in this form to book Joey!</div>
    </replace>
    <replace css:content="#content > div > p">
        <p class="documentDescription">Thank you for contacting me – I will get back to you as soon as I can!</p>
    </replace>
    <replace css:content="#global_statusmessage > div.portalMessage.info">
        <div class="portalMessage info">
            <strong>Info</strong>
                An email has now been sent to Joey
            </div>
    </replace>
  </rules>
```
Changing the instructions at the top of the form:

![contact-form-tweaking-1](https://cloud.githubusercontent.com/assets/815418/24231937/5a4bcb8c-0f55-11e7-83b4-6a6a5115f449.jpg)

Changing the status message and the thank you message:

![contact-form-tweaking-2](https://cloud.githubusercontent.com/assets/815418/24231939/5e1de4fc-0f55-11e7-903c-f597bd7c6f81.jpg)

**Comment by stevepiercy** [comment]
@tkimnguyen is this issue relevant for Plone 6? If not, then let's close it. If it is, then let's change the label `99 tag: Plone 5.x` to `99 tag: Plone 6.x` so it gets some attention from whoever might use it and create a PR for it.

**Comment by stevepiercy** [comment]
Closing as no follow up from @tkimnguyen. Please reopen if you have details.
