### ISSUE TITLE
PLIP Documentation needs update as issuetemplate.com has gone.

### ISSUE THREAD

**Issue by loechel** [plone/documentation#815]
https://docs.plone.org/develop/coredev/docs/plips.html#how-to-submit-a-plip stated to use http://issuetemplate.com/#/plone/Products.CMFPlone/PLIP to produce a new PLIP. This service has gone and it seems there is a new way, to just create an issue in Products.CMFPlone and you get a prefilled issue for bug or PLIP.

**Comment by loechel** [comment]
This specific part of documentation is pulled from buildout.coredev, I have updated the documentation there on the 5.1 branch.

Please close this issue when the next docs export has fixed it.

**Comment by svx** [comment]
Sorry for the delay, busy times and finally better weather :)

In:

> Whether you want to update the default theme or rip out a piece of architecture, everyone should go through the PLIP process. If you need help at any point in this process, please contact a member of the framework team personally or ask for help on the Framework Team mailing list.

I would remove the link to the mailing list and replace it with a link to the right topic on community.plone.org

And here:
> A PLIP is just a GitHub issue on Products.CMFPlone with a special template and a specific tag. To get started, open a new issue, the issue will be prefilled with headings and comments for a bug or a PLIP, remove the bug part. Fill in all applicable fields. After submitting, select the tag "03 type: feature (plip)" for the issues.

I would remove 'just' and set 'GitHub issue' as link to the issue tracker and 'Products.CMFPlone' as link to the repository on GitHub.

**Comment by loechel** [comment]
Tried to apply your requested changes on https://github.com/plone/buildout.coredev/commit/918a6b2201c80f66dc4feecbbe6bdcce03015455 but did not changed link to mailinglist. This maybe should the Framework team consider.

**Comment by svx** [comment]
Hello @plone/framework-team can you please give your 2c about mailing list, community.plone.org or both ?

**Comment by gforcada** [comment]
IMHO (although I'm part of the framework team) pointing to community.plone.org should be the right thing to do. We are trying to move everything there.

As for the issue template, @jensens made an issue template for CMFPlone, so the link to that should point to the CMFPlone github issue tracker.

**Comment by svx** [comment]
Done, with https://github.com/plone/buildout.coredev/commit/d5cc69ec51e156ff58248db09b80e73afa70001c

**Comment by gforcada** [comment]
Closing this then? or there is more to add/fix?

**Comment by loechel** [comment]
The initial issue is fixed and this ticket should be closed, 

@svx issue that there is still a link to the @plone/framework-team mailing list in this documentation and that it should point instead to community.plone.org might need a new ticket.

So closed for now.
