### ISSUE TITLE
Create a setup for 'terminals'

### ISSUE THREAD

**Issue by svx** [plone/documentation#823]
Create a setup, with vagrant, docker or something else, which we use for "screen-shots of terminals"

The goals is that all terminal pictures use the same configuration and with that looking the same, this would be a great improvement for how the docs visual looks like.

**Comment by gforcada** [comment]
Is there any tooling for doing that?

**Comment by svx** [comment]
Not that I am aware off, but I had also no time looking for it or writing something, yet

**Comment by svx** [comment]
@gforcada I use now a custom zsh terminal for that, works great !

Let see if I can put that into a container, snap, flatpak or what ever :)

You can find an example on https://github.com/testthedocs/ttd-textlint, works great for gifs, too

**Comment by stevepiercy** [comment]
Superseded by https://github.com/plone/documentation/issues/1611
