### ISSUE TITLE
Duplicated best practices?

### ISSUE THREAD

**Issue by gforcada** [plone/documentation#826]
I stumbled upon this docs https://github.com/plone/buildout.coredev/blob/5.1/docs/documentation.rst that are pulled in on https://docs.plone.org/develop/coredev/docs/documentation.html

I think @svx did wrote some guidelines on README.rst and CHANGES.rst somewhere else, so should we rather have that file just point there or is this one in buildout.coredev still relevant?

**Comment by svx** [comment]
I am for pointing to our writing guideline, the one in buildout.coredev is old and telling things we are not doing anymore, like singe docs in README.

**Comment by gforcada** [comment]
@svx where are the guidelines then? I can create the pull request if you don't have the time to.

**Comment by stevepiercy** [comment]
These are now published for Plone 6 at: https://6.dev-docs.plone.org/contributing/index.html This is a temporary host name until Plone 6 is out of beta.
