### ISSUE TITLE
Broken link to Archetypes Developer Manual

### ISSUE THREAD

**Issue by tobiasherp** [plone/documentation#829]
On https://docs.plone.org/4/en/develop/plone/searching_and_indexing/indexing.html#creating-a-metadata-column, there is a link to https://plone.org/documentation/manual/developer-manual/archetypes which doesn't work. Please update the link or migrate the contents. Thank you!

**Comment by svx** [comment]
Fixed with https://github.com/plone/documentation/commit/d023b0e077226534bce7559abfb1a3a904ec6703

Please note, it will take some time, till we build and push the docs again.

**Comment by gforcada** [comment]
@svx what's the @plone/documentation-team policy on these reports? Close them as soon as it is merged or someone reviews all open tickets when docs are pushed and thus the end user can see that bug that has been fixed already on docs.plone.org?

**Comment by tobiasherp** [comment]
@gforcada I'd prefer the latter.

**Comment by tobiasherp** [comment]
Btw, there are _lots_ of broken links in the docs (I just found two more in https://docs.plone.org/4/en/develop/addons/components/events.html#creation-events), and this makes it somewhat difficult to find relevant information. Wouldn't it be possible to have HTTP redirections additionally (as generic as possible; 301 status), e.g. to have https://plone.org/documentation/manual/developer-manual/archetypes redirected to https://docs.plone.org/develop/plone/content/archetypes?

**Comment by stevepiercy** [comment]
Closing as won't fix. We no longer support v4.x.
