### ISSUE TITLE
Misleading information about navigation menu

### ISSUE THREAD

**Issue by ghost** [plone/documentation#834]
https://docs.plone.org/working-with-content/introduction/visual-design-of-plone.html mentions:

In the default design, the navigation menu is in the left area, and usually appears as an indented list of folders in the site. 

The default Plone5 design, does not have the navigation menu on the left area. 

Maybe better to write: In this example, the navigation menu.... ?

**Comment by ghost** [comment]
Further down we also mention:

We'll use the default Plone layout design as an example of typical divisions of the screen:

Maybe remove sentence completely?

**Comment by ghost** [comment]
Sorry for the multiple edits here:
This is also not correct, since left and right columns do not appear in the new standard.

So, what does a Plone web site look like? Traditionally, the out-of-the-box look is like that shown at the top of this page, with header, menu, columns, and a footer.

**Comment by svx** [comment]
@polyester ping !

**Comment by polyester** [comment]
oops. this is one of the oldest parts of the docs. It really needs updating, and some of it is not that relevant anymore in the age of phones/tablets and responsive design. I can see if I can get some input from theming experts (hi David, Oshane, Chrissie, Rob) to make it more up-to-date

**Comment by stevepiercy** [comment]
Closing as won't fix. Plone 5 is out of support.
