### ISSUE TITLE
Adding Images

### ISSUE THREAD

**Issue by ghost** [plone/documentation#835]
https://docs.plone.org/working-with-content/adding-content/adding-images.html does not contain a correct, current image. Find attached a up to date screenshot.
![selection_002](https://cloud.githubusercontent.com/assets/1036076/25376178/9839cec2-29a3-11e7-9288-d1e0437d9478.png)

**Comment by svx** [comment]
We do [most of] our screen-shots with robot-framework.

This certain image is done with it, meaning, next time we build the 5.1 branch of the docs we do have a up to date screen-shot.

:)

**Comment by ghost** [comment]
Ok, thanks for the information. Didn't know about that.
