### ISSUE TITLE
Update contributing with more info about images

### ISSUE THREAD

**Issue by svx** [plone/documentation#837]
Explain that we do certain images with robot-framework and such stuff.

**Comment by stevepiercy** [comment]
References: https://github.com/plone/documentation/issues/822#issuecomment-295943326 and #984

We have something for _manually_ adding images in the [Documentation Styleguide](https://docs.plone.org/about/contributing/documentation_styleguide.html?highlight=images#documentation-structure), but I couldn't find anything about the automatic generation of screenshots via robots. How does a new contributor know when to add an image manually versus letting the robot take a screenshot automatically?

**Comment by stevepiercy** [comment]
Closing as won't fix. We currently do not automatically generate screenshots in Plone 6 docs. We might add it in the future, but there are no plans to do so.
