### ISSUE TITLE
add advice on using namespaces in diazo themes

### ISSUE THREAD

**Issue by polyester** [plone/documentation#85]
a number of Diazo themes have issues with things like pop-up modals and ajax. The cause is usually that css class-names collide, and therefore inadvertently trigger Diazo rules.

We should include in the themer documentation a hint / best-practice to use namespaced classnames in their themes. So, instead of 'body' or 'content' use 'mytheme.body' and 'mytheme.content' to avoid conflicts.

**Comment by stevepiercy** [comment]
Closing as stale.
