### ISSUE TITLE
404 in manage/deploying/wsgi.rst

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#865]
In https://github.com/plone/documentation/blame/5.1/manage/deploying/wsgi.rst#L22 the URL returns a 404 error.

```rst
`Plone 5 with WSGI <http://blog.toms-projekte.de/run-plone-with-wsgi.html>`_
```

I don't know of a valid replacement, else I'd submit a PR.

**Comment by svx** [comment]
@tomgross Could it be that your blog is offline ?

We should remove th e Plone 4 link from this site

**Comment by svx** [comment]
This is fixed !
