### ISSUE TITLE
Improve /about - user feedback from the sprint

### ISSUE THREAD

**Issue by svx** [plone/documentation#898]
List of suggestions after some user testing

- [ ] better and more friendly intro with focus on different audiences like 'first timer' and 'more experienced' ppl
- [x] mention in the beginning that you do not have to be a developer
- [x] make it less intimidating
- [ ] add screen-shots 
- [ ] explain better git fork and git branch
- [x] rewrite part about using GitHub online, it is a bit confusing atm, say something like:
"editing docs online on GitHub"

- [x] better listing and overview about steps

**Comment by svx** [comment]
@rioksane was that all or did I forgot something ?

**Comment by stevepiercy** [comment]
Closing as obsolete
