### ISSUE TITLE
JavaScript / Mockup documentation best practice

### ISSUE THREAD

**Issue by thet** [plone/documentation#903]
I added these docs to the mockup repository:

https://github.com/plone/mockup/blob/master/mockup/patterns/structure/README.rst
https://github.com/plone/mockup/pull/785

It's about how to customize the structure updater pattern.

I think, having docs besides each pattern is good practice (Patterns also do so. See: https://github.com/Patternslib/Patterns/blob/master/src/pat/gallery/documentation.md ). But placing the docs where I did in PR https://github.com/plone/mockup/pull/785 does not really follow the Mockup practice. Also it's not Markdown but ReStructredText.
An option would be to place the docs on the same level like https://github.com/plone/mockup/blob/master/mockup/GETTING_STARTED.md
Having them in the plone/documentation repository is another option.

I don't have a strong opinion here. Maybe it's time to think about restructuring the Mockup docs?

Let's discuss this, @plone/documentation-team

**Comment by thet** [comment]
Stale issue. JS‌ docs have to be updated or even rewritten for Plone 6 anyways.

**Comment by stevepiercy** [comment]
@thet would you please create a new issue for Plone 6 that provides any direction for what needs to be documented or rewritten? Please include where you would suggest it be placed in the new docs structure. I assume this is for [Classic UI](https://6.docs.plone.org/classic-ui/index.html)?

**Comment by stevepiercy** [comment]
Superseded by #1270
