### ISSUE TITLE
Change travis config

### ISSUE THREAD

**Issue by svx** [plone/documentation#907]
Since we are moving robot-test to CMFPlone IMHO we can now adjust travis so that we can stop using circleci.

Currently we use circeci for qa tests of the docs, this was setup because we use a somehow old travis setup for the docs.

I would like to cleanup the repo and also having less moving parts is always nice.

@polyester what is the status of the move ? Should I wait with adjusting travis ?

AFAIK we're not really using travis since some time, right ?

**Comment by polyester** [comment]
@svx I've completed the move, in so far as that

- it works, save for some issues with making screenshots of popups, phantomjs has problems with that, and Firefox is in flux with their webdriver so on Linux is not a good alternative until the next version of Firefox comes out. They are small issues, however, when needed for production I could create those 2 screenshots by hand.
- Pull request is ready, waiting for review/merge https://github.com/plone/Products.CMFPlone/pull/2109

What remains to be done:

- update the docs on papyrus on how to generate screenshots. There is documentation at  Products.CMFPlone/Products/CMFPlone/tests/robot/robodoc/README.rst

**Comment by svx** [comment]
Done !

Old travis got removed by: https://github.com/plone/documentation/issues/934
