### ISSUE TITLE
broken links to svn.zope.org

### ISSUE THREAD

**Issue by tkimnguyen** [plone/documentation#909]
as per thread in https://community.plone.org/t/change-template-to-require-auth/4453/7 the page at https://docs.plone.org/develop/plone/security/permission_lists.html#id3 has broken links to svn.zope.org

**Comment by svx** [comment]
Does anyone has an idea on where to link ?

**Comment by tkimnguyen** [comment]
OK here are the 4 links to change:

- http://svn.zope.org/Products.CMFCore/trunk/Products/CMFCore/permissions.py?rev=94487&view=markup -> https://github.com/zopefoundation/Products.CMFCore/blob/master/Products/CMFCore/permissions.py 
- http://svn.zope.org/Zope/trunk/src/AccessControl/Permissions.py?rev=96262&view=markup -> https://github.com/zopefoundation/AccessControl/blob/master/src/AccessControl/Permissions.py

- http://svn.zope.org/Zope/trunk/src/Products/Five/permissions.zcml?rev=99146&view=markup -> https://github.com/zopefoundation/Zope/blob/master/src/Products/Five/permissions.zcml but it's been moved... looking

- http://svn.zope.org/zope.security/trunk/src/zope/security/permissions.zcml?rev=97988&view=markup -> https://github.com/zopefoundation/zope.security/blob/master/src/zope/security/permissions.zcml

**Comment by svx** [comment]
@tkimnguyen I updated the links, for now I also put

``
https://github.com/zopefoundation/Zope/blob/master/src/Products/Five/permissions.zcml but it's been moved... looking
``
there.

**Comment by tkimnguyen** [comment]
Thx @svx ! @jaroel replied at https://community.plone.org/t/old-svn-zope-org-links-in-docs-for-available-permissions-in-plone/5459/2 with:

```
The cmf.* permission pseudo constants are in 

https://github.com/zopefoundation/Products.CMFCore/blob/master/Products/CMFCore/permissions.py

The zope.View etc are in 

https://github.com/zopefoundation/AccessControl/blob/master/src/AccessControl/permissions.zcml

Most of the permissions in Products.Five have been moved to Products.CMFCore per 

https://github.com/zopefoundation/Zope/commit/6a802960f6f7d0b39889278c3a01a982ac886e2c#diff-f86ca931a79aa3dfeefbf0659f69561c 

, so that link could be removed.

**Comment by svx** [comment]
@tkimnguyen sorry I do not get you ?

What do you mean with your latest comment, is there more work needed or can we close this issue ?

**Comment by tkimnguyen** [comment]
Sorry @svx I have to re-read this too... Roel gave additional clarifications that I think addressed the 3rd link that I wanted to do more research on

**Comment by Rupeshiya** [comment]
@tkimnguyen  is this resolved ??

**Comment by tkimnguyen** [comment]
thanks @svx I think this is enough. @Rupeshiya yes, it was merged a while ago. you can see the results in https://docs.plone.org/develop/plone/security/permission_lists.html#id3
