### ISSUE TITLE
Inconsistencies on VCL subroutine vcl_backend_response

### ISSUE THREAD

**Issue by cleberjsantos** [plone/documentation#910]
- Based in _Varnish_ documentation, we're using a variable in the wrong way. The **req** variable cannot be used in VCL subroutine **_vcl_backend_response_**.
See. [Variable Availability in VCL subroutines](http://book.varnish-software.com/4.0/chapters/VCL_Basics.html#variables-in-vcl-subroutines)

- Does not necessary set headers for make sure that _Varnish_ does not accidentally caching error pages. For this we can simply abandon the backend request using the return action: **return (abandon);**

**Comment by svx** [comment]
Fixed with https://github.com/cleberjsantos/documentation/commit/e94fe8c990728bc3db7f501d4ae61d3fa3ead5f4
