### ISSUE TITLE
Search function improvements

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#912]
The search function for the documentation frustrates me for the following reasons. Refer to the screenshot.

![plone-search](https://user-images.githubusercontent.com/102112/29246040-5a21d158-7fa1-11e7-9a2f-5f7d1d1d3938.png)
* Results are inaccurate
* Results appear in a drop-down menu which disappears when clicked, taking the user to that document, forcing the user to re-enter their search term when what they click is not what they really want
* The drop-down is obscenely huge, showing only a few results
* There is no description of the content, other than the title of the found document
* It's very un-Sphinx-like or _insert search engine here_-like, where a list of results are displayed and the user can preserve their search results by opening a link in a new tab or window

For now, I use something like this:
https://duckduckgo.com/?q=site%3Ahttps%3A%2F%2Fdocs.plone.org%2F+thing
![duckduckgo-search](https://user-images.githubusercontent.com/102112/29246045-7e6917ec-7fa1-11e7-8f01-3a9ff5e19ecc.png)

**Comment by svx** [comment]
This got fixed in the latest theme updates. Closing this
