### ISSUE TITLE
document how to edit the footer

### ISSUE THREAD

**Issue by tkimnguyen** [plone/documentation#915]
as per https://github.com/plone/Products.CMFPlone/issues/2128 in Plone 5.0.7 editing the footer requires a convoluted use of the ZMI. See https://community.plone.org/t/change-the-footer/4776/2

We should document this better as a short term solution. In the long term it's possible that Plone will go to a tiles & layouts solution (similar to Castle).

**Comment by svx** [comment]
OK @tkimnguyen according to https://community.plone.org/t/change-the-footer/4776/6 we need to update the docs and add screens to fix that for 5.1 right ?

@polyester are you up for writing a robot-screen for that ? :)

**Comment by tkimnguyen** [comment]
I think so, @svx

**Comment by svx** [comment]
@tkimnguyen OK
Who is willing to take that on ? 


Would be nice to have that in the docs for the upcoming 5.1 release !

:)

**Comment by tkimnguyen** [comment]
I can't promise I'll have it done right away but am willing to try

**Comment by svx** [comment]
Awesome !  Excellent ! Thanks !

**Comment by stevepiercy** [comment]
Closing as obsolete.
