### ISSUE TITLE
Add reference-labels for cross-referencing arbitrary locations

### ISSUE THREAD

**Issue by svx** [plone/documentation#916]
To support cross-referencing to arbitrary locations in any document, the standard reST labels are used. For this to work label names must be **unique throughout the entire documentation**. There are two ways in which you can refer to labels:

If you place a label directly before a section title, you can reference to it with :ref:`label-name`. Example:
```
.. _my-reference-label:

Section to cross-reference
--------------------------

This is the text of the section.

It refers to the section itself, see :ref:`my-reference-label`.
```

This is handy for local use, as in the example above and for the Sphinx intersphinx extension

## Example

We have a training called *Plone Hosting On Kubernetes*, this training has a file called *index.rst*

```rst

=====
Plone 
=====

Please make sure to read :ref:`plonedocs:plone-requirements`

```

This would link to https://docs.plone.org/manage/installing/requirements.html, because in the reSt source of this file, we would have

```rst

.. _plone-requirements:

===============================
Plone Installation Requirements
===============================
```

This would work, because we have the following configuration setting in the *conf.py* of the Kubernetes Training

```python
intersphinx_mapping = {
    'plonedocs' : ('https://docs.plone.org/', None)
}
```

**Comment by stevepiercy** [comment]
See https://6.docs.plone.org/contributing/documentation/myst-reference.html#cross-references
