### ISSUE TITLE
Rectify our broken documentation

### ISSUE THREAD

**Issue by tobiasherp** [plone/documentation#918]
It is sometimes quite difficult to find Plone documentation, especially when looking for topics which have lost the love of those who develop Plone 5. There are people around, including me, who'd love to switch to Plone 5 but are not able to do it _now_ because they have a complex Plone 4.3 installation to handle.

We have many broken links because several hosts and addresses have been dropped during the lauch of https://docs.plone.org. This new documentation site might be quite cool, but it doesn't contain the complete content which was available in the old places.

So, here is my suggestion:

- Resurrect the old hosts and paths, including (but not necessarily limited to):
  - https://develop.plone.org
  - https://plone.org/documentation
  - ...
  Surely there are backups which could be used as a last resort, right?
- Remove harmful redirections, like `^/products` --> `/download` (and, in fact, any redirection of a `/path/with/sub/pages` which doesn't preserve the `/with/sub/pages` information).
- Create a page which gives a rough overview about the URL changes.
- Place a hint on all of these resurrected pages which tells about https://docs.plone.org in general, and includes a hyperlink to that overview page.
- Find or develop a module which allows to collect and use suggestions about new locations:
  - Build a table which contains all new documentation pages.
  - Zope can traverse subpaths; e.g., a `documentation` script in the root can check a RDB for information about redirections for `documentation` and the given subpath information.
  - Any logged-in user of https://develop.plone.org, https://plone.org and the like (SSO solution at hand)? can suggest the new location which could be used as a redirection target (301)
  - Administrators can approve such suggestions;
  - approved URLs can be used for redirections.
  - For pages which have parents with known new locations, display a hint which tells about that fact and includes a hyperlink.
  - Since the old pages very likely refered to Plone 4 or ealier, make those redirections point to Plone 4 versions.
- Find new locations for old contents like e.g. https://docs.plone.org/4/products/example.archetype/ (previously https://plone.org/documentation/4/products/example.archetype/?), and establish redirections (using the mentioned module) one by one.

Currently redirections are managed in the SCM, and suggestions involve pull requests. We need a much ore agile solution.

**Comment by stevepiercy** [comment]
Plone 6 docs uses `linkcheck` now. Closing.
