### ISSUE TITLE
Rename branches

### ISSUE THREAD

**Issue by svx** [plone/documentation#932]
As discussed during the conference, we will be rename the branches of docs and the papyrus.

New naming schema:

master: will be the 'unstable' aka 'latest' branch

According to releases we cut branches to/for pin releases.

Todo:

- rename 5.1 to master
- make sure the new master is in sync with versions from CoreDev
- create a 5.1 branch **when** we build and release the docs, adjust versions of stuff we include

**Comment by svx** [comment]
Ok so to recap, the idea is that the master branch of the docs is always is sync with the master of CoreDev.

With that we can also create builds of the latest aka not stable released docs.
People are asking for this since a long time, cause it make it easier to work on docs for upcoming versions, you can compare them online next to each other etc.

With that we will be able to follow the same schema of naming like it is in use by RTD and others meaning:

docs.plone.org
docs.plone.org/latest
docs.plone.org/VERSION

One thing we should keep in mind, that could be confusing if we change from our current schema to that one.

We possible can catch that with the improved version switcher ?

**Comment by stevepiercy** [comment]
In addition to the switcher, we provide BFDs (Big Friendly Disclaimers) and BFBs (Big Friendly Buttons) on Pyramid docs:

https://docs.pylonsproject.org/projects/pyramid/en/master/
https://docs.pylonsproject.org/projects/pyramid/en/1.8-branch/

And the latest, stable branch is at:
https://docs.pylonsproject.org/projects/pyramid/en/latest/

A switcher for Plone would need to account for changes where pages go away between versions.

**Comment by stevepiercy** [comment]
Closing as superseded by https://github.com/plone/documentation/issues/1140
