### ISSUE TITLE
Remove grok in Vocabularies

### ISSUE THREAD

**Issue by jensens** [plone/documentation#936]
https://docs.plone.org/develop/addons/schema-driven-forms/customising-form-behaviour/vocabularies.html

**Comment by jensens** [comment]
omg, there are so many mentions of grok in the docs if it comes to vocabularies. also, we should have one good doc on vocabs instead of 3

- https://docs.plone.org/develop/addons/schema-driven-forms/customising-form-behaviour/vocabularies.html
- https://docs.plone.org/develop/plone/forms/vocabularies.html
- https://docs.plone.org/external/plone.app.dexterity/docs/grok/advanced/vocabularies.html

**Comment by newbazz** [comment]
can you please elaborate what the issue is?

**Comment by jensens** [comment]
we do not use Grok any longer (it is deprecated in Plone). So all examples in the documentation need to be *ungroked*.

Example:

```
@grok.provider(IContextSourceBinder)
def availablePizzas(context):
```
becomes
```
from zope.component import provider

@provider(IContextSourceBinder)
def availablePizzas(context):
```

or 

```
class RegistrySource(object):
    grok.implements(IContextSourceBinder)
```
becomes
```
from zope.interface import implementer

@implementer
class RegistrySource(object):
```

Does it make sense to you?

**Comment by newbazz** [comment]
yup it does! so what are the files I need to make changes into?

**Comment by jensens** [comment]
good question! 
see the links above? The first two are in the structure of this repository in this folder (and subfolder) https://github.com/plone/documentation/tree/5.1/develop

I just found the last one is no longer an issue as we already removed the old explanation.

Btw.: In order to contribute you need to sign the *Plone Contributor Agreement* - which is very simple. It's about the legal stuff (do not ask me details). For more information consult https://plone.org/foundation/contributors-agreement

**Comment by tulikavijay** [comment]
No one seems to be working on this issue, I would like to take this up.

**Comment by svx** [comment]
@tulikavijay sure ! Excellent ! Awesome ! Thanks !

Just assign the issue to yourself and go ahead !

Thanks again !

**Comment by svx** [comment]
@tulikavijay Just to make sure, you already signed the  Plone Contributor Agreement (https://plone.org/foundation/contributors-agreement) ?

**Comment by tulikavijay** [comment]
@svx yes I have!

**Comment by svx** [comment]
Nice !!! Perfect !

**Comment by tulikavijay** [comment]
```
class MyForm(form.SchemaForm):
        """ Define Form handling

        This form can be accessed as http://yoursite/@@my-form

        """
        grok.name('my-form')
        grok.require('zope2.View')
        grok.context(ISiteRoot)

        schema = IMyForm
        ignoreContext = True

        @button.buttonAndHandler(u'Ok')
```
I was looking at the code, how do i convert this part?
Also there are some references to grok on this one too : https://docs.plone.org/develop/plone/forms/z3c.form.html
