### ISSUE TITLE
incorrect URL for Contribute button (new docs deployment)

### ISSUE THREAD

**Issue by tkimnguyen** [plone/documentation#942]
on https://docs.plone.org/develop/plone/security/sandboxing.html#unit-testing-restrictedpython-code the Contribute button in left column (bottom) points to https://docs.plone.org/develop/plone/security/None which doesn't exist

![untitled](https://user-images.githubusercontent.com/815418/32970408-7384abc6-cbae-11e7-8a05-69670ad3a768.jpg)

**Comment by stevepiercy** [comment]
Two more broken links:

1. "Contribute" in the footer that goes to https://docs.plone.org/about/contributing.html
![contribute-footer](https://user-images.githubusercontent.com/102112/33524555-537bef38-d7d4-11e7-8552-9c4a822bd3ef.png)

2. On this page: https://docs.plone.org/develop/coredev/docs/contributors_agreement_explained.html#contributors-agreement-for-plone-explained the link to the PDF does not work, although the text of the link is correct: https://plone.org/foundation/contributors-agreement/agreement.pdf

I'd submit a PR to fix item 2, but I have no idea where the `coredev` directory lives.

**Comment by newbazz** [comment]
I would like to work on this.

**Comment by svx** [comment]
@stevepiercy thanks for reporting.

Fixed by: https://github.com/plone/buildout.coredev/pull/383 and https://github.com/plone/documentation/commit/87d4a3832436a0fb521f911d4e6c5df185badf00

**Comment by svx** [comment]
@tkimnguyen fixed with https://github.com/plone/papyrus/commit/b20695ef754d96eb8c26893f0157d371215192ec

**Comment by newbazz** [comment]
@svx hi i have now made and played with plone so i should strt solving issues right? Or anything to do before it?

**Comment by tkimnguyen** [comment]
@svx thx for the papyrus commit, but now I'm wondering what the URL should be:

- how to contribute to Plone core? (which is what you set it to, though only the first step of contributing to Plone core, which is to sign the contributor agreement)

- how to contribute to the Plone docs? (which I *thought* was the original intent of that button)

**Comment by newbazz** [comment]
@tkimnguyen so what should i do?

**Comment by svx** [comment]
@tkimnguyen We have this button on every page and it is meant for the docs, this is intentional.

**Comment by tkimnguyen** [comment]
Maybe the destination should be a page that covers all ways to contribute? I'd have to look over plone.org to see if there is something like that already. We have tried to cover this sort of question as a result of GSoC interest. The https://plone.org/get-started page is a good start. What do you think? Would need more material.

**Comment by svx** [comment]
New docs build is deployed, the big blue button works
