### ISSUE TITLE
Version selector erroneously includes "Unreleased" (new docs deployment)

### ISSUE THREAD

**Issue by tkimnguyen** [plone/documentation#943]
also at https://docs.plone.org/develop/plone/security/sandboxing.html#unit-testing-restrictedpython-code the Version selector at bottom left corner includes the choice "Unreleased" which takes you to https://docs.plone.org/unreleased (404)

![untitled 2](https://user-images.githubusercontent.com/815418/32970498-da87fa26-cbae-11e7-95c7-b93f5e63dc34.jpg)

**Comment by svx** [comment]
That is not a bug, this is in preparation of the new 'unstable' aka rolling docs for unreleased versions, this will be really soon available.
