### ISSUE TITLE
unexpected opened list

### ISSUE THREAD

**Issue by bommix** [plone/documentation#945]
Dear Ladies and Gentlemens,

as I use my LinuxMint on my( our) web-site **http://www.stura.htw-dresden.de/**
when I click to any date in the calendar 
![calender](https://user-images.githubusercontent.com/15325388/33376741-283ef486-d50f-11e7-8933-11c138ea0130.png)

opened one other site with "unexpected opened list", 

![bug](https://user-images.githubusercontent.com/15325388/33376554-62ccfe82-d50e-11e7-9277-0ede0f6020cc.png)

which definitely should be close. As I use other operating system there is no same bug.

Could You please fix it?

best regard,

bommix

**Comment by ale-rt** [comment]
This is not the proper place to submit an issue like this :)
I suggest you to first ask support in the website:

- https://community.plone.org

then, if nothing happens, file an issue on the repository:

- https://github.com/plone/Products.CMFPlone/

ANyway it seems your is a configuration problems, it seems to me that you are missing  this javascript:

-
 https://github.com/plone/Products.CMFPlone/blob/4.3.x/Products/CMFPlone/skins/plone_ecmascript/dropdown.js

Try to go to  http://www.stura.htw-dresden.de/manage_main -> portal_jacascript and look for that script.
