### ISSUE TITLE
Documentation grammar issue( Documentation/Developing bobtemplates.plone templates )

### ISSUE THREAD

**Issue by mrsaicharan1** [plone/documentation#950]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
The page contains a 'there' instead of 'their' on a certain line.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation/use case for changing the behavior?**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by svx** [comment]
Thanks for reporting !
Would you mind to tell us the exact page and line ?
Thanks again !

**Comment by mrsaicharan1** [comment]
https://docs.plone.org/develop/addons/bobtemplates.plone/bobtemplates.plone/docs/develop.html
Under the heading subtemplates, line number 4. Mention not!

**Comment by svx** [comment]
Thanks !

Fixed in: https://github.com/plone/bobtemplates.plone/pull/250

**Comment by svx** [comment]
Done, new docs build is online
