### ISSUE TITLE
Sentence formation error

### ISSUE THREAD

**Issue by mrsaicharan1** [plone/documentation#953]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
The page contains 'these test' instead of 'these tests' on a certain line.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**
For a good understanding of a documentation, we need proper English sentence formation. Even such small issues do reflect how well the organization is helping the open source community.

* **What is the motivation/use case for changing the behavior?**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by mrsaicharan1** [comment]
https://docs.plone.org/develop/addons/bobtemplates.plone/bobtemplates.plone/docs/develop.html
Under Testing ,Line 3.

**Comment by stevepiercy** [comment]
@mrsaicharan1 It's OK to submit a pull request with a good commit message, instead of writing up an issue. That would save you and the reviewer time and effort.

**Comment by svx** [comment]
@mrsaicharan1 You are more than welcome to create a Pull Request !
As we are talking here about the docs of bobtemplates, the repo is here: https://github.com/plone/bobtemplates.plone

docs.plone.org 'just' fetches the docs from there, meaning changes/improvements needs to be done there.

Thanks !

**Comment by anton-lin** [comment]
Hi, this is my first time to create a Pull Request.
Fork "https://github.com/plone/bobtemplates.plone" to my repository.
Then create a Pull Request "https://github.com/anton-lin/bobtemplates.plone/pull/1"
Please let me know if there are any problems.

**Comment by Rupeshiya** [comment]
@svx should I fix this issue ?

**Comment by AkshJain99** [comment]
@svx i would like to fix this issue

**Comment by stevepiercy** [comment]
@AkshJain99 submit a PR for review.

**Comment by AkshJain99** [comment]
okay
