### ISSUE TITLE
Adjust locations for better logic and readability 

### ISSUE THREAD

**Issue by svx** [plone/documentation#955]
* **I'm submitting a ...**
 
  - [X] feature request

* **What is the current behavior?**
Because of oir old setup we have 'weird' paths and locations, for better logic and reliability we should adjust these 

* **Example:**
- http://docs.plone.org/develop/addons/bobtemplates.plone/bobtemplates.plone/docs/

* **Motivation:**

This adds nothing for the user, I know we created this setup years ago, but since them we all learned new things.
For better usability we should rethink paths and locations, this goes together with:

 https://community.plone.org/t/broken-links-in-docs-plone-org/5678/45

**Comment by stevepiercy** [comment]
What? Closing as this makes no sense in Plone 6.
