### ISSUE TITLE
Broken link in  documentation/.github

### ISSUE THREAD

**Issue by tulikavijay** [plone/documentation#963]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
CONTRIBUTING.md in .github links to https://docs.plone.org/about/contributing.html that results in Not found -404

* **What is the expected behavior?**
Should link to https://docs.plone.org/about/contributing/index.html

**Comment by tulikavijay** [comment]
I would like to help with this

**Comment by stevepiercy** [comment]
@tulikavijay GitHub issue tips:

* Assign yourself to an issue when you actually start working on it. Until then, this ticket is not assigned.
* Adding the comment "I would like to help with this" adds no new information to the issue's actual state, but adds confusion. (When will this person work on it? Have they abandoned it? Can I work on it?)
* It does not help with [searches for open issues with "no:assignee"](https://github.com/plone/documentation/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+no%3Aassignee).
* It does send an email notification to all subscribers and makes noise.

I hope this doesn't sound like a cranky old developer, but sometimes these "meta" things are not communicated or obvious to new arrivals.

**Comment by tulikavijay** [comment]
Thanks for taking the time to explain!
PS : accidentally closed the issue.
