### ISSUE TITLE
plone-compile-resource params

### ISSUE THREAD

**Issue by iham** [plone/documentation#969]
* **I'm submitting a ...**
  - [ x] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**
BUG

* **What is the current behavior?**
wrong text for compiling resources documentation

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
[documentation](https://docs.plone.org/adapt-and-extend/theming/resourceregistry.html#compiling-bundles)
```
./bin/plone-compile-resources –site-id=myplonesite –bundle=mybundle
```
but it should be:
```
./bin/plone-compile-resources --site-id=myplonesite --bundle=mybundle
```
(see the double-dash instead of the single long dash?

* **What is the expected behavior?**
when copying the text, i'd like to only replace params.

* **What is the motivation / use case for changing the behavior?**
it's a trap!

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by svx** [comment]
Please see:

https://github.com/plone/documentation/blob/5.1/adapt-and-extend/theming/resourceregistry.rst

I added a ``code-block`` should be better readable.

It was already written as
```
/bin/plone-compile-resources --site-id=myplonesite --bundle=mybundle
```
It was bad formated :)

**Comment by stevepiercy** [comment]
Additionally when one does not use `code-block` or other code-like reST markup, and depending on the version of Sphinx in use and its configuration for either `html_use_smartypants` or `smartquotes`, quotes, dashes, and three periods will be converted to their typographically correct entities. There's also language-specific conversions. Whee!

reSt | converted to
-----|-------------
`---` | `—` em-dash
`--` | `–` en-dash
`...` | `…` ellipsis
`'` | `‘` or `’` apostrophe
`"` | `“` or `”` quote

See:
* https://docutils.readthedocs.io/en/sphinx-docs/user/config.html#smart-quotes
* http://www.sphinx-doc.org/en/stable/config.html#confval-html_use_smartypants
* http://www.sphinx-doc.org/en/stable/config.html#confval-smartquotes

**Comment by stevepiercy** [comment]
Closing as won't fix. Please reopen an issue for Plone 6 docs.
