### ISSUE TITLE
Move ZEO explanation 

### ISSUE THREAD

**Issue by svx** [plone/documentation#970]
* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request

**Note: This is NOT suited for "beginner" or people who are new !**

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Currently we explain ZEO under the installation docs.
This should move to a more general place !

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

See: https://github.com/plone/documentation/pull/967#issuecomment-370283306

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
Better docs structure and content location

**Comment by tkimnguyen** [comment]
What else should go into a general background section?

**Comment by stevepiercy** [comment]
Closing as obsolete.
