### ISSUE TITLE
link to docker images not official

### ISSUE THREAD

**Issue by Khaezzar** [plone/documentation#981]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **Do you want to request a *feature* or report a *bug*?**
in the doc the link to docker image don't go to the 'official' plone account in docker hub.
*https://docs.plone.org/manage/docker/docs/index.html*
So I don't know what to use and ask myself if the 'official' docker account is realy 'official'

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by svx** [comment]
Would you mind to explain a bit more ? I can not reproduce that.

If I go to: https://docs.plone.org/manage/docker/docs/index.html

![docker-plone-docs-site](https://user-images.githubusercontent.com/358860/37827618-834471d4-2e98-11e8-82ec-5a96a64b3319.png)

I see a link : 
![docker-plone-link](https://user-images.githubusercontent.com/358860/37827657-a58ae1ce-2e98-11e8-9f95-5d59ca310cc8.png)

This link points to:  https://hub.docker.com/r/plone/plone/

Which is official

**Comment by Khaezzar** [comment]
what I mean is that looking fo plone in hub.docker.com I found plone official that is not the one in the doc.
Yours is : https://hub.docker.com/r/plone/plone/
The other is : https://hub.docker.com/_/plone/
to reproduce : search plone in hub.docker.com => the first one is tagged as official not yours

**Comment by svx** [comment]
These are literally the same images, we push to plone/plone and from the same repo it is pushed to the 'official' account.
But just to avoid more confusion, sure we can change the link.

**Comment by svx** [comment]
Done with: https://github.com/plone/plone.docker/commit/e8a55e062b4963039746f24f2cf69ce9d3ac6c1d

Will be on docs.plone.org next time we push a new docs release
