### ISSUE TITLE
Link for phrasing of your own code review is showing error 404

### ISSUE THREAD

**Issue by sonawanemaitreya** [plone/documentation#982]
The link given for sample the [phrasing](http://ada.mbecker.cc/2012/11/22/be-your-own-code-review/) is showing error 404, under the section of reviewing your changes, in 'Working with Git and Github'. The link to page is [this](https://docs.plone.org/develop/coredev/docs/git.html).

**Comment by svx** [comment]
Fixed with https://github.com/plone/buildout.coredev/pull/443

**Comment by stevepiercy** [comment]
This was fixed years ago.
