### ISSUE TITLE
Please renew certificate for docs.plone.org !!!!

### ISSUE THREAD

**Issue by fgrcon** [plone/documentation#987]
Lets encrypt cert has expired 2018-04-01 !!!
Noa access to docs.plone.org anymore due to HTTP Strict Transport Security
cc @svx  ?

**Comment by svx** [comment]
As mentioned before, we are doing some work on the doc and on the server which is hosting the docs.
So yes, there are some 'bumps' for the next couple of hours.

Including how we do SSL certs ...

**Comment by fgrcon** [comment]
@svx: Sorry  I id not want to make troubles ...  
It's ok again (cert renewed) !!
Thank You!!

**Comment by svx** [comment]
Np ! :)
