### ISSUE TITLE
bobtemplates plone 

### ISSUE THREAD

**Issue by svx** [plone/documentation#988]
We have an issue with how we include bobtemplates.plone.

One of the main reasons why we have this is because in the beginning we had a 'hard copy' (copy and paste from the bobtemplates.plone docs).

At some point that got changed to include the docs via papyrus.

Because of that we have no issues like:

- Quality (no meant to insult people, you are awesome!) but the 'hard copy' had lots of reST, syntax, wording, etc fixes)
Now we include the 'original' ones and these are well .. different and they need some love and testing.

- The dir/content structure changed, too.

- The naming of the include is not perfect, which has partly do to with the script which is used by papyrus to include other content.

All of this needs fixing ASAP ! :)

**Comment by stevepiercy** [comment]
Closing in favor of https://github.com/plone/bobtemplates.plone/issues/570. We won't include its docs at this time.
