### ISSUE TITLE
Question: Should we include external docs in the future ?

### ISSUE THREAD

**Issue by svx** [plone/documentation#989]
In general yes, I am 150% for it.

But this needs dedication and people. Personal I still think that is the way.

I am just not convinced that this is the way for the Plone community, at least not at this given moment.

Taken the amount of people who are working on the docs in general, it is already hard enough and also not going well to maintain and improve the 'core docs'.

Not even speaking about docs of bobtemplates, ansible, docker, dexterity, etc, etc.

One other point is that it is really time consuming and hard sometimes to get docs updates in certain repos.
 

Maybe it would be better to exclude this docs again and host the on RTD, lots of them already there.

Like I said in the beginning I am still sure that including in in general way better and I know (work on) from other projects who are doing that which a huge huge success, also for branding, customer care, marketing, etc, etc.
But well, seeing the current situation of Plone, I am not sure that this is the best way for Plone right now.

Also in terms of user and that we have a responsibility for them.

**Comment by stevepiercy** [comment]
Yes, we do this with git submodules now in Plone 6 docs.
