### ISSUE TITLE
no need to run virtualenv on travis (?)

### ISSUE THREAD

**Issue by svenevs** [plone/documentation#991]
* **I'm submitting a ...**
  - [x] "bug" report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**

Report "bug".

* **What is the current behavior?**

I do not believe you need to run `virtualenv` on Travis.  [These docs](https://docs.plone.org/external/plone.app.robotframework/docs/source/travis-ci.html#travis-yml) are showing your config (?) But I don't see a `travis.yaml` in this repo.

* **What is the expected behavior?**

According to [travis docs](https://docs.travis-ci.com/user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs), python is automatically run in a virtualenv for you.  Maybe this is a new feature that was introduced after this was setup?

* **What is the motivation / use case for changing the behavior?**

Your docs were really nice and helpful to me.  I don't think this is actually a problem.  I also don't know if removing the `virtualenv` stuff is OK.  I am just getting started for my own project and things worked without needing to run `virtualenv`, but I don't know if that will be true for you :smile:

**Comment by loechel** [comment]
Hi @svenevs thanks for your report.

You might confuse that this repository is the collected documentation for Plone. This includes current best practis and recommendations on package layout and configuration.

travis-ci configuration explained in this specific doc explains how to setup and test Frontend interaction with robot test.

You are right virtualenv command is not necessary on travis, but most examples replicate local development workflows. On a local setup using the primary python in path could harm your system python. 

as using virtualenv on travis is not harmful it is sometimes better to do unnecessary steps, that could help new developers to prevent harm.

**Comment by svenevs** [comment]
> as using virtualenv on travis is not harmful it is sometimes better to do unnecessary steps, that could help new developers to prevent harm.

Very true.  And yeah having an extra venv definitely doesn't hurt :smile:
