### ISSUE TITLE
Fix for z3c.autoinclude not automatically adding a Plone package

### ISSUE THREAD

**Issue by idgserpro** [plone/documentation#992]
I just found this snippet in https://romanofskiat.wordpress.com/2012/09/25/z3c-autoinclude-does-not-automatically-include-a-plone-package/:

> Something I stumbled over just recently and is a PEBKAC again. What happens if you create a plone package and you always need to explicitly specify the zcml slot for that package? Check the namespace declaration in the setup.py. That means, what I had configured:

```python
 namespace_packages=['mooball'],
 entry_points="""
 # -*- Entry points: -*-
 [z3c.autoinclude.plugin]
 target = plone
```

> But the packages layout was “mooball.portlets.latestcontent”. After digging, I found out that simply the namespace_package is incorrectly declared. Changing it to:

```python
 namespace_packages=['mooball', 'mooball.portlets'],
 entry_points="""
 # -*- Entry points: -*-
 [z3c.autoinclude.plugin]
 target = plone
```

> got it correctly included via z3c.autoinclude.

Which would be really useful in the docs. The question is: where is the best place to put it? When searching for autoinclude in the docs we only get https://github.com/plone/documentation/blob/7cf6b33cf8c3bd04de93e5806aa5fdcf21de199a/develop/addons/components/zcml.rst.

**Comment by stevepiercy** [comment]
Closing as obsolete. See https://6.docs.plone.org/backend/upgrading/version-specific-migration/upgrade-to-60.html#autoinclude
