### ISSUE TITLE
develop/plone/i18n/contribute_to_translations needs support section updating

### ISSUE THREAD

**Issue by stevepiercy** [plone/documentation#996]
I'm not sure how to update this correctly. @gforcada last updated it.
https://github.com/plone/documentation/blame/5.1/develop/plone/i18n/contribute_to_translations.rst#L110-L111

I think the preferred method is through the Community over an email list and Gitter:
https://community.plone.org/c/development/i18nl10n

Please let me know, and I'll submit a PR.

**Comment by gforcada** [comment]
IMHO we could point to community.plone.org where we have a l10n section for that.
